### ISSUE TITLE
po2oo says: "don't know what to do with input format .po"

### ISSUE THREAD

**Issue by transl8bzimport** [translate/translate#174]
_Version: 0.8rc5_

_Originally posted by Erdal Ronahi:_

I tried to use po2oo to make an kurdish sdf-file from .po files. All I get with
commands like

po2oo -i ooo2 -l ku -t en_US.sdf -o ku.sdf
po2oo -l ku -t en_US.sdf --nofuzzy -i ooo2 ku.sdf
po2oo -i ooo2 -l ku -t en_US.sdf -o ku.sdf

are error messages like

po2oo: warning: Couldn't handle input file ooo-writer.po: don't know what to do
with input format .po, template format .sdf

for every .po-file in the directory and the subdirectories.

Funny that po2oo shouldn't know the input format .po, isn't it there to convert
.po files?

It makes no difference whether the directory ooo2 does either contain small
.po-files (Rosetta style) or one big .po-file (14,1 MB) with all the
translations, the result is always the same.

**Comment by linuxjackto1** [comment]
thanks www.movied.org
