### ISSUE TITLE
unicode problems with using pomerge

### ISSUE THREAD

**Issue by dwaynebailey** [translate/translate#176]
_Version: 0.8rc5_

Seems that string containing Unicode characters are barfing when using pomerge:

PS Need a component for tools :(

[dwayne@laptop-wifi fftb11]$ pomerge --errorlevel=traceback -t
nso/browser/chrome/browser/preferences/preferences.properties.po
nso-nso-missing-check/browser/chrome/browser/preferences/preferences.properties.po
nso/browser/chrome/browser/preferences/preferences.properties.po
processing 1 files...

pomerge: warning: Error processing: input
nso-nso-missing-check/browser/chrome/browser/preferences/preferences.properties.po,
output nso/browser/chrome/browser/preferences/preferences.properties.po,
template nso/browser/chrome/browser/preferences/preferences.properties.po:
Traceback (most recent call last):

  File "/usr/lib/python2.4/site-packages/translate/misc/optrecurse.py", line
418, in recursiveprocess
    success = self.processfile(fileprocessor, options, fullinputpath,
fulloutputpath, fulltemplatepath)

  File "/usr/lib/python2.4/site-packages/translate/misc/optrecurse.py", line
471, in processfile
    if fileprocessor(inputfile, outputfile, templatefile, **passthroughoptions):

  File "/usr/lib/python2.4/site-packages/translate/tools/pomerge.py", line 111,
in mergepo
    outputfile.write(str(outputpo))

  File "/usr/lib/python2.4/site-packages/translate/storage/po.py", line 689, in
**str**
    pesrc = str(pe) + "\n"

  File "/usr/lib/python2.4/site-packages/translate/storage/po.py", line 366, in
**str**
    postr = "".join(lines)

UnicodeDecodeError: 'ascii' codec can't decode byte 0xc5 in position 17: ordinal
not in range(128)

**Comment by linuxjackto1** [comment]
thanks www.movied.org
