### ISSUE TITLE
csv2po experiencing and __str__ related conversion problem

### ISSUE THREAD

**Issue by dwaynebailey** [translate/translate#177]
_Version: 0.8rc5_

When running csv2po on about 90 files I got this error on about 5 of them:

csv2po: warning: Error processing: input
updates-final/Final_Sepedi/toolkit/chrome/global-platform/win/intl.properties.csv,
output nso/toolkit/chrome/global-platform/win/intl.properties.po, template
templates/toolkit/chrome/global-platform/win/intl.properties.pot: Traceback
(most recent call last):

  File "/usr/lib/python2.4/site-packages/translate/misc/optrecurse.py", line
418, in recursiveprocess
    success = self.processfile(fileprocessor, options, fullinputpath,
fulloutputpath, fulltemplatepath)

  File "/usr/lib/python2.4/site-packages/translate/misc/optrecurse.py", line
471, in processfile
    if fileprocessor(inputfile, outputfile, templatefile, **passthroughoptions):

  File "/usr/lib/python2.4/site-packages/translate/convert/csv2po.py", line 186,
in convertcsv
    outputposrc = str(outputpo)

  File "/usr/lib/python2.4/site-packages/translate/storage/po.py", line 689, in
**str**
    pesrc = str(pe) + "\n"

TypeError: **str** returned non-string (type NoneType)

**Comment by linuxjackto1** [comment]
thanks www.movied.org
