### ISSUE TITLE
Use lxml elementsoup instead of beautifulsoup

### ISSUE THREAD

**Issue by friedelwolff** [translate/translate#1813]
_Version: trunk_

Since we already have a dependency on lxml, it would be ideal to use lxml.html.soupparser. It still uses beautifulsoup in the backend, but provides the lxml API and a few other advantages as explained here:
http://codespeak.net/lxml/elementsoup.html

**Comment by nijel** [comment]
As `lxml.html.ElementSoup` is now just an [legacy interface to BeautifulSoup](https://lxml.de/api/lxml.html.ElementSoup-module.html), porting the code doesn't make much sense - the dependency would stay, it would just use legacy API.
