### ISSUE TITLE
Missing strings originally translated in editor/ui/chrome/composer/editorPrefsOverlay

### ISSUE THREAD

**Issue by transl8bzimport** [translate/translate#184]
_Version: 0.8rc6_

_Originally posted by Oscar Manuel Gómez Senovilla:_

The file editor/ui/chrome/composer/editorPrefsOverlay in thunderbird 1.5 returns
only one untranslated string:
# : editorCheck.accesskey

msgid "c"
msgstr ""

**Comment by linuxjackto1** [comment]
thanks www.movied.org
