### ISSUE TITLE
Missing strings originally translated in mail/chrome/messenger/addressbook/abCardOverlay.dtd

### ISSUE THREAD

**Issue by transl8bzimport** [translate/translate#185]
_Version: 0.8rc6_

_Originally posted by Oscar Manuel Gómez Senovilla:_

In thunderbird 1.5 file mail/chrome/messenger/addressbook/abCardOverlay.dtd, I
get two untranslated strings, but I think that what fails is the pot file,
producing lines like this:
# : WorkAddress2.label

msgid ""
"_: WorkAddress2.label\n"
""

and several like these:

msgid ""
"_: \n"
""
msgstr ""

msgid ""
"_: \n"
""
msgstr ""

**Comment by linuxjackto1** [comment]
thanks www.movied.org
