### ISSUE TITLE
SGML comment shown as string

### ISSUE THREAD

**Issue by transl8bzimport** [translate/translate#187]
_Version: 0.8rc6_

_Originally posted by Oscar Manuel Gómez Senovilla:_

In the suscribe.dtd file, there's one commented multiline entity that is
converted to an "usable" entity.

...
<!ENTITY server.accesskey             "A">
<!ENTITY subscribedHeader.label       "Subscribe">

<!ENTITY namefield.label              "Show items that contain:">
...

**Comment by linuxjackto1** [comment]
thanks www.movied.org
