### ISSUE TITLE
Variable names should be stripped from messages

### ISSUE THREAD

**Issue by friedelwolff** [translate/translate#188]
_Version: 0.8rc6_

Many of the filter checks remove variables as part of the process of checking a
certain quality. This removes the variable markers, but keeps the variable name,
which means that the variable name must conform to the rest of the check (sane
capitalisation, for example), which is meaningless and out of the translators
hands and domain.

This enhancement should remove the variable names too, as follows:
msgid "The $ProgramName$"
msgstr "Die $ProgramName$"
is good and should be accepted by all tests. If only the $-signs are stripped,
the word "ProgramName" remains in the string, and could fail some tests, like
proper capitalisation, unchanged, wrong characters, etc. If stripped as "The "
and "Die " gives a better indication of the parts where the translator should be
spending the effort. 

An alternative is to replace it with another placeholder, like replacing it with
the first allowed character in the script of the target language ('a' for Latin
script, for example).

**Comment by linuxjackto1** [comment]
thanks www.movied.org
