### ISSUE TITLE
PHP conversion with space before comma fails

### ISSUE THREAD

**Issue by dwaynebailey** [translate/translate#1898]
_Version: trunk_

We are not able to extract units from this file from the second unit onwards because we fail with a space before the comma.  Remove the command and we succeed.

``` php
$english = array(
         'item:site'  =>  "Sítios",
         'login'  =>  "Entrar" ,
         'loginok'  =>  "Entrou com sucesso." ,
```

**Comment by bobhairgrove** [comment]
Is there any progress on this? I cannot get `po2php` to work for arrays or for define formats ... Getting at least `define(...)` to work would be awesome!

**Comment by dwaynebailey** [comment]
@bobhairgrove is your issue related to "space before comma" or another issue?  Or some other issue?

**Comment by bobhairgrove** [comment]
Thanks for answering so quickly, Dwayne. I cannot get any translation to work with PHP "define(...)" syntax, whether with or without commas.

Here is the PHP template file "script_EN.php":

`<?php`
`define("SBBL_ERROR_PAGE_TITLE", "SBBL &mdash; Error");`
`define("SBBL_ERROR_PAGE_REDIRECT_MSG", "In %d seconds you will be redirected to the %s page.");`
`define("SBBL_ERROR_PAGE_REDIRECT_MAIN", "main");`
`define("SBBL_ERROR_PAGE_REDIRECT_LOGIN", "login");`
`define("SBBL_ERROR_PAGE_HEADER", "An error has occurred in the SBBL application:");`
`?>`
`
I run this command to produce a POT translation template file:
`php2po -P script_EN.php -o script_EN.pot`

So far, so good. I translate the strings in the POT file and save it as "script_DE.po":

` #. extracted from script_EN.php`
` #, fuzzy`
`msgid ""`
`msgstr ""`
`"Project-Id-Version: PACKAGE VERSION\n"`
`"Report-Msgid-Bugs-To: \n"`
`"POT-Creation-Date: 2016-07-07 00:23+0200\n"`
`"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"`
`"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"`
`"Language-Team: LANGUAGE <LL@li.org>\n"`
`"MIME-Version: 1.0\n"`
`"Content-Type: text/plain; charset=UTF-8\n"`
`"Content-Transfer-Encoding: 8bit\n"`
`"X-Generator: Translate Toolkit 2.0.0b2\n"`

`#: define("SBBL_ERROR_PAGE_TITLE"`
`msgid "SBBL &mdash; Error"`
`msgstr "SBBL &mdash; Fehlermeldung"`

`#: define("SBBL_ERROR_PAGE_REDIRECT_MSG"`
`msgid "In %d seconds you will be redirected to the %s page."`
`msgstr "In %d Sekunden werden Sie zur %s umgeleitet."`

`#: define("SBBL_ERROR_PAGE_REDIRECT_MAIN"`
`msgid "main"`
`msgstr "Hauptseite"`

`#: define("SBBL_ERROR_PAGE_REDIRECT_LOGIN"`
`msgid "login"`
`msgstr "Login-Seite"`

`#: define("SBBL_ERROR_PAGE_HEADER"`
`msgid "An error has occurred in the SBBL application:"`
`msgstr "Ein Fehler ist in der SBBL-Anwendung aufgetreten:"`

Next, I run this command to produce the PHP file (in German, supposedly):
`po2php --progress=verbose -t script_EN.php -i script_DE.po -o script_DE.php`

A file is created, but it is an exact copy of the English original. :( As you can see, the only spaces outside of the message strings are those in the PHP "define()" commands, one after the comma separating the constant from the value.

**Comment by dwaynebailey** [comment]
@bobhairgrove new bug new issue please.  For the simple reason that this bug is about space before comma. And I've just seen this same comment posted in #3283 which is also unrelated.

**Comment by bobhairgrove** [comment]
OK, will do ... thanks!
