### ISSUE TITLE
Duplicate entry in PHP files causes parsing failure

### ISSUE THREAD

**Issue by dwaynebailey** [translate/translate#1899]
If we have two entries that are identical then we can't parse and will fail.  The parsing fail is because in conversion when we use `base:makeindex()` because our location comments are identical we make them `None`, dropping any previous translation.

We need to decide what to do here:
1) Change behaviour to warn and take the last one
2) Make PHP not use location comments

**Comment by unho** [comment]
Commit 8bc169ec added the ability to warn about duplicate entries and take only the first appearance.

@dwaynebailey do you think this closes the issue properly?

**Comment by unho** [comment]
Closing this since the commit referenced above provides some fix, despite it doesn't pick the last occurrence but the first one.
