### ISSUE TITLE
.properties files personalities for Mozilla and Java

### ISSUE THREAD

**Issue by dwaynebailey** [translate/translate#193]
_Version: 0.9a1_

Current .properties files are designed for Mozilla's use of .properties. 
Ideally we should be able to work with proper Java .properties files.

Please refer to #12 which discussed some of the needs for Java conformance. 
This bug however superceded #12.

Please us this bug to collect references and to point to other bugs that relate
to Java .properties conformance.

My feeling is that we will have to introduce a concept of personalities within
the properties.py storage module.  By default prop2po and friends would invoke
the Java conformance.  While when run from moz2po the Mozilla personality would
be used.

**Comment by linuxjackto1** [comment]
thanks www.movied.org
