### ISSUE TITLE
properties::getoutput doesn't use personality data

### ISSUE THREAD

**Issue by dwaynebailey** [translate/translate#1937]
_Version: trunk_

If you are using .strings files on Pootle then the output is broken because we do a few bad things in properties::getoutput()

1) We don't use any of the personality information about quotes or end delimiters
2) We do some encoding of the values before adding them to the ouput and then we encode again in **str**()

**Comment by nijel** [comment]
I believe this is working now properly (I would certainly see that in Weblate if it would not). Fixing commit might be 620b9a953
