### ISSUE TITLE
browser/defines.inc needs a section uncommented during po2moz

### ISSUE THREAD

**Issue by dwaynebailey** [translate/translate#196]
_Version: 0.9a1_

In browser/defines.inc which we manipulate the mozfunny2po there is a section
that needs to be uncommented and changed:

---
# If non-English locales wish to credit multiple contributors, uncomment this
# variable definition and use the format specified.
# define MOZ_LANGPACK_CONTRIBUTORS em:contributorTranslate.org.za/em:contributor

---

The translator needs to add themselves and uncomment this line.

We should do this automagically as otherwise if you work directly with the .inc
file your changes will be overwritten

**Comment by linuxjackto1** [comment]
thanks www.movied.org
