### ISSUE TITLE
moz2po should localize searchplugins *.src files

### ISSUE THREAD

**Issue by dwaynebailey** [translate/translate#202]
_Version: 0.9a1_

The searchplugins directory in browser/ folder contains a number of .src files
which define how you should interact with a given searhc engine for the Firefox
quick search widget.

We need to be able to localise these.

This bug raises the need:
https://bugzilla.mozilla.org/show_bug.cgi?id=330370#c15

This should probably be added to the mozfunny2po files.

**Comment by linuxjackto1** [comment]
thanks www.movied.org
