### ISSUE TITLE
mercurial fails when trying to commit untracked file

### ISSUE THREAD

**Issue by ichernev** [translate/translate#2063]
_Version: trunk_

_Created [attachment 793](http://bugs.locamotion.org/attachment.cgi?id=793)_

patch to fix the problem

If the user tries to commit to VCS, using mercurial and the file is not tracked yet (this may happen for example if the file was copied from a template) then hg commit fails.

It should add the file and then commit successfully.

**Comment by nijel** [comment]
Related code was removed in https://github.com/translate/translate/pull/4069
