### ISSUE TITLE
Validate that html2po can convert bookmarks.html in Mozilla source

### ISSUE THREAD

**Issue by dwaynebailey** [translate/translate#209]
Depends on:
- [x] #120 html2po must wrap multiline extracts in double quotes to make valid PO files

_Version: 0.9a1_

We need to validate that we can fully localise the bookmarks.html file in
Mozilla.  Also check if we can't remove some of the rubbish, there are very very
long <A> tags that will confuse a localiser.  Perhaps, as this is a bookmarks
file, in this instance <A> tags should not appear in the text.

**Comment by linuxjackto1** [comment]
thanks www.movied.org
