### ISSUE TITLE
Confirm whether Apache-2.0 patches used in GPL-2.0+ licensed translate-toolkit 1.9.0

### ISSUE THREAD

**Issue by elchevive** [translate/translate#2126]
*Version: trunk*

Hi all!

While putting translate-toolkit into openSUSE Factory (the development version of openSUSE) the SUSE Legal Team review the source files of packages. For virtaal I have no problem, just adjust the spec to contain License: GPL-2.0+ and LGPL-3.0 (as autocorr files came from OpenOffice an are LPGL).

But the problem they find is related to translate-toolkit and are express here:

"The license for translate-toolkit 1.9.0 is GPL-2.0+ (as stated by the spec file
and the majority of files in the package). However, there seems to be the
possibility that the GPL-2.0 incompatible Apache-2.0 license has been used with
some files:

translate/doc/api/translate.misc.diff_match_patch-module.html
translate/doc/api/translate.misc.diff_match_patch-pysrc.html
translate/misc/diff_match_patch.py

Can you please check on what the effect of including the .py file is. For
example, is it patched into existing GPL licensed files? Is it imported by such
files? If any of these are true, there may be problems with GPL compatibility."

source: https://bugzilla.novell.com/show_bug.cgi?id=750652

Can you guys help me with that subject?

Regards

**Comment by unho** [comment]
Translate Toolkit uses diff-match-patch as an external dependency since 1.12. Specifically see commits https://github.com/translate/translate/commit/e266d7b16fbc21aa45686649855a68120f0618ec and https://github.com/translate/translate/commit/e9ee9489f0c2e8a63f3e39144e9859efdcff96af. So closing this.

**Comment by elchevive** [comment]
Hi,

diff_match_patch still exist in the 1.13.0 .tar.bz2
(https://github.com/translate/translate/blob/master/translate/misc/diff_match_patch.py) and are still incompatible with GPL2 which leads me to still have to remove it out of openSUSE package.

**Comment by unho** [comment]
@elchevive It is still there, but the previous content was completely removed. That file just imports diff-match-patch and reexports it again for backwards compatibility. Just check the code and see the file was completely rewritten from scratch and it is 2 lines of code now.

**Comment by elchevive** [comment]
Sorry, you are right! Thanks!
