### ISSUE TITLE
Version control might commit extra files when adding new files

### ISSUE THREAD

**Issue by friedelwolff** [translate/translate#2158]
_Version: trunk_

When we add new files to a VCS, we commit afterwards. We currently reuse the commit code that basically commits a containing directory of the files. If there are changes in already tracked files, they will be committed in the same commit where we commit the new files, maybe even with all other files added (.translation_index, etc.) that weren't intended at all.

We should add an interface to commit multiple files, and use that to explicitly commit the newly added files instead of everything. We will be able to use it for other things in future as well, I guess.

**Comment by nijel** [comment]
Related code was removed in https://github.com/translate/translate/pull/4069
