### ISSUE TITLE
php2po doesn't handle Nucleus CMS php translation format

### ISSUE THREAD

**Issue by unho** [translate/translate#2238]
_Version: 1.9.0_

Hi,
these last I was collecting translations files in strange formats (at least for me since I am very used to Gettext format) and I found one kind of PHP translation file format that php2po seems not to be able to handle. The format is like the following lines:

// for use in archivetype-skinvar
define('_ARCHIVETYPE_DAY',          'day');
define('_ARCHIVETYPE_MONTH',        'month');

// tickets (prevents malicious users to trick an admin to perform actions he doesn't want)
define('_ERROR_BADTICKET',          'Invalid or expired ticket.');

You can download a lot of files of these kind (including the one for english) from http://nucleuscms.org/languages.php

Bye

**Comment by nijel** [comment]
This should work fine since using phply to parse the PHP files, it seems to match following test:

https://github.com/translate/translate/blob/2a74e4efbf1e6271998dcc198aa8275e73005625/translate/storage/test_php.py#L253-L264
