### ISSUE TITLE
html2po can't extract and insert nested <ul>

### ISSUE THREAD

**Issue by chhitz** [translate/translate#2603]
_Version: 1.9.0_

_Created [attachment 879](http://bugs.locamotion.org/attachment.cgi?id=879)_

nested <ul> testcase

In nested html lists html2po adds the opening <ul> to the preceding msgid. The attached test case produces msgid "item 1 <ul>" instead of the expected "item 1".

**Comment by anderskaplan** [comment]
I cannot reproduce this issue and the attachment link is broken. Suggest closing.
