### ISSUE TITLE
Land improved pofilter XML check contributed by LibreOffice

### ISSUE THREAD

**Issue by friedelwolff** [translate/translate#2607]
*Version: trunk*

Zolnai Tamás posted a new check for XML tags which seems to give less false positives.

http://markmail.org/thread/tjuohpd6t7bxogl4

We could consider simply incorporating it, but if it is generic enough, we might want to try and merge it with the current xmltags test to avoid having two tests checking (basically) the same thing.

**Comment by unho** [comment]
That patch landed in 097852bd. So closing this.
