### ISSUE TITLE
Clarify license version for toolkit

### ISSUE THREAD

**Issue by dwaynebailey** [translate/translate#2799]
_Version: trunk_

*\* licence **

In your source files you are quite clear about the licence being GNU GPL v2 or
any later version but in README.rst and docs/license.rst it just says "GPL"
without saying which GPL (GNU GPL? Nethack GPL? v2+? v3 only?). Perhaps a link
to the GPL online and/or mention of the COPYING file would be appropriate too.

**Comment by nijel** [comment]
I believe this has been addressed in 0336f2d6442828fac0bda7bef5c4946f510dd149.
