### ISSUE TITLE
USECPO=1 testing aborts on Travis

### ISSUE THREAD

**Issue by dupuy** [translate/translate#2859]
_Version: trunk_

Something in test_po2prop.py is failing in an abrupt way when USECPO=1 and cpo.py is used for output.  Not much other information available there as it is aborting without reporting any errors on that test module.

translate/convert/test_po2php.py ..........x..........x.
translate/convert/test_po2prop.py ............./home/travis/build.sh: line 149: 1265 Aborted py.test -r EfsxX

The command "py.test -r EfsxX" exited with 134.

Done. Your build exited with 1.

**Comment by claudep** [comment]
I think the issue is now solved (due to recent work on stripping duplicate messages). libgettextpo didn't like duplicate messages. Of course, there are still ~70 test failures with USECPO=1, but at least no abrupt exit.

**Comment by nijel** [comment]
It did not abort for some time and anyway we're no longer running these tests since e96c3629edbe0d59bcf80348ec5d6646c41944d3.
