### ISSUE TITLE
Add support for Android plurals

### ISSUE THREAD

**Issue by dupuy** [translate/translate#2900]
_Version: trunk_

Lukakama (https://github.com/lukakama) wrote
(in https://github.com/translate/translate/pull/23):

> Added initial support for Android plurals.
> 
> It was implemented and tested using Weblate, so I don't know if it would work
> for Pootle or other applications, but I hope that this initial implementation
> could be used as base for further development.

Android plurals use CLDR plural rules, so some of the issues relevant to recent Mozilla plural work may apply here as well (i.e. how, if at all, do we want to set PO plural equations when converting) but they are a bit beyond the scope of this patch, which simply tries to support storing/loading plural forms as such.

**Comment by nijel** [comment]
I think this can be closed Android plurals are fully supported and we even have the CLDR data for that (see a6f041f150c91759f38a8e0787ebd7ab165710ca).
