### ISSUE TITLE
xmltags check warns about email addresses

### ISSUE THREAD

**Issue by transl8bzimport** [translate/translate#3067]
_Version: 1.10.0_

_Originally posted by Gabor Kelemen:_

pofilter currently marks translators email addresses between <> as added tags. These are completely valid in the below situations, so pofilter should ideally not complain about these.

Is it possible to add an exception from xmltags check in strings "" (the empty header string) and translator-credits?

gabor@micimacko:~/src/gnome/gnome-system-monitor/po$ pofilter -t xmltags hu.po 
processing 1 files...
msgid ""
msgstr ""
"Project-Id-Version: gnome-system-monitor master\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2013-08-06 10:01+0200\n"
"PO-Revision-Date: 2013-08-06 06:29+0200\n"
"Last-Translator: Gabor Kelemen <kelemeng at gnome dot hu>\n"
"Language-Team: Hungarian <openscope at googlegroups dot com>\n"
"Language: hu\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"
"X-Generator: Lokalize 1.5\n"
# (pofilter) xmltags: Added XML tags
# : ../src/interface.cpp:397

msgid "translator-credits"
msgstr ""
"Dvornik László <dvornik at gnome dot hu>\n"
"Kelemen Gábor <kelemeng at gnome dot hu>\n"
"Tímár András <timar at gnome dot hu>\n"
"Ványi Róbert <robi at mora.u-szeged dot hu>"
[###########################################] 100%

**Comment by claudep** [comment]
I just tested and can confirm that providing `--gnome` excludes the translator credits units.
