### ISSUE TITLE
aeidon module no longer available for python 2

### ISSUE THREAD

**Issue by llimeht** [translate/translate#3068]
_Version: 1.10.0_

As discussed in Debian bug #714063 [1], the aeidon module has been converted from python 2 to python 3 in a non-backwards compatible fashion. As a result, it is no longer available for translate-toolkit.

In the long run, translate-toolkit and friends need plan for python 3 but in the short term, a plan for what happens when modules like this just disappear would be good.

I suspect that I will have to disable aeidon support in the Debian translate-toolkit package quite soon, but any other suggestions most happily received.

[1] http://bugs.debian.org/714063

**Comment by unho** [comment]
Closing this since Translate Toolkit currently tries gaupol as a fallback if aeidon cannot be imported.
