### ISSUE TITLE
po2tmx stops conversion when an invalid XML is found

### ISSUE THREAD

**Issue by transl8bzimport** [translate/translate#3147]
_Version: trunk_

_Originally posted by Jordi Mas:_

When we convert a PO to an XML, po2tmx stops the conversion when founds an XML char is not XML.

Example:
1. Download -> http://translationproject.org/PO-files/ca/xchat-2.8.8.ca.po
2. Do po2tmx -l ca xchat-2.8.8.ca.po -o xchat.tmx

You get:

po2tmx: warning: Error processing: input xchat-2.8.8.ca.po, output xchat-2.8.8.ca.tmx, template None: All strings must be XML compatible: Unicode or ASCII, no NULL bytes or control characters
[###########################################] 100%

The problem is that the PO contains chars like STX[1] that are valid UTF-8 chars but are invalid XML chars[2].

My expectation that the file is processed and does not stop when it finds an error. I think that is a better option to report on the error, skip the strings that cannot be converted to XML because they contain invalid XML chars, and continue with the rest of file.

Jordi,

[1] http://en.wikipedia.org/wiki/Start_of_text#STX
[2] http://en.wikipedia.org/wiki/Valid_characters_in_XML

**Comment by nijel** [comment]
Should be fixed by https://github.com/translate/translate/pull/5205
