### ISSUE TITLE
Not output file from rc files

### ISSUE THREAD

**Issue by PhoneixS** [translate/translate#3199]
I have tried to convert my rc files (and other test rc files) to po using rc2po but it said 100% completed although not output file is created.

I don't know what I'm doing wrong, I have tried different versions (1.12.0-rc1 in Ubuntu 14.04 and 1.9.0 in Windows). All time with the same result.

For example:

```
~$ rc2po lang/ pot/ --errorlevel traceback
WARNING:rc2po:Output directory does not exist. Attempting to create
processing 7 files...
[###########################################] 100%
```

But pot directory is empty.

In lang directory I have http://sourceforge.net/p/wine/code/ci/master/tree/dlls/avifil32/avifil32.rc file to test if it was a problem in my rc files, but nothing.

It's very strange as it don't get me any error. It's a bug or is something that I'm doing wrong?

**Comment by SantosSi** [comment]
@PhoneixS: have you had time to review @unho's proposed solution #3204?

**Comment by PhoneixS** [comment]
I'm sorry but nowadays I don't use rc2po, we have moved to other projects that don't need it so I'm a bit disconnected from it.

**Comment by mkalkbrenner** [comment]
I run in the same issue here: 100% completed but no pot or po is created.

The rc-files we try to convert/extract could be find here:
https://github.com/mjrgh/PinballY

Examples:
https://github.com/mjrgh/PinballY/blob/master/PinballY/PinballY.rc
https://github.com/mjrgh/PinballY/blob/master/PinballY%20Admin%20Mode/PinballY%20Admin%20Mode.rc

**Comment by ImaAlvarez19** [comment]
@mkalkbrenner 
Hi, could you solve this? I have the same problem/
