### ISSUE TITLE
Use pyparsing to parse rc files

### ISSUE THREAD

**Issue by PhoneixS** [translate/translate#3204]
The actual parsing for RC file format is insufficient for this format. With python regex you can't use recursion (needed for menus and submenus). So you have two options, simplify it (read as only search for strings between " or ') or use a more advanced library.

I have opted for the second approach, and I'm doing a fork that use pyparsing (you can read more about it in http://pyparsing.wikispaces.com/ ).

The fork is in https://github.com/PhoneixS/translate/tree/pyparsing-rc

For now, it do the rc2po conversion correctly. And I need to test the other way.

This issue is to ask for a better approach to parse rc files, and my fork is an example of how can it be done.

I know that adding a dependency isn't accepted normally, so my fork will be there just in case is needed.

**Comment by nijel** [comment]
Closing in favor of https://github.com/translate/translate/pull/3961
