### ISSUE TITLE
Move patches for ConvertOptionParser to ConvertOptionParser

### ISSUE THREAD

**Issue by unho** [translate/translate#3228]
See:

* https://github.com/translate/translate/blob/5204d7a0/translate/convert/odf2xliff.py#L39-L41
* https://github.com/translate/translate/blob/5204d7a0/translate/convert/xliff2odf.py#L121-L123
* https://github.com/translate/translate/blob/5204d7a0/translate/convert/idml2po.py#L36-L38
* https://github.com/translate/translate/blob/5204d7a0/translate/convert/po2idml.py#L155-L157

**Comment by claudep** [comment]
This is now obsolete, as we consistently open files in binary mode.
