### ISSUE TITLE
Single space is not formatted as \0020

### ISSUE THREAD

**Issue by okulev** [translate/translate#3232]
Using latest 1.13.0-rc1, the following properties in Firefox OS are written in `apps/sms/sms.properties` as:

```
phone-type-separator = ,\u0020
phone-carrier-separator =
```

The second property should be `\u0020` because in the PO file it is " " (single whitespace).

**Comment by nijel** [comment]
This was introduced in 1.12.0-rc1 via ab17c6afdd.
