### ISSUE TITLE
Add support for Localized Property List File (OS X >= 10.9 and iOS >= 7)

### ISSUE THREAD

**Issue by nijel** [translate/translate#3238]
Some time ago [Apple introduced "Localized property list file"](https://developer.apple.com/library/ios/releasenotes/Foundation/RN-Foundation/#//apple_ref/doc/uid/TP30000742-CH2-SW56).

You can find more [here](https://developer.apple.com/library/ios/documentation/General/Reference/InfoPlistKeyReference/Articles/AboutInformationPropertyListFiles.html) and another explanations [here](https://github.com/objcio/articles/blob/master/2014-02-10-string-localization.md#plural-and-gender-support).
Some nice guy also set up a test repository [here](https://github.com/ObjectiveToast/LocalizeTesting), demonstrating the usage of the new file (`.stringsdict`).

Any future plan to support this?

**Comment by romanr** [comment]
This is a current official best practice for non plurals localization for macOS/iOS: https://developer.apple.com/library/archive/documentation/MacOSX/Conceptual/BPInternational/LocalizingYourApp/LocalizingYourApp.html#//apple_ref/doc/uid/10000171i-CH5-SW10    
Without support for `stringsdict` proper Localization of macOS/iOS can not be achieved. This is a show stopper level issue.

**Comment by nijel** [comment]
The base format has support in Python stdlib: https://docs.python.org/3/library/plistlib.html
