### ISSUE TITLE
csv2po new line

### ISSUE THREAD

**Issue by ghost** [translate/translate#3246]
Hi there, i have CSV with:

```csv
"yellow pencil","żółty\nołówek"
"photo description","opis zdjęcia"
```

And converted with csv2po:

```po
msgid "yellow pencil"
msgstr "żółtynołówek"

msgid "photo description"
msgstr "opis zdjęcia"
```

How to convert with save format "\n", script delete \ from string.

**Comment by nijel** [comment]
Proposed fix is here: https://github.com/translate/translate/pull/3880
