### ISSUE TITLE
JSON storage fails adding new units

### ISSUE THREAD

**Issue by nijel** [translate/translate#3249]
When adding new units to JSON, it fails as it does not update the storage document, only adds it to internal list of units. Whenever calling ``__str__`` later (eg. through saving), the newly added units are not present as it just dumps state of the file when it was loaded.

**Comment by nijel** [comment]
I've implemented simple workaround for our needs, but that's far from supporting all JSON formats translate-toolkit supports: https://github.com/nijel/weblate/blob/master/weblate/trans/aresource.py#L32

**Comment by unho** [comment]
@nijel Can you please PR that change alongside some tests to ensure it works?

**Comment by nijel** [comment]
I'm not sure it's good enough for merging as it's really limited. Also there is no existing testsuite for JSON, so it's hard to check what all is current module supporting...

**Comment by nijel** [comment]
PS: Also seeing how slow are pull requests merged does not motivate one to produce new ones...

PS2: I've just realized that there is already a pull request fixing this issue open for few months: https://github.com/translate/translate/pull/3224

**Comment by jleclanche** [comment]
@nijel we're not great at handling PRs on TTK; mostly because of our current Pootle release cycle which has been extremely demanding. But if it's a PR, it will at least get looked at and merged. If it's just sitting in an issue it'll die out after a week.

**Comment by nijel** [comment]
As I've already mentioned before, the PR with basically same code as mine is there since October, it just was not understood for some reason: https://github.com/translate/translate/pull/3224 I hope this bug report will work as explanation.

**Comment by unho** [comment]
@nijel Our apologies for the delay on merging stuff, but sometimes we merge most of the PRs just before releases, and our stuff just got in the middle.

Also thanks for linking that PR. I now finally understand what problem @SirAnthony was trying to fix there.

I see that the code differs in both approaches, since one uses `unit.source` and the other `unit.target`. My guess is that `unit.target` is most likely the desired one. @nijel can you please check on your side?

**Comment by nijel** [comment]
@unho If you look at json module source, it really does not matter which attribute is used: https://github.com/translate/translate/blob/master/translate/storage/jsonl10n.py#L96

**Comment by unho** [comment]
@nijel Yes. Thanks. Also I just found that I had a local branch where I added some tests. We will try to merge this as soon as possible.

**Comment by nijel** [comment]
@unho Thanks, the slow progress on merging PRs basically stopped me from digging deeper into TTK issue I face...
