### ISSUE TITLE
Irish plural form is incorrect

### ISSUE THREAD

**Issue by dwaynebailey** [translate/translate#3255]
I'm looking at moving my PO files onto Pootle now.   One thing I'm
worried about are the plural forms.  It looks like Pootle thinks Irish
has 3 plural forms, which stems from an old old bug on the gettext web
site

http://www.gnu.org/savannah-checkouts/gnu/gettext/manual/html_node/Plural-forms.html

This is wrong, and it's been corrected in CLDR and everywhere else
that I can think of.  The correct plural form string is this one:

```
"Plural-Forms: nplurals=5; plural=n==1 ? 0 : n==2 ? 1 : (n>2 && n<7) ?
2 :(n>6 && n<11) ? 3 : 4;\n"
```

Even if there are no plurals in the Mozilla strings, it would be
helpful to have this correct since it gets added to the exported PO
files in the mozilla-lang repo, and when the plural form string is
wrong, it makes it a pain to include the files in a big
compendium/translation memory.

**Comment by kscanne** [comment]
That's strange.  It looks like you already had 5 plural forms.  But the MozillaPootleL10nBot includes nplurals=3 when committing to git: 

https://github.com/translate/mozilla-lang/blame/master/ga_IE/esr.lang.po#L14

**Comment by dwaynebailey** [comment]
@kscanne I think its a combination of outdated toolkit and outdated Irish entry on mlo.  I'm slowly fixing them all.
