### ISSUE TITLE
php arrays, php2po

### ISSUE THREAD

**Issue by beachmat** [translate/translate#3256]
I'm trying php2po to translate some php string arrays in this format:
```php
array(
  'page_title'=> 'blabla'
)
```
but one issue is that HTML tags in the strings are appearing in the text to be translated. Is there any way round this?
thanks

**Comment by unho** [comment]
Can you share the file you are using? I don't see any HTML tag on the snipppet.

**Comment by beachmat** [comment]
I can't share the file, but say for example this:

  'sign_up_text'  => '<p><strong>Here is some strong text</strong>and some more text</p>

I imagine this is not an issue with the file format or conversion and that it's up to the translation environment as to how to present the tags, but I thought it was worth asking.

**Comment by unho** [comment]
@beachmat We don't consider this to be a problem on the parsing. If you are not OK with HTML tags to be included in the translatable texts then maybe you can let your developers know about that. Some translation tools can provides you some help on treating those HTML tags as not translatable content, for example Virtaal.

I am closing this issue.
