### ISSUE TITLE
Maximum file size

### ISSUE THREAD

**Issue by JohnnyKing94** [translate/translate#3259]
What is the maximum file size for the conversion of csv2po... i have 3MB csv file and i can't conver it into .po
After hours it prints this output KILLED. The csv has 50000 lines in it, is there a limit even for this?

What's the optimal conversion?

Thx in advance

**Comment by unho** [comment]
@JohnnyKing94 As far as I can tell we never tested the limit. 50000 lines feels too large, but maybe it is failing for some other reason. Can you please provide a more detailed error output? A traceback would be fine. Also if you can share the file we might be able to test on our side as well.

Finally I must say I am curious why are you dealing with a file so big.

**Comment by JohnnyKing94** [comment]
Ok i resolved the situation converting the file first in txt (always with 50K of strings), then i converted into .po file and uploaded, it works... totally... it's a .lang file of a game... there are around 750K string, and i split into 14 files... all working, sometimes the pootle server is a little laggy, but i understand that :D

anyway i encoutered a new problem, when we translate something, the sumbmissions keep doubling... and then i found this on the database: https://dl.dropboxusercontent.com/u/89718989/Pootle/bandicam%202015-04-14%2013-17-11-753.jpg

As you can see, the pootle server stores the real submission and this string value "200", why?? how can i fix it??? it's annoying and the stats shown on the website are doubled too :|

Thx

**Comment by unho** [comment]
@JohnnyKing94 I recommend you using a bilingual format, like PO.

**Comment by JohnnyKing94** [comment]
I use po files converted as i said... all the files are converted and into .po files... everything works, except this.

**Comment by JohnnyKing94** [comment]
I just checked your pootle demo and even your demo has this problem... re-open this ticket and mark this as bug...

Look, this user has 4 submissions: http://pootle.locamotion.org/accounts/bokar/
but when you click on "4", you see only 2 submissions made by him: http://pootle.locamotion.org/ach/pootle/translate/#filter=user-submissions&user=bokar

There's an error in the application, please address this issue

Thx in advance

**Comment by JohnnyKing94** [comment]
I opened a ticket in the proper channel: https://github.com/translate/pootle/issues/3673

Greetings
