### ISSUE TITLE
Parse EOL as newline on Android strings

### ISSUE THREAD

**Issue by dllud** [translate/translate#3262]
Contrary to what @nijel implemented on [Android resources support #2](https://github.com/translate/translate/pull/2#issuecomment-8185814) it is (now?) possible to [use a real EOL instead of an explicit `\n`](http://stackoverflow.com/a/17288710) on Android strings' files. This makes the strings' files easier to read.

Thus translate-toolkit should parse an EOL as a newline instead of a whitespace.

**Comment by nijel** [comment]
I've created pull request for this issue: https://github.com/translate/translate/pull/3442

**Comment by nijel** [comment]
It seems that it's not really this way in all cases, see https://github.com/WeblateOrg/weblate/issues/1418#issuecomment-288031554. However my knowledge of Android is quite limited, so it's really hard to decide what should be the correct approach here.
