### ISSUE TITLE
[html2po] <pre> code block snippets normalization problem

### ISSUE THREAD

**Issue by stephenjang** [translate/translate#3265]
Version: trunk

`<pre><code>` multi-line code block is should not be normalization.
### `<pre>` example:

``` html
<pre><code>// JavaScript's most important data type is the object.
// An object is a collection of name/value pairs, or a string to value map.
var book = {               // Objects are enclosed in curly braces.
    topic: "JavaScript",   // The property "topic" has value "JavaScript".
    fat: true              // The property "fat" has value true.
};                         // The curly brace marks the end of the object.</code></pre>
```
### Expect Results:

```
msgid "// JavaScript's most important data type is the object."
msgstr ""

msgid "// An object is a collection of name/value pairs, or a string to value map."
msgstr ""

msgid "var book = {               // Objects are enclosed in curly braces."
msgstr ""

msgid "    topic: "JavaScript",   // The property "topic" has value "JavaScript"."
msgstr ""

msgid "    fat: true              // The property "fat" has value true."
msgstr ""

msgid "};                         // The curly brace marks the end of the object."
msgstr ""
```
### html2po Results:

```
#: ch01.html+html.body.div.div.pre:119
msgid ""
"// JavaScript's most important data type is the object. // An object is a "
"collection of name/value pairs, or a string to value map. var book = { // "
"Objects are enclosed in curly braces. topic: \"JavaScript\", // The property "
"\"topic\" has value \"JavaScript\". fat: true // The property \"fat\" has "
"value true. }; // The curly brace marks the end of the object."
msgstr ""
```

**Comment by dupuy** [comment]
While normalization is not desirable for `<pre>` or `<code>` blocks, I can't imagine you really want to have each line as a separate msgid/msgstr.  What you probably want is something like this:
```
#: ch01.html+html.body.div.div.pre:119
msgid ""
"// JavaScript's most important data type is the object.\n// An object is a "
"collection of name/value pairs, or a string to value map.\nvar book = {    "
"           // Objects are enclosed in curly braces.\n    topic: \"JavaScript\","
"   // The property \"topic\" has value \"JavaScript\".\n    fat: true      "
"        // The property \"fat\" has value true.\n};                        "
" // The curly brace marks the end of the object."
msgstr ""
```
with spaces (and newlines) preserved.

**Comment by ivilata** [comment]
What @dupuy mentions is what I would expect too for whatever enclosed in a `<pre>` block.

The only workaround that comes to mind is going over each translation adding newlines manually in the `msgstr` (if that doesn't make tools complain about the line number mismatch), and ensure that the `msgstr` isn't blank in any translation.

This issue is still present in v3.3.6.

**Comment by ivilata** [comment]
Alternatively, if you don't want to ensure that the `msgstr` is there for all translations, you can alter your HTML to put a `<br>` at the beginning of every line in the `<pre>` block except the first one (at the cost of getting one space at the end of each line):

```
<pre>
This is
<br>a
<br>pre block.
</pre>
```

**Comment by ivilata** [comment]
An approach which finally worked for me (both for source and translations) was to use `<br>` *instead of* the newline:

```
<pre>This is<br>a<br>pre block.</pre>
```

Which is utterly ugly and partly defeats the purpose of `<pre>`, but it works at least.

**Comment by nijel** [comment]
Can you please check if https://github.com/translate/translate/pull/4428 works for you?
