### ISSUE TITLE
Problems with json2po

### ISSUE THREAD

**Issue by sleivaj-golden** [translate/translate#3274]
I have problem with json2po tool on windows with version 1.9.0.

`C:\_base\lang> json2po --template=en_GB.json it_IT.json it_IT.po
processing 1 files...`

`json2po: warning: Error processing: input it_IT.json, output it_IT.po, template
en_GB.json: __init__() got an unexpected keyword argument 'dialect'
[###########################################] 100%`

And the tool does not generate the .po file

All files are in the same folder "lang"

Thanks

**Comment by claudep** [comment]
This was fixed in 1.10.0 by commit 5d110bf8826
