### ISSUE TITLE
unit equality issue

### ISSUE THREAD

**Issue by claudep** [translate/translate#3322]
As the `__ne__` method is not defined for translation units, there is a bug with some unit comparison, for example txt units return True for both `==` and `!=`.
This patch shows the problem when running the test suite:

```diff
diff --git a/translate/storage/test_base.py b/translate/storage/test_base.py
index b65104d..fcf586b 100644
--- a/translate/storage/test_base.py
+++ b/translate/storage/test_base.py
@@ -109,6 +109,7 @@ class TestTranslationUnit:
         assert unit1 != unit3
         assert unit4 != unit5
         assert unit1 != unit6
+        assert not(unit1 == unit6)
 
     def test_target(self):
         unit = self.unit
```

This unexpectedly fails for `TxtUnit`, `RESXUnit`, and `dtdunit`.

We can define the `__ne__` method:

```diff
diff --git a/translate/storage/base.py b/translate/storage/base.py
index b2123b2..22a2bc8 100644
--- a/translate/storage/base.py
+++ b/translate/storage/base.py
@@ -141,6 +141,9 @@ class TranslationUnit(object):
         """
         return self.source == other.source and self.target == other.target
 
+    def __ne__(self, other):
+        return not self.__eq__(other)
+
     def __str__(self):
         """Converts to a string representation that can be parsed back using
         :meth:`~.TranslationStore.parsestring`."""
```

But now `test_eq()` fails, because for some units (mainly monolingual), the source is equal to the target so unit1 and unit6 are indeed identical. I tried to special case the comparison for tests subclassing `TestMonolingualUnit`, but this doesn't seem to be sufficient, as monolingual units are not all behaving the same.

Any pointer from a more experienced dev?

**Comment by unho** [comment]
No idea for now.

**Comment by dwaynebailey** [comment]
@friedelwolff I wonder if you have any ideas here?
