### ISSUE TITLE
Replace iniparse by configparser

### ISSUE THREAD

**Issue by claudep** [translate/translate#3348]
The iniparse lib is not available in Python 3. Is there a good reason to keep using this lib instead of the configparser in the standard lib?
I made some tests and with configparser, we loose the exact layout from the source file (always output as `key<space>=<space>value`). Is that a requirement or can we accept that loss?
I can provide the patch if this gets accepted.

**Comment by unho** [comment]
According to my read of https://github.com/translate/translate/blob/d14072eac9f07f97ee9376b1cb4bd853ddeea0a9/docs/formats/ini.rst#conformance keeping the layout is the standard toolkit way. Perhaps we can look for some `iniparse` replacement that keeps current functionality while we support both Python 2 and Python 3.

**Comment by claudep** [comment]
@bkabrda I saw that you ported iniparse to Python 3 and that your patch was integrated in Fedora and Debian packages, for example. Do you maintain a fork of iniparse somewhere? Seems upstream dev is stalled.

**Comment by bkabrda** [comment]
Hi, I don't maintain an iniparse fork. It does seem that upstream dev is stalled.

I currently don't have any spare time to maintain a fork, plus I personally don't use iniparse any more. I usually choose configobj [1] when I need to manipulate ini files - would that work for you?

[1] http://configobj.readthedocs.org/en/latest/

**Comment by claudep** [comment]
Thanks for the pointer, nice. For what I've seen, configobj also hardcodes a space around each side of the equal sign. I personally wouldn't care about this, as spaces around '=' are not significant, but that's a decision left to core TTK developers.

**Comment by dwaynebailey** [comment]
@claudep generally in ttk we want to not introduce non-l10n changes when we're working with the files. So we want to match the source en-US format that we're usually using as reference.  We need to either:

1. Soften that requirement.
2. Change upstream to support that.

I'm thinking for foreign not primarily l10n formats we should maybe take a position like 1).

**Comment by nijel** [comment]
Closing this as iniparse is now working on Python 3.
