### ISSUE TITLE
csvunit.context is not properly populated

### ISSUE THREAD

**Issue by JohnnyKing94** [translate/translate#3356]
I open this ticket-issue from a [**quote**](https://github.com/translate/pootle/issues/4097#issuecomment-142665602) of @unho:

"_My guess is that `csvunit.context` is not properly populated when the CSV file is parsed, and thus https://github.com/translate/translate/blob/master/translate/storage/csvl10n.py#L135-L144 doesn't return different values. So the fix should be on Translate Toolkit, since Pootle relies on it for knowing if a unit has duplicates or not: https://github.com/translate/pootle/blob/b0439ae3/pootle/apps/pootle_store/models.py#L1569-L1573_".

Thx in advance
FULL LINK: https://github.com/translate/pootle/issues/4097

**Comment by claudep** [comment]
Could you tell us your Translate Toolkit version, please?

**Comment by unho** [comment]
Merged a test to expose the issue: fdbe7128

**Comment by JohnnyKing94** [comment]
Here you are
```
root@server:~# pip freeze | grep translate
translate-toolkit==1.13.0
```

**Comment by unho** [comment]
Noticed that the test I merged was wrong, so just landed a fix.

**Comment by JohnnyKing94** [comment]
Anything new about the csv problem? I don't want to rush, but i need to know if it will be a long road to fix it or not? if it yes, i will try to change with other formats and i won't wait anymore

**Comment by unho** [comment]
@JohnnyKing94 This might be fixed early, but most likely the release of a newer TTK package won't be soon.

**Comment by JohnnyKing94** [comment]
Buf it gets fixed soon, i can use the git version of Translate, right?? Pootle will work with a newever version?

**Comment by unho** [comment]
It should work fine.

**Comment by JohnnyKing94** [comment]
Ok then i'll be waiting for a solution with the csvunit...

**Comment by JohnnyKing94** [comment]
Has been found any tricks, any workarounds? I know you're busy and probably you won't find solution for now, but even if you tell me something, that would be perfect... cause i need to publish my translate website and the csv format is the most manageable format for me to use on it...

**Comment by unho** [comment]
@JohnnyKing94 Sorry for the delay. We didn't provide a fix for this yet, and we don't have any plans for any close release. Our apologies for not being really helpful. Our main reasons to postpone this is that the fix and the release will consume time that we find more useful to be spent on other developing tasks.

Anyway I advise you against using CSV for translating. Have you tried proper translation formats, for example XLIFF?

**Comment by JohnnyKing94** [comment]
I can't... one of my friends, created a software to convert a large txt file into csv. Apparently i can't use any of the existing utilities on the web, not even yours (eg txt2po) since the program stops working for its enormity... i've a 36Mb file with 749292 strings... it's a localization file of a game... so basically my friend helped me to create an easy utility to create a csv from three txt files (an ID file, a Source file and the target file)... it does trick in a minute with a specific amount of cpu usage, and at the end it completes the job despite other programs on the web... so changing format, it means creating a new program, unless you know other utilites that they do this kind of large conversion.

**Comment by phlax** [comment]
hi @JohnnyKing94 - is the issue that it uses to much system memory?

Im trying to spec a ttk2 at the moment and had not thought too much about large file handling - so it would be good to know what the limitations of ttk are

**Comment by JohnnyKing94** [comment]
The txt2po (like csv2po) utility just stops working, i don't have a huge load of system memory... just when you run it, it's already crashed... it does nothing, not even consuming... tried with several tools, so i decided to create our own tool using our own knowledge :) ... now we're deciding to make a csv/txt to xliff tool... but atm we didn't decide yet... we keep hoping it would be a csv fix in a not distant future :)

Anyway if you want the original file for testing... like conversion on proper formats, i would be happy to give it to you :)

**Comment by JohnnyKing94** [comment]
Never mind, we built another tool for xliff format... we're gonna try how the server is goona react with all these strings after it completed the upload (about 10/15K of strings each minute with "pootle update_stores" command, i feel satisfied for the moment) :D I'll keep you posted... for the moment no ERROR returns for double IDs or stuff like that
