### ISSUE TITLE
po2php outputs empty files

### ISSUE THREAD

**Issue by 00svbeon** [translate/translate#3372]
On Debian GNU/Linux 2.6.32-042stab111.12
po2php version: 1.13.0-rc1
Running `po2php --progress=names -x en.po -S -t en.php po/ ./` returns a list of po files as output, as expected:
```
sv.po
fr.po
```

As expected
But the output php files all got the following content:
```
```

That's right, nothing. Expected output,  something like:

```php
<?php
$loc['lang']='sv';
$loc['paypal lang']='se';
$loc['ca']='Katalanska';
$loc['cs']='Tjekiska';
$loc['de']='Tyska';
```
(sv.php)

po files where generated with `php2po --progress=names -S --exclude=*-*.php -t en.php ./ po/` and the output po files of that command looks something like this:

```po
#. extracted from en.php, ./en.php
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2016-01-17 17:52+0200\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Generator: Translate Toolkit 1.13.0-rc1\n"

#: $loc['lang']
msgid "en"
msgstr "en"

#: %24loc%5B%27paypal+lang%27%5D
msgid "us"
msgstr "us"

#: $loc['ca']
msgid "Catalan"
msgstr "Catalan"
```
(en.po)
etc. (note adding `--fuzzy` to the po2php command makes no difference)

**Comment by unho** [comment]
Try running `po2php --progress=names -x en.po -S -t en.php -i po/ -o ./` If it still fails, can you please share your files for us to test?

**Comment by 00svbeon** [comment]
It worked, I made a quick hack to update en as well
```
cp en.php en2.php
po2php --progress=names -S -t en2.php -i po/en.po -o ./en.php
rm -rf en2.php
```

Thanks

**Comment by 00svbeon** [comment]
(and added --fuzzy)

**Comment by unho** [comment]
Great. Closing this.
