### ISSUE TITLE
po2rc: UnicodeWarning: Unicode unequal comparison failed to convert both arguments to Unicode - interpreting them as being unequal

### ISSUE THREAD

**Issue by TitaneBoy** [translate/translate#3373]
For translate-toolkit-1.13.0:

Hi. It looks that `po2rc` is not working well. Using `rc2po` to create `.pot` file then using it with `pot2po` to create `.po` file works wery well. The original `rc` file used to do my test is within translate-toolkit package and it is named `one.rc` (`tests/cli/data/test_rc2po/one.rc`). The charset of the `one.rc` file is `UTF-8`

This is the list of command I used to do my test:
- `rc2po -P --charset=utf8 -i one.rc -o one.rc.pot`
- `pot2po -i one.rc.pot -o one.rc.po`
- Edited `one.rc.po` with PoEdit
- `po2rc -t one.rc -i one.rc.po -o oneFrench.rc -l LANG_FRENCH --errorlevel=traceback`

And this is what I get after using `po2rc`:

``` pytb
C:\Python27\lib\site-packages\translate_toolkit-1.13.0-py2.7.egg\translate\convert\po2rc.py:70: UnicodeWarning: Unicode unequal comparison failed to convert
both arguments to Unicode - interpreting them as being unequal
  if self.inputdict[location] != unit.match.groupdict()['value']:
WARNING:po2rc:Error processing: input one.rc.po, output oneFrench.rc, template one.rc: Traceback (most recent call last):

  File "C:\Python27\lib\site-packages\translate_toolkit-1.13.0-py2.7.egg\translate\misc\optrecurse.py", line 514, in recursiveprocess
    fulltemplatepath)

  File "C:\Python27\lib\site-packages\translate_toolkit-1.13.0-py2.7.egg\translate\convert\convert.py", line 179, in processfile
    fulltemplatepath)

  File "C:\Python27\lib\site-packages\translate_toolkit-1.13.0-py2.7.egg\translate\misc\optrecurse.py", line 572, in processfile
    **passthroughoptions):

  File "C:\Python27\lib\site-packages\translate_toolkit-1.13.0-py2.7.egg\translate\convert\po2rc.py", line 93, in convertrc
    outputrclines = convertor.convertstore(inputstore, includefuzzy)

  File "C:\Python27\lib\site-packages\translate_toolkit-1.13.0-py2.7.egg\translate\convert\po2rc.py", line 45, in convertstore
    outputblocks.append(self.convertblock(block))

  File "C:\Python27\lib\site-packages\translate_toolkit-1.13.0-py2.7.egg\translate\convert\po2rc.py", line 72, in convertblock
    self.inputdict[location])

UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 6: ordinal not in range(128)

[###########################################] 100% 
```

I have tried many solutions to solve it but cannot find it at all. Can you please fix this issue ?

Thank you very much.

**Comment by unho** [comment]
Tested and this happens when the translated PO file contains non ASCII characters, like "Français".

@TitaneBoy Thanks for reporting. Sadly this format is not largely used and probably we won't fix this issue soon.

**Comment by SantosSi** [comment]
Well, Windows applications are more and more becoming open source, so does a Windows clone: [ReactOS](https://reactos.org/wiki/Translation_Introduction). Since the [weblate translation software](https://hosted.weblate.org) relies in rc2po, this would be a good opportunity to review these issues?
