### ISSUE TITLE
Add Fluent support to Translate Toolkit

### ISSUE THREAD

**Issue by phlax** [translate/translate#3389]
Quoting @dwaynebailey : 

> We have some WIP l20n support for l20n2po in ttk. We need to complete this and make sure it works for the minimal use case which is plurals and some other minor pieces.

Refs:

https://github.com/translate/translate/issues/2177

https://github.com/translate/translate/compare/master...dwaynebailey:l20n-db

**Comment by unho** [comment]
More on the format: http://l20n.org/

**Comment by nijel** [comment]
Maybe it could be based on https://github.com/projectfluent/python-fluent now...
