### ISSUE TITLE
Skip newlines when parsing DTD

### ISSUE THREAD

**Issue by unho** [translate/translate#3390]
Real newlines don't usually (or never) matter, thus raising lots of false positives for newlines check. The best way to avoid this is not to parse the real newlines. Thus the following entity (https://github.com/translate/mozilla-l10n/blob/master/templates-en-US/calendar/chrome/calendar/preferences/categories.dtd#L22):

```
<!ENTITY pref.categories.overwrite "A category already exists with that name. \n Do you want to overwrite it?">
```

will be parsed as a single line string, where `\n` will be escaped as `\\n` in the parsed string.

The following one will be a single line string too (https://github.com/translate/mozilla-l10n/blob/master/templates-en-US/browser/chrome/browser/aboutCertError.dtd#L24-L27):

```
<!ENTITY certerror.whatShouldIDo.badStsCertExplanation "This site uses HTTP
Strict Transport Security (HSTS) to specify that &brandShortName; only connect
to it securely. As a result, it is not possible to add an exception for this
certificate.">
``` 

but no `\n` nor `\\n` will be present in the parsed string.

Real examples for both:

- https://mozilla.locamotion.org/eu/lightning/translate/calendar/chrome/calendar/preferences/categories.dtd.po#unit=6519837
- https://mozilla.locamotion.org/eu/firefox/translate/browser/chrome/browser/aboutCertError.dtd.po#unit=8703314

**Comment by dwaynebailey** [comment]
I've noticed that there are some units that are using linebreaks to ease translation.

E.g.

```
<ul>
   <li>One
   <li>Two
</ul>
```

We lose that when we strip `\n`.

I was wondering if/how we could detect that?  Otherwise we need another strategy then global removal.
