### ISSUE TITLE
json2po output strings in wrong order

### ISSUE THREAD

**Issue by huftis** [translate/translate#3394]
Running `json2po` outputs a valid PO files, but the strings are in the wrong order. I’m not sure exactly *which* order it is, but is *neither* the original order, the reverse order or alphabetically. Here’s an example JSON file:

```json
    {
        "foo": "foo",
        "bar": "bar",
        "baz": "baz"
    }
```

Running `json2po` on this file results in the following (with a PO file header):

```po
    #: .baz
    msgid "baz"
    msgstr ""
    
    #: .foo
    msgid "foo"
    msgstr ""
    
    #: .bar
    msgid "bar"
    msgstr ""
```

Having the strings in a different order than in the original file makes it much harder to correctly translate the file, as one loses context.

I observe this bug both in version 1.13.0 and 1.14.0-rc1.

**Comment by dwaynebailey** [comment]
I think this might be quite hard to fix, reasons follow.

There is no real ordering in JSON, it's just a data structure.  From the Python side its just a dictionary, which has no order.  We rely on a JSON parser to help us here and to most programmers the ordering isn't important at all.  The parser might expose some way for us to get such ordering, things like [OrderedDict](https://docs.python.org/2/library/collections.html#collections.OrderedDict) do exist in Python.

From a translator's perspective the change in ordering is really problematic.  But writing our own parse is really not an option.  Note to programmers, use proper localisation formats, JSON isn't one of those.

**Comment by dwaynebailey** [comment]
@dwaynebailey decides to experiment a bit to confirm things.

**Comment by dwaynebailey** [comment]
Ouch, that was an embarrassingly easy fix.

Thanks @huftis for spotting this.  And thanks for a really nice simple example that replicates the issue, that saved me a lot of time.

Would appreciate if you could confirm the PR I'll post in a bit.

**Comment by dwaynebailey** [comment]
Getting the tests to pass though was not as easy.  This will only work in Python >= 2.7

**Comment by huftis** [comment]
Thank you! I can confirm that the fix works fine. (`po2json` has a similar issue, but I see that that’s already mentioned in the TODO list in the source code (`jsonl10n.py`).)

**Comment by dwaynebailey** [comment]
@huftis back conversion has landed, if you'd care to check.
