### ISSUE TITLE
Drop Python 2.6 support in ttk

### ISSUE THREAD

**Issue by dwaynebailey** [translate/translate#3401]
We should drop Python 2.6 support because of the maintenance burden.  The reasons and options available to users is [clearly outlined in this](http://www.snarky.ca/stop-using-python-2-6) and similar articles.

Summary would be:

1. There are alternate options for people to get at least Python 2.7 on older platforms like RHEL.
2. It's a massive burden to support Python 2.6 at no cost to the user but at great expense to the ttk devs. Especially considering point 1.

As a note to point 2. Landing the json2po changes to maintain ordering was a 10min fix.  Coping with making it run on Python 2.6 lead to new dependencies, try except blocks and fallbacks to non-optimal behaviour for Python 2.6.  And that took half a day to develop.

So my motivation, so that we can focus on localisation, is to drop a very very very old release which we're maintaining for a teeny tiny user base (if they exist at all) who already have a many many many options to get Python 2.7 which we do support.

**Comment by claudep** [comment]
+1

After 1.14, I guess?

**Comment by unho** [comment]
I agree, but if we do it, lets do it for 1.14.

I am anticipating @friedelwolff pushback, something that already happened when dropping support for Python 2.5. But users that want to keep using 2.6 already have basically all the old Translate Toolkit releases.
