### ISSUE TITLE
Backwards incompatible change in multistring

### ISSUE THREAD

**Issue by julen** [translate/translate#3404]
The behavior of the `multistring` class with respect to string comparisons has changed in 1.14-rc1, more specifically when the `autoencode` class was removed in 4f9ee7edfc9. At least this is the case in Python 2.7.

I have experienced this in some custom Pootle code when testing out TTK from master — a multistring with non-ASCII characters was being compared against the empty byte string `''`, and it resulted in a encoding error. I can reproduce this in a test case:

```python
from translate.misc import multistring

def test_cmp():
    t = multistring.multistring
    s1 = t("test")
    assert s1.__cmp__("test") == 0

    s2 = t(u"téßt")
    assert s2.__cmp__("test") > 0
```
(Note that for 1.13.x the multistring constructor needs an `encoding='UTF-8'` parameter in the test).

I'm not sure if this could be considered a bug, after all my understanding is apps/libraries should internally work with code points and not bytes, however this is a breaking change that might potentially affect existing consumer code so I consider it's worth bringing this up to hear people's thoughts.

**Comment by unho** [comment]
@claudep Can you provide some additional insight?

**Comment by claudep** [comment]
Julen, could you check if the patch is solving the issue for you?

**Comment by julen** [comment]
Thank you for taking quick action on this, @claudep! I tested the PR against the failing code I had and now it works beautifully.
