### ISSUE TITLE
php2po extra lines and quotes

### ISSUE THREAD

**Issue by beachmat** [translate/translate#3407]
I'm wondering if there's a reason why php2po breaks up paragraphs into extra lines enclosed by quote marks? For example with this in the php
`  'first_bit'												=>	'Some said it was a move to shield him from prosecution while others welcomed his return to active politics.',`
you get this in the pot:
`"Some said it was a move to shield him from prosecution while others welcomed "
"his return to active politics."`
There is a line break after welcomed ". Obviously it gets removed on return, but it seems to be causing segmentation problems in my translation software.

**Comment by claudep** [comment]
This line break thing is not directly caused by translate, but that's a known behavior of gettext's msgmerge, which can be disabled with the `--no-wrap` option, but this should absolutely not break your translation software as this formatting is found in many po files in the wild.
