### ISSUE TITLE
Using po2sub / po2sub errors out with No module named gaupol.subtitle

### ISSUE THREAD

**Issue by pmkovar** [translate/translate#3409]
po2sub / po2sub on Fedora 19+ (I think) errors out with No module named gaupol.subtitle. This used to work on F18, didn't work on Arch Linux either.

Tried po2sub -t gnome320.srt po/cs.po gnome320.cs.srt with https://git.gnome.org/browse/video-subtitles/tree/video-subtitles/gnome320/gnome320.srt

```
$ po2sub -t gnome320.srt po/cs.po gnome320.cs.srt
processing 1 files...

po2sub: warning: Error processing: input po/cs.po, output gnome320.cs.srt, template gnome320.srt: No module named gaupol.subtitle
[###########################################] 100%
```

**Comment by dwaynebailey** [comment]
@pmkovar do you actually have the dependencies installed?  The code tries aedion, then falls back to gaupol.

I'd be curious to know how you installed this to try figure out why you don't have the dependencies.

That said we should probably fail if we can't find the needed libraries.

**Comment by pmkovar** [comment]
@dwaynebailey I just installed the latest rpm package for F23. Is there a list of dependencies somewhere that I could check?

The list of requirements for the Fedora package starts here:

http://pkgs.fedoraproject.org/cgit/rpms/translate-toolkit.git/tree/translate-toolkit.spec#n16

Is it missing something? I couldn't find a package called aedion and gaupol is a GUI subtitle editor in Fedora. Is that a dependency? 

Thanks!

**Comment by dwaynebailey** [comment]
@pmkovar thanks that helps.  I used to package the Fedora rpm, haven't for a while.

Just checking 0.11.0 has the needed guards for Gaupol and Aedion http://pkgs.fedoraproject.org/cgit/rpms/translate-toolkit.git/tree/translate-toolkit.spec#n36

This line in the spec http://pkgs.fedoraproject.org/cgit/rpms/translate-toolkit.git/tree/translate-toolkit.spec#n36 is asking for the aeidon package (sorry I misplelled I think)

This package https://www.rpmfind.net/linux/RPM/fedora/23/i386/a/aeidon-0.25-4.fc23.noarch.html should be what you need.

This reminds me I think post 23 there is an issue that aeidon is only available on Python 3 (saying this without double checking)

So I'd check why when you installed you didn't get the aeidon package installed.  Check the logs.

**Comment by pmkovar** [comment]
@dwaynebailey I'm on F23 and the aeidon package is pulled in as a dependency by dnf. I just reinstalled translate-toolkit-1.9.0-5.fc20.noarch which also installed aeidon-0.25-4.fc23.noarch and am still seeing the same issue.

Thanks.

**Comment by afranke** [comment]
I am on F24 here. I tried with translate-toolkit from the Fedora repository (1.9.0), same issue as @pmkovar. Then I tried with translate-toolkit from git master, it works. @dwaynebailey, could you maybe update the Fedora package?

**Comment by lynxlynxlynx** [comment]
It's the same on (K)ubuntu 16.04, where it doesn't change after installing the gaupol package. aiedon is packaged, but only for python3, so you have to do it manually.

**Comment by afranke** [comment]
That is expected as 16.04 has version 1.13.

**Comment by juhp** [comment]
I have been updating the fedora package... but I am not a user

**Comment by juhp** [comment]
Yes aeidon seems python3 only and for F25 I am still building for python2.
F26 has python3 translate-toolkit so that probably works.

**Comment by dwaynebailey** [comment]
I've added some code that at least reports more clearly when required aeidon or gaupol packages are unavailable. @pmkovar @afranke @lynxlynxlynx @juhp just a heads up if you want to test.

It essentially tries to import aeidon then gaupol and then fails with a useful message which considers if you are PY3 or PY2

**Comment by pmkovar** [comment]
@dwaynebailey Thanks! I've recently filed https://bugzilla.redhat.com/show_bug.cgi?id=1449724 to track the Fedora package issue with sub2po. Jens suggests it's related to PY2/PY3.
