### ISSUE TITLE
No Windows version

### ISSUE THREAD

**Issue by Peremptor** [translate/translate#3410]
Were you just lying on your website, is the website no longer up to date or have you lost your last Windows programmer?
I'm very sorry I have to use such a stupid operating system but it has to function in many ways for university, ways that Linux just can't provide.
So, write on your "home"-page which operating systems you cover. I'm really tired to look for hours and hours for some little problems of mine to be solved (just because I'm no child of Bill Gates, sorry).

**Comment by dwaynebailey** [comment]
@Peremptor try this https://sourceforge.net/projects/translate/files/Virtaal/0.7.1/

We're an open source project.  I'll happily accept the offer you've just made to help us package on Windows and to make changes on our website to help others like you find the right software.  Welcome aboard.  That's a bit tongue in cheek, but seriously there are other people on Windows for whatever reason and we'd like to serve them.  But our resources are limited.  Unless this was also an offer to pay for packaging a Windows version for you? :)

**Comment by dwaynebailey** [comment]
@Peremptor whoops wrong app, same reasoning though.  The last Windows build is here https://sourceforge.net/projects/translate/files/Translate%20Toolkit/1.9.0/

Making Windows builds mostly needs someone who has a machine to make them.  None of our devs have at the moment.  So roll out your Windows machine and Python skills and give us a hand.

**Comment by Peremptor** [comment]
When I'm finished with studying I will have time to learn a complete 
programming language (next to the English one). Until then I'm not much 
more than a stupid user, because a Python is just a snake for me. (There 
are really too many programming languages out there, I only understand a 
bit of Visual Basic).
But you are telling people on your website, that there IS a Win version. 
You have to understand whoever is looking for it is disappointed. That's 
like offering a bit of chocolate to a kid and then draw it away.

And you are not the only one working for free. I'm repairing computers 
for everyone who asks, I helped the neighbour's child for about two 
years with school things, my cellar is full of "thanks". That's why I 
can't support myself, my parents have to pay the health insurance, I'm 
living with a friend near the university, I'm working every free minute 
and nevertheless there isn't enough money to live with. Any further 
questions?

Am 24.03.2016 um 00:22 schrieb Dwayne Bailey:

**Comment by dwaynebailey** [comment]
Closing in favour of https://github.com/translate/translate/issues/3162
