### ISSUE TITLE
po2html incorrect sub-strings substitution

### ISSUE THREAD

**Issue by s-n-g** [translate/translate#3416]
This is the situation at hand:

I have two messages

msgid "This is me <b>**Writing in English**</b>"
msgid "**Writing in English**"

Both messages are translated, but po2html result is (within the html file):

This is me (**<b>Translation of "Writing in English**"</b>)
and
(**Translation of "Writing in English**")

As I understand it, there is a sub-string substitution going on for the first message (when it shouldn't).
I have tried to overcome by sorting the po file by message length so that the first message would be substituted first, but no luck...

**Comment by dwaynebailey** [comment]
@s-n-g yes I'm pretty sure what you've observed is correct, we do string substitution.  What would really help is if you could supply a really small test case of the PO and HTML files to replicate the issue.

**Comment by s-n-g** [comment]
Sure, here you are:  [issue3416.zip](https://github.com/translate/translate/files/196399/issue3416.zip)

Commands executed:
`html2po -P html pot`
`mkdir po`
`cp pot/* po`

And after translating **index.po**:
`po2html -t html po elhtml`
