### ISSUE TITLE
Multistring doesnt work as a python2 string

### ISSUE THREAD

**Issue by phlax** [translate/translate#3428]
Previously you were able to so ~~`str(multistring("foo"))`~~ but it seems this no longer works.

EDIT: apologies that was a bad example it should have read something like `str(multistring("é"))`

Im wondering if we should add py2 compat similar to the one in django (https://docs.djangoproject.com/en/1.9/_modules/django/utils/six/#python_2_unicode_compatible)

@claudep any thoughts on this?

**Comment by claudep** [comment]
Could you be a little more specific about what doesn't work? Maybe a traceback?

**Comment by phlax** [comment]
hi - yep, apologies.

by doesnt work i mean it triggers UnicodeEncodeErrors, here is an example

```
(Pdb) suggestion.target
multistring([L'équipe FrenchMozilla])
(Pdb) str(suggestion.target)
*** UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 2: ordinal not in range(128)

```
it can be resolved by adding a __str__ method that returns something like this, where necessary
```
(Pdb) "".join(suggestion.target.strings).encode("utf8")
"L'\xc3\xa9quipe FrenchMozilla-pain"
```

**Comment by claudep** [comment]
Just added a proposal to fix that regression. When testing the old behavior, I think only the first string was output by `str()`, no join occurred. I don't know enough history of the module and its usage to know if multiple strings were supposed to be joined or not.

**Comment by phlax** [comment]
@claudep nice one! thanks for the quick resolution
