### ISSUE TITLE
pip install --pre translate-toolkit can't find guide

### ISSUE THREAD

**Issue by bialix** [translate/translate#3432]
It seems translate toolkit was installed in the end, but during execution of pip install I got

```
  creating build\bdist.win-amd64\wheel\translate_toolkit-1.14.0rc1.data\data\Lib\site-packages\translate\docs\_build\html\_sources\guides
  copying docs\_build\html\_sources\guides\checking_for_inconsistencies.txt -> build\bdist.win-amd64\wheel\translate_toolkit-1.14.0rc1.data\data\Lib\site-packages\translate\docs\_build\html\_sources\guides
  copying docs\_build\html\_sources\guides\cleanup_translator_comments.txt -> build\bdist.win-amd64\wheel\translate_toolkit-1.14.0rc1.data\data\Lib\site-packages\translate\docs\_build\html\_sources\guides
  copying docs\_build\html\_sources\guides\creating_a_terminology_list_from_your_existing_translations.txt -> build\bdist.win-amd64\wheel\translate_toolkit-1.14.0rc1.data\data\Lib\site-packages\translate\docs\_build\html\_sources\guides
  error: could not create 'build\bdist.win-amd64\wheel\translate_toolkit-1.14.0rc1.data\data\Lib\site-packages\translate\docs\_build\html\_sources\guides\creating_a_terminology_list_from_your_existing_translations.txt': No such file or directory

  ----------------------------------------
  Failed building wheel for translate-toolkit
```

I've downloaded your 1.14.0-rc1 tarball from PyPI and there is no such file indeed, with extension txt, but there is file with extension rst. I guess you have some setup.py files list mismatch.

**Comment by dwaynebailey** [comment]
@bialix that file is in the tarball, just checked:

```
~/dev/toolkit/tmp/translate-toolkit-1.14.0-rc1 (master)$ ls -l docs/_build/html/_sources/guides/creating_a_terminology_list_from_your_existing_translations.txt 
-rw-r--r--  1 dwayne  staff  7489  7 Mar 15:18 docs/_build/html/_sources/guides/creating_a_terminology_list_from_your_existing_translations.txt
```

We simply graft the whole `doc` directory into the package.

The file is present so something else must be causing the issue.  The fact that the two line directly before succeed, and they're doing the same thing, and that the file does exist in the tarball indicates another issue.

I don't get any such error on a Mac, and I assume Linux would be the same.  From the paths, I'm assuming this is on Windows.

Can you give us some information about your setup and steps to replicate this.

Also could you check `tar tvjf` to get a listing of files in the tarball to see if it is there. And do `tar xvjf` to see if the file is actually extracted.  I just guessing but wonder if the long filename has perhaps caused some unexpected issue.

**Comment by bialix** [comment]
Yes, I'm on Windows.
Giving in mind that path `"docs/_build/html/_sources/guides/creating_a_terminology_list_from_your_existing_translations.txt"` is 96 characters long, I think it's possible that pip install hit Windows max path limitiation, which is 260 characters.

```
In [7]: len("build\bdist.win-amd64\wheel\translate_toolkit-1.14.0rc1.data\data\Lib\site-packages\translate\docs\_build\html\_sources\guides")
Out[7]: 123
```

96+123 = 219, plus path to my temp directory 34 characters, plus pip created some prefix, I guess. It's easy to hit 260 limit, I think.

Maybe if I change my TEMP directory to shortest possible path, it would work. I don't really know whether it will be classified as real bug. Because only possible solution to fix it - is to shorten your file names. I can live without docs.

**Comment by unho** [comment]
Tried to unsuccessfully replicate this using Windows 7. Perhaps you can share more details on what you are exactly doing when you hit this issue. Does it also happen with latest release?

**Comment by bialix** [comment]
Sorry, I don't think I will ever have a time to work on this anytime soon.
