### ISSUE TITLE
multistring needs a __hash__ method

### ISSUE THREAD

**Issue by phlax** [translate/translate#3434]
In old ttk you could do something like

```python
foo = multistring("foo")
foodict = {foo: "bar"}
assert 'foo' in foodict
```
It seems this no longer works - not sure why, but a `__hash__` method that returns `hash(str(self))` should fix the problem i believe

@claudep @julen any thoughts on this?

**Comment by julen** [comment]
FWIW `multistring` already [has as `__hash__` method](https://github.com/translate/translate/blob/208074431728d87c17e53b6359cd87616d64bc9a/translate/misc/multistring.py#L84-L85).

Also, I don't see any differences across versions with the snippet you provided:
```python
In [1]: from translate import __version__
In [2]: __version__.sver
Out[2]: '1.13.0'
In [3]: from translate.misc.multistring import multistring
In [4]: foo = multistring('foo')
In [5]: foodict = { foo: 'bar' }
In [6]: assert 'foo' in foodict
```

```python
In [1]: from translate import __version__
In [2]: __version__.sver
Out[2]: '1.14.0-rc1'
In [3]: from translate.misc.multistring import multistring
In [4]: foo = multistring('foo')
In [5]: foodict = { foo: 'bar' }
In [6]: assert 'foo' in foodict
```

**Comment by phlax** [comment]
@julen i think i may have got this the wrong way round it shoud read

```
foo = multistring("foo")
foodict = {"foo": "bar"}
assert foo in foodict
```

**Comment by julen** [comment]
WFM.

**Comment by phlax** [comment]
> WFM

not sure if you mean code or test @julen 

ive added a PR to demonstrate the problem and fix it

**Comment by phlax** [comment]
for ref here is the test failing https://travis-ci.org/phlax/translate/jobs/125898982#L1126
