### ISSUE TITLE
poparser wrongly parses first unit source

### ISSUE THREAD

**Issue by nijel** [translate/translate#3450]
When msgid of first unit of po file is unicode, it's wrongly parsed (it's decoded using iso-8859-1 instead of charset specified in the header).

File which shows this behavior: [Author_Group.po.txt](https://github.com/translate/translate/files/322881/Author_Group.po.txt)

Testcase patch to see the problem: [test_po.patch.txt](https://github.com/translate/translate/files/322885/test_po.patch.txt)

**Comment by nijel** [comment]
There is PR for this: https://github.com/translate/translate/pull/3455

**Comment by dwaynebailey** [comment]
Fixed in https://github.com/translate/translate/pull/3455
