### ISSUE TITLE
csv2po urlencoded forward slashed in case of multiple string locations without -t

### ISSUE THREAD

**Issue by sargac** [translate/translate#3457]
I am using Poedit to manage .po files

The issue happens when converting some PO file to CSV, and then back to PO following the tutorial at http://docs.translatehouse.org/projects/translate-toolkit/en/latest/guides/using_csv2po.html

Converting "po2csv" goes well, but at the "csv2po" conversion I got .po file with originally separated locations (1) merged into one line and (2) with url-encoded forward slashes. So instead of a path "some/path/to" I got "some%2Fpath%2Fto".

The issue seems to occur only at multiple locations, and not at single location paths, as you can see from example below.

### Part from output (.po) file, generated from CSV

1st string with single location is correctly displayed
2nd string with multiple location paths is wrong (urlencoded and merged into 1 line, I guess)

--

#: path/to/File.php:55
msgid "Enter string."
msgstr "Vpišite znak."

#: 
path%2Fto%2FFile.php%3A59+path%2Fto%2FFile2.php%3A22+path%2Fto%2FFile2.php%3A188+path%2Fto%2FFile3.php%3A301
msgid "Invalid string."
msgstr ""
"Nepravilen znak. Preverite da v znaku ni presledkov in ostalih "
"nedovoljenih znakov in poskusite ponovno."

--

### Same part from original (.po) file for comparison:

--

#: acc/controllers/Auth.php:55
msgid "Enter string."
msgstr "Vpišite string."

#: path/to/File.php:59 path/to/File2.php:22
#: path/to/File2.php:188 path/to/File3.php:301
msgid "Invalid email."
msgstr ""
"Nepravilen znak. Preverite da v znaku ni presledkov in ostalih "
"nedovoljenih znakov in poskusite ponovno."

--

**Comment by dwaynebailey** [comment]
The workaround this issue is quite simple.  If you use the target PO files as a template it will work correctly thus:

```
csv2po -t my.po my.csv my.po
```

I'm not sure that we can completely fix this.  CSV gives a single location that will include spaces.  PO doesn't accept a single location with spaces so we urlencode the spaces away, and I suspect forward slash gets the same encoding treatment.

We might want to look more closely at this.  But with the workaround I don't thinks its critical

**Comment by sargac** [comment]
Thanks Dwayne, it solves the issue perfectly, so I'm closing the issue!
