### ISSUE TITLE
po2php not working with PHP "define()" syntax

### ISSUE THREAD

**Issue by bobhairgrove** [translate/translate#3462]
I cannot get any translation to work with PHP "define(...)" syntax, whether with or without spaces.

Here is the PHP template file "script_EN.php":

``` php
<?php
define("SBBL_ERROR_PAGE_TITLE", "SBBL &mdash; Error");
define("SBBL_ERROR_PAGE_REDIRECT_MSG", "In %d seconds you will be redirected to the %s page.");
define("SBBL_ERROR_PAGE_REDIRECT_MAIN", "main");
define("SBBL_ERROR_PAGE_REDIRECT_LOGIN", "login");
define("SBBL_ERROR_PAGE_HEADER", "An error has occurred in the SBBL application:");
?>
```

I run this command to produce a POT translation template file:
`php2po -P script_EN.php -o script_EN.pot`

So far, so good. I translate the strings in the POT file and save it as "script_DE.po":

``` po
#. extracted from script_EN.php
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2016-07-07 00:23+0200\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Generator: Translate Toolkit 2.0.0b2\n"

#: define("SBBL_ERROR_PAGE_TITLE"
msgid "SBBL &mdash; Error"
msgstr "SBBL &mdash; Fehlermeldung"

#: define("SBBL_ERROR_PAGE_REDIRECT_MSG"
msgid "In %d seconds you will be redirected to the %s page."
msgstr "In %d Sekunden werden Sie zur %s umgeleitet."

#: define("SBBL_ERROR_PAGE_REDIRECT_MAIN"
msgid "main"
msgstr "Hauptseite"

#: define("SBBL_ERROR_PAGE_REDIRECT_LOGIN"
msgid "login"
msgstr "Login-Seite"

#: define("SBBL_ERROR_PAGE_HEADER"
msgid "An error has occurred in the SBBL application:"
msgstr "Ein Fehler ist in der SBBL-Anwendung aufgetreten:"
```

Next, I run this command to produce the PHP file (in German, supposedly):
`po2php --progress=verbose -t script_EN.php -i script_DE.po -o script_DE.php`

A file is created, but it is an exact copy of the English original. :( As you can see, the only spaces outside of the message strings are those in the PHP "define()" commands, one after the comma separating the constant from the value.

**Comment by dwaynebailey** [comment]
Doing a quick experiment it seems that we can safely extract `define` entries but we can't recombine them to rebuild the translated PHP file.

**Comment by bobhairgrove** [comment]
Thanks for reformatting my message, Dwayne ... I still have to learn Markdown. :) Much nicer now.

**Comment by bobhairgrove** [comment]
Here are three files for a somewhat simpler test run:
[test_po2php.zip](https://github.com/translate/translate/files/351923/test_po2php.zip)

**Comment by bobhairgrove** [comment]
In the meantime, I had a look at the sources in `po2php.py`. My Python is a little rusty, but if you look at lines 101-125 in the function `convertline` , it appears that the code is trying to parse a PHP define() command:

```
            # otherwise, this is a definition
            else:
                # now deal with the current string...
                key = line[:equalspos].rstrip()
                lookupkey = self.prename + key.lstrip()
                # Calculate space around the equal sign
                prespace = line[len(line[:equalspos].rstrip()):equalspos]
                postspacestart = len(line[equalspos+len(self.equaldel):])
                postspaceend = len(line[equalspos+len(self.equaldel):].lstrip())
                postspace = line[equalspos+len(self.equaldel):equalspos+(postspacestart-postspaceend)+len(self.equaldel)]
                self.quotechar = line[equalspos+(postspacestart-postspaceend)+len(self.equaldel)]
                inlinecomment_pos = line.rfind("%s%s" % (self.quotechar,
                                                         self.enddel))
                if inlinecomment_pos > -1:
                    inlinecomment = line[inlinecomment_pos+2:]
                else:
                    inlinecomment = ""

                if lookupkey in self.inputstore.locationindex:
                    unit = self.inputstore.locationindex[lookupkey]
                    if ((unit.isfuzzy() and not self.includefuzzy) or
                        len(unit.target) == 0):
                        value = unit.source
                    else:
                        value = unit.target
```
It uses the variables `equalspos` and `equaldel` which were set further up in the code. However, equalsdel is apparently set to the sequence `=>` (line 81) whereas `define()` uses the comma as delimiter.

**Comment by bobhairgrove** [comment]
Possible workaround:

1. Create PO files from PHP using `php2po`;
2. Use the PO files to do the translations;
3. Create CSV files using `po2csv`;
4. Open the CSV files in a spreadsheet program and delete the column containing the source text;
5. Save the file as CSV, possibly altering the options (delimiter, quoting, etc.);
6. Open the CSV file in a text editor that can handle column edits (e.g. geany on Linux / UltraEdit on Windows);
7. Fix it so that you have valid PHP syntax and save to a PHP file.

**Comment by bobhairgrove** [comment]
Is anyone looking into this?

**Comment by iafan** [comment]
@bobhairgrove [here's an alternative way](https://gist.github.com/iafan/d0d0e2456522b075d9e0d118a3815494) to deal with your resource files without TTK.

**Comment by dwaynebailey** [comment]
@bobhairgrove not at the moment, we're trying to nail down our next beta release https://github.com/translate/translate/milestone/22

I'll chat with @unho and see if we can load it into the next beta of before final.  Can't promise anything but if we can find an easy fix we can land.

**Comment by bobhairgrove** [comment]
Thanks, Dwayne. I am going to use the PHP array syntax in the meantime -- this does work fine. It's also rather trivial to convert from arrays to defines (and vice-versa) in a good text editor with macro capability.

**Comment by bobhairgrove** [comment]
Has there been any progress here in the past 1-1/2 years?

**Comment by unho** [comment]
This should have been fixed by amazing work carried over by @nijel in #3697.
