### ISSUE TITLE
po2prop is not working as expected

### ISSUE THREAD

**Issue by xinoman12** [translate/translate#3463]
I've spend some days by now and I can't seem to find any solution.

I have a strings file from my ios app and I'm able to convert it successfully to a po using prop2po using this command.

`prop2po --encoding utf8 -t ../en.lproj/Localizable.strings  Localizable.strings es.po`

I'm executing this command inside the `/Strings/es.lproj` where the Localizables.strings is the one having the Spanish translations.

So it creates a es.po file with the msgid form the template and the translations from the Localizables.strings from the current path.

Then when I try to convert back my es.po to a new Localizables.strings with the new translations I'm getting always the template.

I'm using this command:
`po2prop --encoding utf8 -i es.po -o new.strings -t ../en.lproj/Localizable.strings`

new.strings is always the same as the template that I'm using instead of having the translation from the es.po.

Also I think there is something wrong with the gettext file parser as I have to delete this two lines from the es.po generated file in order to work.
`#, fuzzy`
`msgid ""` <--
`msgstr ""` <--

I've added the commented fuzzy but that line does not creates trouble.

If I don't delete theese two lines when I try to use the po2prop command I get this error:
`template ../en.lproj/Localizable.strings: 'NoneType' object has no attribute 'istranslated'`

Is quite misleading as it seems that is has a problem with the template but after many tries I manage to figure that the problem was in the po file.(Or maybe not and I'm missing something).

I'm using the 2.0.0b2 version.

I hope someone can tell me what I'm doing wrong..or if this is actually a bug since I've tried many ways to convert from po2prop using all the settings available and I'm not able to do it right.

Supposedly this should work...

http://stackoverflow.com/questions/13939766/are-there-any-good-tools-for-ios-pseudo-localization

Or this : 

`po2prop -t some.properties some.po some-other.properties` from http://docs.translatehouse.org/projects/translate-toolkit/en/latest/commands/prop2po.html

Thanks,
Rubén.

**Comment by xinoman12** [comment]
Also the link in http://docs.translatehouse.org/projects/translate-toolkit/en/latest/formats/strings.html to the _Localising string resources_ resource it's a 404 so I don't know where else to look.

**Comment by mejatysek** [comment]
Same here. Some files works fine, but i can't figure out whats difference betwen working ones and bugy ones.

**Comment by dwaynebailey** [comment]
@xinoman12 and @mejatysek can you post example files please.  I'd like to know what units are causing those blank entries and I suspect that might be playing havoc with the serialisation back to `.strings`.

If you can't post publicly then please PM me on https://gitter.im/translate/pootle

**Comment by mejatysek** [comment]
@dwaynebailey version 2.0.0b3 work's for me. If you still need/want example files let me know.

**Comment by unho** [comment]
@xinoman12 If you are still experiencing trouble it would be helpful if you can share those files so we can replicate and debug on our side.

**Comment by xino12** [comment]
Okay, here I leave the template and the po file I told in the comment.


[files.zip](https://github.com/translate/translate/files/387952/files.zip)

**Comment by unho** [comment]
The files you provided had duplicated entries (the converters skip them), and the `.strings` file had several blank lines that were causing trouble. Also as pointed out it was trying to convert the first msgid/msgstr pair in the PO file (the header one) when it shouldn't. I have created a PR that solves these issues: #3472

**Comment by unho** [comment]
As reported before your files contain duplicate entries (not a big issue but you should check it), and most importantly the `.strings` file has several blank lines that as far as I can tell do not conform to format specification https://developer.apple.com/library/mac/documentation/Cocoa/Conceptual/LoadingResources/Strings/Strings.html#//apple_ref/doc/uid/10000051i-CH6 so I recommend you to remove those too.

I am landing PR #3472 with a fix for the issue processing first msgid/msgstr pair.
