### ISSUE TITLE
po2xliff conversion issur

### ISSUE THREAD

**Issue by darani73** [translate/translate#3464]
http://docs.translatehouse.org/projects/translate-toolkit/en/latest/installation.html#installing-on-windows
AS per your instructions in above url,I have installed and it is working in my machine in a web application.
but the same above steps i followed in another machine. po2xliff is not working in the same web application It is creating a empty file. I don't what i am missing in that machine (both machines are running windows 10 OS) please help me to fix the issue
In command Prompt po2xliff is working fine in both machines

**Comment by phlax** [comment]
@darani73 did you find out what the problem was?
