### ISSUE TITLE
Add l20n checker

### ISSUE THREAD

**Issue by ta2-1** [translate/translate#3471]
We need to add checker for some l20n format specifics:
- [Variables](http://l20n.org/learn/interpolation-variables)
- [Builtins](http://l20n.org/learn/builtins)
- [Entity refences](http://l20n.org/learn/entity-references)
- [Selectors](http://l20n.org/learn/selectors) and [Advanced selectors](http://l20n.org/learn/advanced-selectors)

**Comment by dwaynebailey** [comment]
@ta2-1 I think you're overthinking this.  In our discussion by checker I literally meant variable checker, using the existing pofilter processing we already have.  Do that and we have varaible checking working.

Certainly the other things can be looked at but I suspect they're a different need.

**Comment by nijel** [comment]
l20n support has been dropped, see https://github.com/translate/translate/pull/4047
