### ISSUE TITLE
printf: Different printf variable: %20d is a html space really

### ISSUE THREAD

**Issue by moylop260** [translate/translate#3478]
We have a po file translating a template of html with spaces %20d
A message of different print variable is emitted.

We have different number of `%20d` because we need add more words for spanish vs english.
- EN: `Order Voucher`
- ES: `El Comprobante de la Orden`

If you use `%20d` instead of space the message is emitted.

Is there way of indicate that there are `%` values that don't are printf variables?

**Comment by unho** [comment]
Why are you not using the `&nbsp;` entity to include extra whitespaces?

**Comment by moylop260** [comment]
That is a good question
