### ISSUE TITLE
Allow accelerator test to test when target language doesn't have accelerators

### ISSUE THREAD

**Issue by dwaynebailey** [translate/translate#3479]
With https://github.com/translate/translate/pull/3476 we landed the ability to switch off the accelerator test completely for languages that don't use accesskeys.  This is fine a good fix for all the current false positives.  However it would now hide incorrect accelerator choices i.e. cases where an accelerators key has been used but should not have been used.

Using this example file you can see the results for each of the cases of a language that requires accesskeys (Afrikaans) and one that should not have accesskeys (Khmer)

```po
# Afrikaans - PASS - Correct use of accesskeys
# Khmer - FAIL - you shouldn't add an accesskey to your translation
#: one 
msgid "&One"
msgstr "&Een"

# Afrikaans - FAIL - missing the accesskey
# Khmer - PASS - we don't want accesskeys in the target
#: two
msgid "&Two"
msgstr "Twee"

# Afrikaans - FAIL - there is no accesskey in the source
# Khmer - FAIL - we don't want accesskeys
#: three
msgid "Three"
msgstr "&Drie"
```

**Comment by dwaynebailey** [comment]
I'm realising that the problem can get worse.  One of the reasons for #3476 is that in Mozilla we choose not to use an accesskey as the platform will provide it.  However in other systems it might be the translator's responsibility to provide the accesskey in a way such as the following:

```po
msgid "&One"
msgstr "Een (&O)"
```

So in these cases normal accelerator checking can proceed.  Its really only the situation in Mozilla where we want to handle a non-accesskey situation.

**Comment by unho** [comment]
>  Its really only the situation in Mozilla where we want to handle a non-accesskey situation.

Thus our initial approach where we disabled `accelerators` check for some languages in `MozillaChecker` as we agreed, and our kinda-agreement on adding some additional check to ensure accelerator absence in target for those very languages in `MozillaChecker`.

In the meantime I wrote a test to ensure TTK does what you expect.
