### ISSUE TITLE
update sourceforge project

### ISSUE THREAD

**Issue by glensc** [translate/translate#3501]
https://sourceforge.net/projects/translate/

please go to your sourceforge project settings and setup new homepage.
sourceforge then will display message to users after that, something like:

> As of 2014-04-08, this project may now be found at https://github.com/smarty-gettext/smarty-gettext.

for example: https://sourceforge.net/projects/smarty-gettext/

**Comment by dwaynebailey** [comment]
We already have a homepage set but it doesn't seem to appear like the smarty-gettext one.  So not 100% sure how to achieve this tbh

**Comment by glensc** [comment]
there's some setting to tell "my project moved elsewhere". i could look from my project if you have problem finding the setting.

**Comment by dwaynebailey** [comment]
Finally found it. https://sourceforge.net/projects/translate/

Thanks @glensc
