### ISSUE TITLE
Add [[ sections ]] support in l20nfile

### ISSUE THREAD

**Issue by ta2-1** [translate/translate#3516]
`[[Sections]]` allow grouping entities that belong to a particular piece of UI. We need to add such support when parsing `.ftl` and convert resources.

```
[[ File menu ]]

file-menu =
    [xul/label]     File
    [xul/accesskey] F
tab-menuitem =
    [xul/label]      New Tab
    [xul/accesskey]  T
tab-command =
    [xul/key]        t
new-user-context-menu =
    [xul/label]      New Container Tab
    [xul/accesskey]  C
```

**Comment by nijel** [comment]
l20n support has been dropped, see https://github.com/translate/translate/pull/4047 and this doesn't seem to be present in fluent, see https://www.projectfluent.org/fluent/guide/

**Comment by flaki** [comment]
> and this doesn't seem to be present in fluent

To be fair, the concept of sectioning a translation resource does exist in Fluent, it is done by delineating the sections with _double-hashed comments_ (##), as explained here:

https://projectfluent.org/fluent/guide/comments.html

I was actually looking for a way to group messages together in Weblate when we started using it (yesterday), so it would be much welcome if this was supported by Weblate.

**Comment by nijel** [comment]
@flaki please open separate issue for that.
