### ISSUE TITLE
Discrepancy on number of pofilter checks

### ISSUE THREAD

**Issue by leonardcj** [translate/translate#3527]
42 or 48?

http://docs.translatehouse.org/projects/translate-toolkit/en/latest/features.html
Our checker has over 42 checks to find errors such as: missing or translated variables, missing accelerator keys, bad escaping, start capitalisation, missing sentences, bad XML and much more.

http://docs.translatehouse.org/projects/translate-toolkit/en/latest/commands/pofilter_tests.html
Currently there are 48 tests.

**Comment by unho** [comment]
I am not an English speaker, but over covers 48 or 1 trillion, isn't it? :)

Yes, we can adjust the number.

**Comment by unho** [comment]
If you leave out the extraction checks it is exactly 42. I am now leaning towards leaving this unchanged.

**Comment by dwaynebailey** [comment]
@leonardcj I wanted to avoid maintaining a number and not have to update those every time we added a new check.  Yip and its likely it excludes the extraction tests.

42 has such a nice geek ring, lets not change that until we have 'over 50' checks

**Comment by leonardcj** [comment]
No worries.  Just pointing it out.
