### ISSUE TITLE
json file flattened after po2json

### ISSUE THREAD

**Issue by unho** [translate/translate#3541]
This has been originally reported by @cgarreau in https://github.com/translate/pootle/issues/5693

Hi, I'am using po2json with a template json file that includes UI grouping section:

```json
{
  "group": {
    "label1": "abc",
    "label2": "def"
  }
}
```

after using po2json the json result is flattened:
```json
{
  "group.label1": "abc",
  "group.label2": "def"
}
```

This is a regression since commit https://github.com/translate/translate/commit/40ab1e74a1a1b4a1472967f03b0571388ee77f82 than fixes #3249

**Comment by andreistefan87** [comment]
I suggest this to be fixed by adding a new feature / command line argument (e.g --flattenresult), based on which the output will be flattened or not.

**Comment by BhaaLseN** [comment]
Weblate uses a [hook](https://github.com/WeblateOrg/weblate/blob/master/examples/hook-json_restore_hierarchy) to restore the hierarchy before committing it back; maybe this can be used/integrated here.

**Comment by mkjaxxo** [comment]
I ran into the same issue. I hoped it had been solved with "Added support for nested JSON" of 2.2.4.
Any chance to get this as an option or default (preserve the initial structure of json source file)?

**Comment by huftis** [comment]
I’ve also run into this issue, on JSON files downloaded from Transifex (and which won’t reupload because of the flattening done by po2json).
