### ISSUE TITLE
Display reports from coverage tools

### ISSUE THREAD

**Issue by unho** [translate/translate#3572]
It would be helpful to integrate reports from coverage tools like codecov or coveralls like in Pootle repository. This will surely help to increase test coverage and thus allow for a faster cleanup of API.

**Comment by nijel** [comment]
I think codecov is better for this than coveralls, mostly due to better support for pull requests. See https://github.com/translate/translate/pull/3591

**Comment by dwaynebailey** [comment]
Coverage has been on for some time, but pings back to PRs it seems have not.  This has been sorted with the #3591 fix and others.
