### ISSUE TITLE
do the installed .py files require `#!/usr/bin/env python`?

### ISSUE THREAD

**Issue by juhp** [translate/translate#3609]
When building translate-toolkit for Fedora, packaging tests complained about
the `#!/usr/bin/env python` shebangs in the installed .py files which are not executable.
Since they all seem to get wrapper scripts in `/usr/bin/` anyway, I think the shebangs
are unnecessary and could safely be removed. Would such a patch be acceptable?

If so I can open a PR.

**Comment by juhp** [comment]
rpmlint output:
```
translate-toolkit.noarch: E: non-executable-script /usr/lib/python3.6/site-packages/translate/convert/csv2po.py 644 /usr/bin/env python
This text file contains a shebang or is located in a path dedicated for
executables, but lacks the executable bits and cannot thus be executed.  If
the file is meant to be an executable script, add the executable bits,
otherwise remove the shebang or move the file elsewhere.
```

**Comment by juhp** [comment]
Fedora bug to track this: https://bugzilla.redhat.com/show_bug.cgi?id=1442002

**Comment by phlax** [comment]
hi @juhp - i think these are not needed - feel free to PR - or one of us can clean up - thanks for reporting
