### ISSUE TITLE
Use .gz for releases uploaded to pypi

### ISSUE THREAD

**Issue by nijel** [translate/translate#3612]
There seem to be set of users who end up using Python without bzip2 support (see http://stackoverflow.com/q/812781/225718 or https://github.com/WeblateOrg/weblate/issues/1451 for examples). Making the release in gz would avoid installation problems, though I'm not really sure if this is something worth fixing (and I haven't checked how big difference in size that would create).

On the other side, it seems that most projects published on pypi do use gzip, so using that is probably most common choice (and default in setuptools).

Anyway the fix would be simple:

```patch
diff --git a/Makefile b/Makefile
index 88eb6631..b25c074d 100644
--- a/Makefile
+++ b/Makefile
@@ -1,5 +1,5 @@
 DOCS_DIR = docs
-FORMATS=--formats=bztar
+FORMATS=--formats=gztar
 
 .PHONY: all build docs requirements help publish-pypi sort-imports
 ```

**Comment by unho** [comment]
Since we just released I used the opportunity to compare the size difference. Using `bztar` the size is 4.8 MB and with `gztar` the size increases to 6.0 MB, that means it is 25% larger.

So I am closing this as a wontfix for now.

**Comment by phlax** [comment]
@unho can you not just publish both formats?

**Comment by nijel** [comment]
No, pypi accepts just one upload. In past it was possible to upload multiple sources, but AFAIK that no longer works.

**Comment by phlax** [comment]
in which case my vote goes with gz as its more widely available

**Comment by unho** [comment]
Changed to gzip in 2373e650fc82258363b410acbbb13cfc712b68ae as requested.
