### ISSUE TITLE
Plurals in Ruby YAML Files

### ISSUE THREAD

**Issue by Artoria2e5** [translate/translate#3615]
As displayed in the good old sample (https://github.com/noosfero/noosfero/blob/master/config/locales/en-US.yml), Ruby (or rails-i18n)'s YAML localization format has some basic plural handling to deal with. This goes down to these `one` `other` things here:

```YML
      less_than_x_minutes:
        one:   "less than a minute"
        other: "less than %{count} minutes"
```

Subkeys used for each language in Ruby's YAML files come directly from [Unicode CIDR Plural Rules](http://www.unicode.org/cldr/charts/28/supplemental/language_plural_rules.html). A basic heuristic for finding plurals is therefore:

1. Look at a key.
2. Does it point to a dictionary? Otherwise return false.
3. Does any of its sub-key members point to a non-string thing? If so, return false.
4. Are all its sub-keys part of the Unicode CIDR cardinal terminology (zero, one, two, few, many, other)? Otherwise return false.
5. Guess true.

Arguably one can never be sure about which key is a plural key, as a perfectly (ab)normal key can also have subkeys named just like plural string groups. Step four can probably improved by some stricter per-language checks.

The current HEAD version does not seem to have such a feature. Since there is no such thing as ruby-yaml-to-po in translate-toolkit, all my observations should be treated as a guess and verified by someone else.

**Comment by nijel** [comment]
PR implementing this is here: https://github.com/translate/translate/pull/3846
