### ISSUE TITLE
Obsolete po units show as fuzzy

### ISSUE THREAD

**Issue by phlax** [translate/translate#3616]
Currently if a unit is marked as `fuzzy` *and* `obsolete` in a po file it shows as both

this is from debugging in pootle
```
(Pdb) self.newunit
<translate.storage.pypo.pounit object at 0x7f02d6f65650>
(Pdb) self.newunit.isfuzzy() 
True
(Pdb) self.newunit.isobsolete()
True
```

im thinking it should only be `obsolete`

not sure about implications for other formats.

**Comment by dwaynebailey** [comment]
Doing a check on PO this is actually valid afaikt.

The following file:
```
msgid "One"
msgstr "Een"

#, fuzzy
#~ msgid "Won"
#~ msgstr "Een"
```

Will `msgcat` as exactly that.  So in fact a PO unit can be fuzzy and obsolete it would seem. So ttk is doing the right thing.

**Comment by dwaynebailey** [comment]
Closing as invalid, we mimic Gettext, even if it doesn't quite feel logical.
