### ISSUE TITLE
OrderedDictYAMLLoader fails on input yaml with numbers (similar as #3363)

### ISSUE THREAD

**Issue by OdyX** [translate/translate#3619]
As can be seen in https://github.com/translate/translate/blob/master/translate/storage/yaml.py#L188 , the OrderedDictYAMLLoader raises an exception (that currently isn't catched by Weblate) on integer inputs in a Ruby YAML file.

The integers should be used as-is, or just ignored.

**Comment by nightpool** [comment]
Would be nice to see a fix for this soon, we're adding weblate to a reasonably large rails project and ran into a couple errors of this ilk

**Comment by Frexuz** [comment]
Same here!

**Comment by unho** [comment]
@nijel Can you look into this?

**Comment by nijel** [comment]
Proposed fix is here: https://github.com/translate/translate/pull/3785
