### ISSUE TITLE
Use a third-party PHP parser for PHP support

### ISSUE THREAD

**Issue by rimas-kudelis** [translate/translate#3625]
I think that instead of having TTK's own minimal PHP parser which relies on regex and such, it might make sense to use a third-party PHP parser, even if it has way more to offer than necessary for TTK.

One such parser might be https://github.com/viraptor/phply. I haven't tested it, but the README looks quite promising.

**Comment by nijel** [comment]
I've given this a try, see https://github.com/translate/translate/pull/3697 (still not for merge as it produces slightly different output than previous code).
