### ISSUE TITLE
PHP: Can't parse if newline between delimiter and value

### ISSUE THREAD

**Issue by unho** [translate/translate#3628]
Reported by @rimas-kudelis:

When there is a newline after delimiter (`=>` in the example below) and the value within an array the parser doesn't work:

```php
<?php
return array(
    'parent3'=> array(
            'key1' =>
                'value2',
        ),
);
```

**Comment by rimas-kudelis** [comment]
This looks like a dupe of #2647.

**Comment by unho** [comment]
Yes, part of what is on this issue is already covered by https://github.com/translate/translate/issues/2647. I am repurposing this issue.
