### ISSUE TITLE
Directional non printable characters

### ISSUE THREAD

**Issue by yarons** [translate/translate#3635]
Since most of my daily translation work is somehow related to Translate Toolkit in some way this bug really bothers me!

Let's pretend I have this source string:
As a customer of (some) Corporation, Product will work for you.

When I come to translate it to Hebrew I need to use RLM characters in order for the text to appear in the correct order:
<div dir="rtl" align="right">
כלקוח של החברה (כלשהי) Corporation,‏ Product יעבוד למענך.</div>
In case you were wondering there's an RLM right after the comma and the word Corporation so the words in English will appear correctly (since comma is agnostic to the directionality of the paragraph it inherits the directionality from the surroundings in this case).

This is the same sentence without directionality characters:
<div dir="rtl" align="right">
כלקוח של החברה (כלשהי) Corporation, Product יעבוד למענך.</div>

In that preticular case I'm seeing an error about changing the order of the punctuation, now that's completely untrue since RLM has nothing to do with punctuation and the order remains.

We're seeing this behaviour mostly in Mozilla Pontoon but there are other cases as well.

**Comment by dwaynebailey** [comment]
The Translate Toolkit doesn't have anything to do with text rendering, you need to ask your tool developer to fix that.  But most likely they're relying on your platform or browsers Unicode bidi algorithm and that's where you'll win or lose.

In Pootle we make things like RLM markers available in the editor and have a raw mode precisely to have more fine grained control for cases where the Bidi layout isn't working correctly.

Please reopen if I've misunderstood your error report

**Comment by yarons** [comment]
Indeed, misunderstood 😄

The check `puctspacing` will trigger in cases where I've added directional characters between 2 punctuation characters, in many cases in Hebrew it's desirable.

http://docs.translatehouse.org/projects/translate-toolkit/en/latest/commands/pofilter_tests.html#puncspacing

Sorry for the mess earlier.

**Comment by friedelwolff** [comment]
I didn't review this, but I'm guessing this happens because the puncspacing is looking for <comma><space> and is not finding it, since the RLM is now between the two characters. I'm not sure if we should simply strip RLM before doing the test, or what will help, but personally I haven't paid any attention to the puncspacing test in years. It is completely useless for me.

**Comment by dwaynebailey** [comment]
@yarons are you able to create a small snippet that show the issue we can look at coding a fix, I'm sure many Bidi languages would benefit.  And I'd prefer to have reports of failure which we can fix then people ignoring tests.

**Comment by yarons** [comment]
I can't come up with an original string that might trigger an error when the puncspacing is changed.

Maybe something like ",."? and then I'll try adding RLM between them?

**Comment by dwaynebailey** [comment]
@yarons the ideal is something small but valid, so less demo then an actual small example.  But that is known to break puncspacing.  Then I can at least see if this is something that can be adapted for Hebrew or for Bidi languages in general.

**Comment by yarons** [comment]
@dwaynebailey I don't knooooow how to do it, is there some kind of playground or something that will help me achieve that?

Thanks.

**Comment by dwaynebailey** [comment]
@yarons this a new bug from what I can see, related to quotes and not RLM.  The checks will adjust for different quote styles, we just need to actually know what character is used for Hebrew quotes.  Would you mind opening a new bug to specify hebrew quotes

**Comment by yarons** [comment]
@dwaynebailey Sure, I can use this example to demonstrate the problem with RLM as well, how can I supply a working example of the problem that will please you?

**Comment by dwaynebailey** [comment]
If you can provide a very simple example string that would be a start

**Comment by yarons** [comment]
English: Hello, world
<div dir="rtl" align="right">Hebrew:‏ שלום,‏ עולם‏</div>

Adding RLM or LRM at the beginning or the end will lead to Starting Punctuation, Ending Punctuation respectively.

If there will be no problem with copying you should see the same errors, if not just add RLM and LRMs between the words and around the punctuation.

It probably affects LRE, RLE, LRO, RLO etc.
As far as I'm concerned ZWNJ shouldn't be used around period and comma but it probably affects too.

Is that good enough?

**Comment by dwaynebailey** [comment]
@yarons is it possible to add those into a snippet of a PO files?

```po
msgid ""
msgstr ""
```

Then we can probably work with it.

**Comment by yarons** [comment]
[test.txt](https://github.com/translate/translate/files/1089186/test.txt)
Uploaded as txt file due to GitHub limitations on file extension.

Thanks and sorry for the delay.

**Comment by dwaynebailey** [comment]
@yarons looks like I have a solution.  Just removing `\u200f` before running the check.  I'd rather work from examples in the wild so lets leave ZWNJ.  I'll try PR something tomorrow

**Comment by yarons** [comment]
@dwaynebailey Cool, don't forget all the other directionality characters 😃

**Comment by dwaynebailey** [comment]
@yarons don't forget to give me a Hebrew quoting examples please ;)

I'm reluctant to add anything but RLM and LRM without tests that show it in action.  Some other examples with those would be helpful.  Perhaps @khaledhosny could construct some Arabic examples for this?

**Comment by yarons** [comment]
I've made a complete example with all known directionality characters (with the help of this tool: http://r12a.github.io/pickers/arabicblock/).

The last two are in Arabic and in addition to puncspacing there's a spelling mistake (I think it's fine because there's no reason for ZWNJ to ZWJ to be somewhere else but between two Arabic letters).

Tested with Virtaal.
[test.txt](https://github.com/translate/translate/files/1091160/test.txt)

**Comment by dwaynebailey** [comment]
@yarons I'm going to paste that last bit in a new issue.  One bug per issue please, just so that we can track and know that something is done. The quotes really aren't part of the puncspacing

**Comment by dwaynebailey** [comment]
@yarons that is a brilliant PO file, I thought I might have to pick it out, but one issue one examples is perfect.

**Comment by yarons** [comment]
@dwaynebailey Woo hoo! So much compliments 😃 I think I'll stay!

Regarding the quote: sure, my bad, I'll track that too.
Thanks a lot!
