### ISSUE TITLE
switch to tar.gz intentional?

### ISSUE THREAD

**Issue by ilovezfs** [translate/translate#3644]
I noticed the release tarball for 2.2.1 is tar.gz this time instead of tar.bz2

Was that intentional? CC @unho

**Comment by unho** [comment]
@ilovezfs Yes, it is intentional. See https://github.com/translate/translate/issues/3612 for reasons. Is it a problem for you or anyone else you know?

**Comment by ilovezfs** [comment]
@unho nope it's not a problem at all. I only noticed because I had to intervene to change the extension when the auto update script failed as I was opening https://github.com/Homebrew/homebrew-core/pull/14726. Thanks for confirming!
