### ISSUE TITLE
rc2po does not work on input with windows newlines

### ISSUE THREAD

**Issue by learn-more** [translate/translate#3664]
When Reading .rc files that use windows newlines, rc2po failts to output anything.
(No error message, no .po file).
By adding:
`rcsrc = rcsrc.replace('\r\n', '\n')`
in `rcfile.__init__` between the close and the parse, files are output successfully.

**Comment by dwaynebailey** [comment]
@learn-more could you PR that proposed with with a test? That would be greatly appreciated and help get that code into TTK.

**Comment by learn-more** [comment]
Well it is more of a workaround, since it does not remember line endings, end thus effectively destroys them.

**Comment by SantosSi** [comment]
I do not understand: replacing the Windows style newlines with *nix style ones make them forgotten? Isn't it possible to make the software work with Windows style newlines instead, e.g. by finding the incompatible code?
