### ISSUE TITLE
Note might not handled correctly in xliff

### ISSUE THREAD

**Issue by mastizada** [translate/translate#3671]
`translate.storage.xliff.xliffunit` do not indent `note` tags.
That might be reason for bug #3670

**Comment by mastizada** [comment]
@unho Can you approve?

**Comment by unho** [comment]
@mastizada If you mean approve PR https://github.com/translate/translate/pull/3670 I am afraid I can't approve until the raised concerns in the PR are addressed or at least a good reason is provided to not address those.

**Comment by unho** [comment]
I am closing this issue in favor of https://github.com/translate/translate/issues/3424 which raises the same concern about XLIFF not correctly indenting the `note` tags.
