### ISSUE TITLE
Advanced Yaml support

### ISSUE THREAD

**Issue by Lozik** [translate/translate#3695]
In the docs ( http://docs.translatehouse.org/projects/translate-toolkit/en/latest/formats/yaml.html ), I saw that parts of Yaml features are not yet supported. I just wanted to ask if that is planned and if so, if there is any progress being made. Especially the multiline and quoted strings features would be of great importance.

My use case: I use Symfony as web framework and Weblate as translation tool that is based on the Translate Toolkit. As the tool makes it possible to directly push changes, it would be extremely useful to have compatible files build directly by the tool without having to change the files to make them compatible.

Thank you for your valuable work!

**Comment by unho** [comment]
Contributions are always welcome, and we offer paid development if you are willing to pay. But we don't have any specific plan yet on completing YAML support. Weblate developers often contribute, and in fact YAML format support was contributed by them, so I won't be surprised if they contribute the required improvements.

**Comment by nijel** [comment]
I've written most of the YAML support, but I currently do not have any plans to extend it as it serves well in situations I need. Is there some specific issue you're hitting?

**Comment by Lozik** [comment]
Thank you for your answers. Yes, i'm getting the issue that exporting a longer (multiline) string to yaml is not saved as multiline string (using | or >) but as a quoted string which has backslashes before every newline character. 
However, I'm not enough in the topic to tell if this is an issue/missing feature of the Translate Toolkit or if it is only caused by the Weblate project. Sorry about that.

**Comment by nijel** [comment]
The second issue is actually per YAML specification and there are more strings which get parsed as true/false values what can be pretty confusing, see http://yaml.org/type/bool.html

You can try it yourself, enter "yes: no" into http://yaml-online-parser.appspot.com/ and you will get:

```
{
  "true": false
}
```

**Comment by Lozik** [comment]
Hmm, yes, I see.
 I suppose, for the booleans, the error is on the Symfony side, as the parsing component isn't using a strict verification for translations and accepts a `yes: Yes`.

**Comment by nijel** [comment]
Most of incompatiblities should be addressed by https://github.com/translate/translate/pull/3926
