### ISSUE TITLE
does not match `msgcat --no-wrap` format, wraps blocks differently than gettext

### ISSUE THREAD

**Issue by eighthave** [translate/translate#3765]
We use `msgcat --no-wrap` format with Weblate since it means greatly reduced git diffs and merge conflicts.  There is still one incompatibility between Weblate and `msgcat --no-wrap`.  Since Weblate is just using the lib to do the wraping, from what I can tell, I'm filing the issue here.  Apoligies if its the wrong place.

Here's an example diff caused by running `msgcat --no-wrap` on .po files just fetched from Weblate:

```diff
diff --git a/po/_docs.bo.po b/po/_docs.bo.po
index 0b82316..eb08c38 100644
--- a/po/_docs.bo.po
+++ b/po/_docs.bo.po
@@ -4,7 +4,19 @@
 # FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
 #
 msgid ""
-msgstr "Project-Id-Version: PACKAGE VERSION\nReport-Msgid-Bugs-To: team@f-droid.org\nPOT-Creation-Date: 2018-02-12 17:42+0100\nPO-Revision-Date: 2018-02-16 05:40+0000\nLast-Translator: Allan Nordhøy <epost@anotheragency.no>\nLanguage-Team: Tibetan <https://hosted.weblate.org/projects/f-droid/website-docs/bo/>\nLanguage: bo\nMIME-Version: 1.0\nContent-Type: text/plain; charset=UTF-8\nContent-Transfer-Encoding: 8bit\nPlural-Forms: nplurals=1; plural=0;\nX-Generator: Weblate 2.19\n"
+msgstr ""
+"Project-Id-Version: PACKAGE VERSION\n"
+"Report-Msgid-Bugs-To: team@f-droid.org\n"
+"POT-Creation-Date: 2018-02-23 10:04+0100\n"
+"PO-Revision-Date: 2018-02-16 05:40+0000\n"
+"Last-Translator: Allan Nordhøy <epost@anotheragency.no>\n"
+"Language-Team: Tibetan <https://hosted.weblate.org/projects/f-droid/website-docs/bo/>\n"
+"Language: bo\n"
+"MIME-Version: 1.0\n"
+"Content-Type: text/plain; charset=UTF-8\n"
+"Content-Transfer-Encoding: 8bit\n"
+"Plural-Forms: nplurals=1; plural=0;\n"
+"X-Generator: Weblate 2.19\n"
 
 #. type: Title #
 #: build/_docs/md/All_About_Descriptions_Graphics_and_Screenshots.md
```

source: https://gitlab.com/fdroid/fdroid-website

translations: https://hosted.weblate.org/projects/f-droid/website-docs/

and some context: #340 #3702 WeblateOrg/weblate#961

**Comment by nijel** [comment]
This is intentional. As for translate-toolkit it can behave in both ways:

- setting width to -1 will make it do no wrapping at all (this is what you observe)
- setting width to big value (gettext uses INT_MAX - 1) will keep wrapping on `\n`

So I don't think there is anything to fix in translate-toolkit.
