### ISSUE TITLE
Please create a new release tag

### ISSUE THREAD

**Issue by sotathan** [translate/translate#3815]
Fixes [b92873d4](https://github.com/translate/translate/commit/b92873d4c212d959951e37bba5f02c4bc5021c09) and [6289ea55](https://github.com/translate/translate/commit/6289ea5533b63fb0e7cdc4249d1a601af6b98fee) are essential to our project.

Could you please create a new tag.

Thanks,
Sotiris

**Comment by unho** [comment]
@sotathan Translate Toolkit 2.3.1 has just been released.

**Comment by sotathan** [comment]
Thanks @unho !!!
