### ISSUE TITLE
Better handle nested keys

### ISSUE THREAD

**Issue by nijel** [translate/translate#3819]
Currently there are several ways in translate-toolkit to handle nested IDs in translation format.

What I know is that:

* XLIFF uses `u"\04"`
* YAML uses `->`
* JSON uses `.`

All these are problematic as they can as well occur in the actual value and leads to possible problems when serializing. Only XLIFF seems to care about escaping in this case.

It would be great if this would be consistent and error prone, but any change can lead to problems in convertors as they would now generate different IDs.

In the end I think using `u"\04"` with proper escaping should be fine. Another option is to use tuple as ID in this case.

Related code snippets:

https://github.com/translate/translate/blob/master/translate/storage/xliff.py#L498-L509

https://github.com/translate/translate/blob/master/translate/storage/jsonl10n.py#L184-L195

https://github.com/translate/translate/blob/master/translate/storage/yaml.py#L177-L194

**Comment by unho** [comment]
This is a very nice one. Thanks for raising it!

**Comment by nijel** [comment]
The similar issue is with lists - they are encoded as `key[index]`, but the same value can be used as actual key in the files.

**Comment by nijel** [comment]
@unho I was thinking how to address this and I think that using strings to encode this is not really a good idea. What about introducing following objects to track this:

```python
class UnidId(object):
    def __init__(self, *items):
        self.items = items

    def __str__(self):
        return ''.join([str(item) for item in items])

class UnitIdKey(object):
    def __init__(self, value):
        self.value = value

    def __str__(self):
        return '.{}'.format(self.value)

class UnitIdList(object):
    def __init__(self, value):
        self.value = value

    def __str__(self):
        return '[{}]'.format(self.value)
```

It will work as strings (for the converters into formats which do not support this), but will keep the detailed information for the ones which do.

It would be used by something like this:

```python
def getid():
    return UnitId(UnitKey('hello'), UnitIdList(1))
```

What do you think about this approach?

**Comment by unho** [comment]
I am not sure I understand. Can you please share an example JSON (or PHP) and explain how this would work?

I am most concerned about if this would break backwards compatibility, and how.

**Comment by unho** [comment]
Also unrelated to all of this I would really like to get rid of `setid` and `getid` in favor of a `unit_id` property, if possible.

**Comment by nijel** [comment]
The `getid` would return this object instead of string. It would allow to know exact id (or path in the original document), but it would still work as a string for uses which don't care about this, so backwards compatibility should be kept (that's motivation for the `__str__` methods). Of course this needs to be tested, but I first wanted to know whether this is viable approach before I spend more time on this.

Alternative would be to introduce more special chars as a separators similarly as currently done with `u"\04"` in xliff.

**Comment by nijel** [comment]
I've given it some time and tried to implement it for JSON in https://github.com/translate/translate/pull/3835

**Comment by unho** [comment]
I've left some comment in the PR with the example. Generally I like the idea, but I feel it inconvenient to have to enclose all calls to `getid()` with a call to `str()`, which is something that can be easily avoidable by using a new different method, for example `get_key()` (check first that is not already being used).

And as I said in a previous comment in this issue, I am looking towards getting rid of `getid()` and `setid()` method in favor of a `unit_id` property in the future which would return the string representation for the unit key.
