### ISSUE TITLE
2.3.1 release ?

### ISSUE THREAD

**Issue by Toub** [translate/translate#3829]
When can we expect a 2.3.1 release with last fixes from master?

Waiting for this one: https://github.com/translate/translate/commit/f50aace4e62e37bdc9d122f8b59da4d7b7b5bc68

**Comment by unho** [comment]
I will try to book some time to do a new release as soon as I can.

**Comment by unho** [comment]
@Toub That particular commit is already included in the latest published release. You can easily install it with `pip` (or any other method listed in http://docs.translatehouse.org/projects/translate-toolkit/en/latest/installation.html ).

**Comment by Toub** [comment]
Oh, my bad, this commit is from 2017, not 2018.

So, the bug is back in 2.3.0 :-(

@see https://github.com/translate/translate/issues/3827
