### ISSUE TITLE
Romanian plural trailing semicolo

### ISSUE THREAD

**Issue by arski** [translate/translate#3837]
Hi there, is it me or should the definition of Romanian plural not have a trailing semicolon in https://github.com/translate/translate/blob/master/translate/lang/data.py#L160 ? all others don't.

**Comment by vinyldarkscratch** [comment]
Seems a little strange indeed -- the semicolon doesn't actually have any effect on the expression, and removing it doesn't cause a failing build.  Cleaning that up in the form of a PR.  :wink:

**Comment by arski** [comment]
:+1:

**Comment by unho** [comment]
Fixed after merging proposed PR.
