### ISSUE TITLE
Make toolkit compatible with diff-match-patch 20181111

### ISSUE THREAD

**Issue by rffontenelle** [translate/translate#3843]
As of translate-toolkit 2.3.1, in Arch Linux 64-bit, `po2tmx` and other tools fails with diff-match-patch 20181111 ([site]), because `diff-match-patch==20121119` is required.

```
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 581, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 898, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 789, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (diff-match-patch 20181111 (/usr/lib/python3.7/site-packages), Requirement.parse('diff-match-patch==20121119'), {'translate-toolkit'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/po2tmx", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3126, in <module>
    @_call_aside
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3110, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3139, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 596, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 784, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'diff-match-patch==20121119' distribution was not found and is required by translate-toolkit
```

[site]: https://pypi.org/project/diff-match-patch/

**Comment by rffontenelle** [comment]
@nijel So, just to confirm, building Virtaal from latest master commit won't be a problem without diff-match-patch==20121119, right?

**Comment by nijel** [comment]
I have no clue about that, sorry. Latest Virtall just doesn't try to import diff_match_patch from translate-toolkit.

**Comment by unho** [comment]
@rffontenelle AFAICT Virtaal needs diff-match-patch==20121119 which is the one TTK requires. I am checking the changes introduced with the new version to see how much it changed.

**Comment by unho** [comment]
I am almost sure that upgrading TTK to use `diff-match-patch==20181111` won't cause any trouble on Virtaal. The only problem is that the newest diff-match-patch version requires Python 2.7 or Python 3.4 or newer.

**Comment by vinyldarkscratch** [comment]
As the classifiers specify for this repository, we don't support 2.6 and below anyways, and Travis only tests against 2.7.  Python 3.3 might be a bit of a problem, however.

**Comment by nijel** [comment]
Quoting upstream: "support for the 3.3 series of releases ended on 2017-09-29", that's year ago. 
Was there any distro having that as default version?

**Comment by unho** [comment]
FYI, I have greenlighted PR #3845 which drops diff-match-patch altogether.

**Comment by rffontenelle** [comment]
Thanks for fixing it!

For the record,  I successfully built and used the combination translate-toolkit (latest revision), diff-match-patch 20181111, and virtaal (latest revision).  Virtaal still imports diff-match-patch, but version 20181111 seems to work just fine.

**Comment by unho** [comment]
> For the record, I successfully built and used the combination translate-toolkit (latest revision), diff-match-patch 20181111, and virtaal (latest revision). Virtaal still imports diff-match-patch, but version 20181111 seems to work just fine.

@friedelwolff would like to hear that.
