### ISSUE TITLE
Link download 2.3.1 on TTK page doesn't work

### ISSUE THREAD

**Issue by elchevive** [translate/translate#3859]
Hi,

The link on ttk page to download the latest version (2.3.1) doesn't work:

https://toolkit.translatehouse.org/download.html

Regards,

Luiz

**Comment by nijel** [comment]
@unho The release tarball is missing from https://github.com/translate/translate/releases/tag/2.3.1

**Comment by unho** [comment]
Fixed. Thank you very much @elchevive for reporting. Thank you very much @nijel for diagnosing the issue.
