### ISSUE TITLE
msgfmt JS implementation

### ISSUE THREAD

**Issue by yarons** [translate/translate#3867]
We're having some thought over at [Weblate](https://github.com/WeblateOrg/weblate/issues/1989) about adding browser level support for `msgfmt` checks on the fly.

I ran into the following project but I'm not sure it'll be able to provide what we're looking for:
https://messageformat.github.io/messageformat/

Do you know of any good way to implement msgfmt checks on the fly without using the server side?

**Comment by julen** [comment]
What are the specific `msgfmt` checks you are referring to? Are you referring to the Gettext `msgfmt` command? FWIW that's a way to compile PO files to MO, and has nothing to do with translation quality checks. On the other hand, the library you linked to, albeit having a similar name, has nothing to do with `msgfmt` nor Gettext.

**Comment by yarons** [comment]
I'll explain the motivation to help you better understand what I'm after.

One of the many gettext implementations are Weblate which is an online localization platform.
I was talking to Michal, the project owner, about adding checks on the fly so when there's a C-format or a double word check it will be highlighted before attempting to save the string (more convenient to the translator and saves some server side resources).

So, if the checks were implemented in JS it was possible and this online platform (along many others available today and more to come) could benefit from such implementation for their products.

Thanks.

**Comment by julen** [comment]
Thanks @yarons, I see now what the end goal is (also checked the linked issue).

> Do you know of any good way to implement msgfmt checks on the fly without using the server side?

This would need to be implemented in JS — or in some language that allows compiling logic down to wasm, but then offer a JS API anyway. TTK is a Python library, and I'm afraid what you are suggesting here is out of the scope of the project, sorry.

**Comment by yarons** [comment]
So it should be a complimentary project?
In case of a possible implementation it should be a set of rules defined by regex with logical connections between them, if there's some logical map it would probably be easier to implement such a thing.

Thanks!

**Comment by phlax** [comment]
> if there's some logical map it would probably be easier to implement such a thing.

some time ago, i had a go at moving checks into regexes that could be used by both js and python - but atm i think you would need to code them by hand in js - and this would need to be added to eg weblate

**Comment by yarons** [comment]
If it's a complete fork with no programmatic ability to sync with the Python origin there's a good chance it will become unmaintained at some point (unless it's being actively developed and used).

The thing is that the Weblate maintainer (@nijel) is also very active in here but I'm not sure that creating this kind of project is part of his roadmap.

I'm guessing that if I could find any nodeJS based localization system I could push this forward but I can't find any.

**Comment by nijel** [comment]
I currenlty have no intention in implementing client-side checks. It would probably never cover all of checks in Weblate (some needs database access or use big data sets which are not suitable for client side use) and in many cases it would mean maintaining two implementations of the checks. As mentioned before, some of the checks could be done purely by regexp and those would be easy to run on client side, but I don't think such partial solution is worth of the effort.
