### ISSUE TITLE
Travis CI tests segfaults

### ISSUE THREAD

**Issue by nijel** [translate/translate#3873]
Since about yesterday, the Travis CI build often fails with segfault.

* First failing build: https://travis-ci.org/translate/translate/builds/492093783
* Last good build: https://travis-ci.org/translate/translate/builds/488970442

There seems to be difference on some libraries, but my guess would be lxml upgrade from 4.3.0 to 4.3.1.

**Comment by nijel** [comment]
It seems to be more or less fixed, I no longer see these failures in builds for #3871...

**Comment by nijel** [comment]
...hmm rather I was just lucky, tests for https://github.com/translate/translate/pull/3838 still segfault.

**Comment by unho** [comment]
Nice! @nijel Thank you very much for your effort!
