### ISSUE TITLE
Nested YAML dictionary is serialized as OrderedDict in PO file

### ISSUE THREAD

**Issue by svenihoney** [translate/translate#3895]
### Problem
If there is a nested dictionary in a YAML file, the resulting po file contains a string starting with `OrderedDict`
### Expectation
The nested keys are shown correctly in the PO file
### How to reproduce
The following YAML input
```
e1:
- s1: Subtag 1
```
given to `yaml2po -i test.yml -o test.po` results in the PO file content of
```
#: t1-%3E[0]
msgid "OrderedDict([('s1', 'Subtag 1')])"
msgstr ""
```
I would expect something like
```
#: t1-%3E[0]-%3Es1
msgid "Subtag 1"
msgstr ""
```
Perhaps it may be related to #3819.

**Comment by nijel** [comment]
Should be fixed by https://github.com/translate/translate/pull/3898
