### ISSUE TITLE
Traceback with non-ascii header key

### ISSUE THREAD

**Issue by friedelwolff** [translate/translate#3896]
If a PO header contains a non-ASCII key (left of the colon), we have a traceback. An example is file here:
https://gitlab.gnome.org/GNOME/gimp/blob/master/po-python/oc.po#L21

The traceback comes from poheader.gettargetlanguage():

```python-traceback
  File "env/lib/python2.7/site-packages/translate/storage/poheader.py", line 286, in gettargetlanguage
    header = self.parseheader()
  File "env/lib/python2.7/site-packages/translate/storage/poheader.py", line 219, in parseheader
    return parseheaderstring(header.target)
  File "env/lib/python2.7/site-packages/translate/storage/poheader.py", line 52, in parseheaderstring
    key = str(key.strip())
UnicodeEncodeError: 'ascii' codec can't encode character u'\xed' in position 4: ordinal not in range(128)
```

I don't have a usable toolkit environment configured, so anybody is free to fix this if they can/want. I guess translate/storage/poheader.py::parseheaderstring() line 52 the `str(key.strip())` could probably just be without the str(), but we'll have to check the tests. Also, I think in some places header dictionaries might be passed as **kwargs, and non-ascii values might not work in Python 2, so I'm not sure it is a trivial change.

**Comment by nijel** [comment]
Your suggested fix seems to work well, **kwargs works fine with unicode keys in Python 2.7, so it looks safe. See https://github.com/translate/translate/pull/3897
