### ISSUE TITLE
Qt Linguist translations since Qt 5 now uses type="vanished" instead of type="obsolete"

### ISSUE THREAD

**Issue by Wohlstand** [translate/translate#3901]
Qt Linguist's TS parser lacks the support for `type="vanished"` which is the same as `type="obsolete"` since Qt 5. Both are meaning the same.

**Little about Qt 5 and Qt 4 TS differences**: they are similar to each other, however, there are some differences between each other:
* `<message>` tag no more uses `utf8="true"` tag, the codepage is always UTF8 or specified in the header of entire TS file.
* Version of TS is 2.1 on Qt 5 while 2.0 on Qt 4
* Vanished messages are now marking with `type="vanished"` in Qt 5 and `type="obsolete"` in Qt 4. However, Qt 4's "obsolete" is still work on Qt Linguist of Qt 5, but no more coming by default.

An example TS file which contains "vanished" translations: https://github.com/Wohlstand/OPL3BankEditor/blob/master/src/translations/opl3bankeditor_fr_FR.ts

**Comment by Wohlstand** [comment]
I have made a small change that adds the support for "vanished" type to work the same as "obsolete".

**Comment by Wohlstand** [comment]
As this has been implemented and merged, so, this issue has been solved!

**Comment by ossilator** [comment]
the analysis behind this report is incorrect: 'vanished' didn't replace 'obsolete'; rather, one complements 'unfinished' and the other 'finished'/default (i don't remember which way around). i implemented this specifically to mirror .po's 'obsolete fuzzies'.

**Comment by Adama-WADE** [comment]
From what I observed after running a few tests, "obsolete" is assigned when a message with a translation that hadn't been validated yet is removed, whereas "vanished" is assigned when the translation of the deleted message had been validated. Both show up in Qt 5.

**Comment by nijel** [comment]
I still don't see an issue with the implementation in https://github.com/translate/translate/pull/3902. If you think something should be changed, please open a separate issue describing how it should behave.

**Comment by ossilator** [comment]
i didn't check the current state of affairs, but the original PR treats vanished and obsolete identically, which is just wrong and doesn't map to the full capabilities of the po format.

**Comment by ossilator** [comment]
prospectively, you might want to use this information when seeding translation memory with these strings.

anyway, as long as you're not falsifying the state info when writing back modified files, everything is fine.
