### ISSUE TITLE
Android xml parsing fails if it contains an Entity

### ISSUE THREAD

**Issue by Viish** [translate/translate#3907]
I'm using WeblateOrg and I encountered an issue I reported on their project: https://github.com/WeblateOrg/weblate/issues/2843

From what they said, the problem comes from your library.
I try to use an Entity in a Doctype (see below image)
![Screenshot_20190628_161758](https://user-images.githubusercontent.com/1561996/60418689-de3e0a00-9be3-11e9-814d-8291ea8767b7.png)
and the error I get is 
`app/src/main/res/values/strings.xml | attribute 'text' of 'lxml.etree._Entity' objects is not writable`

You can try on the `app/src/main/res/values/strings.xml` file in the `feature/trying_to_use_entity_in_resources` branch of https://github.com/BelledonneCommunications/linphone-android repository 

Thanks in advance.

**Comment by Viish** [comment]
Hi,
I just tried with version 3.9.1 (fresh install) and there is still an issue regarding this.
File are correctly imported but export is broken, I attached exported french traduction along with expected file.
[linphone-linphone-android-fr-expected.log](https://github.com/translate/translate/files/3916005/linphone-linphone-android-fr-expected.log)
[linphone-linphone-android-fr-got.log](https://github.com/translate/translate/files/3916006/linphone-linphone-android-fr-got.log)

Also there are a lot of alerts:
```
app/src/main/res/values-ar/strings.xml | attribute 'text' of 'lxml.etree._Entity' objects is not writable

app/src/main/res/values-de/strings.xml | attribute 'text' of 'lxml.etree._Entity' objects is not writable

app/src/main/res/values-es/strings.xml | attribute 'text' of 'lxml.etree._Entity' objects is not writable

app/src/main/res/values-fi/strings.xml | attribute 'text' of 'lxml.etree._Entity' objects is not writable

app/src/main/res/values-fr/strings.xml | attribute 'text' of 'lxml.etree._Entity' objects is not writable

app/src/main/res/values-it/strings.xml | attribute 'text' of 'lxml.etree._Entity' objects is not writable

app/src/main/res/values-iw/strings.xml | attribute 'text' of 'lxml.etree._Entity' objects is not writable

app/src/main/res/values-ja/strings.xml | attribute 'text' of 'lxml.etree._Entity' objects is not writable

app/src/main/res/values-ka/strings.xml | attribute 'text' of 'lxml.etree._Entity' objects is not writable

app/src/main/res/values-nl/strings.xml | attribute 'text' of 'lxml.etree._Entity' objects is not writable

app/src/main/res/values-pl/strings.xml | attribute 'text' of 'lxml.etree._Entity' objects is not writable

app/src/main/res/values-pt-rBR/strings.xml | attribute 'text' of 'lxml.etree._Entity' objects is not writable

app/src/main/res/values-ru/strings.xml | attribute 'text' of 'lxml.etree._Entity' objects is not writable

app/src/main/res/values-sr/strings.xml | attribute 'text' of 'lxml.etree._Entity' objects is not writable

app/src/main/res/values-sv/strings.xml | attribute 'text' of 'lxml.etree._Entity' objects is not writable

app/src/main/res/values-tr/strings.xml | attribute 'text' of 'lxml.etree._Entity' objects is not writable

app/src/main/res/values-uk/strings.xml | attribute 'text' of 'lxml.etree._Entity' objects is not writable

app/src/main/res/values-zh-rCN/strings.xml | attribute 'text' of 'lxml.etree._Entity' objects is not writable

app/src/main/res/values-zh-rTW/strings.xml | attribute 'text' of 'lxml.etree._Entity' objects is not writable

app/src/main/res/values/strings.xml | attribute 'text' of 'lxml.etree._Entity' objects is not writable
```

**Comment by Viish** [comment]
I made a few changes to my test branch and it is even worse: it finds the translations but now they are empty (both source file in English and translated file in French) with the same error:
```
Weblate n’a pas pu analyser les fichiers de traduction lors de la mise à jour du dépôt.

Les occurrences suivantes ont été trouvées :

Nom de fichier | Erreur

-- | --
app/src/main/res/values-fr/strings.xml | attribute 'text' of 'lxml.etree._Entity' objects is not writable
app/src/main/res/values/strings.xml | attribute 'text' of 'lxml.etree._Entity' objects is not writable
```

**Comment by nijel** [comment]
It's fixed by https://github.com/translate/translate/commit/09f05f0edd5c28cd5dd78f6c4cdb518d8dd7c462 which is not yet part of any release. To get the fix you need to install from git, for example: `pip install https://github.com/translate/translate/archive/master.zip`

**Comment by Viish** [comment]
Indeed with the master version of translate it works fine, thanks a lot !
I'll now be able to install it in production :)

**Comment by Viish** [comment]
It also triggers check-end-semicolon and check-punctuation-spacing verifications.

**Comment by nijel** [comment]
@Viish that's offtopic here, I've created issue on Weblate for that: https://github.com/WeblateOrg/weblate/issues/3268

**Comment by Viish** [comment]
OK, thanks.
