### ISSUE TITLE
Support ARB files

### ISSUE THREAD

**Issue by 12people** [translate/translate#3910]
I'm developing an app using Flutter and using the [.arb file format](https://github.com/google/app-resource-bundle/wiki/ApplicationResourceBundleSpecification), as per the [official Flutter documentation](https://flutter.dev/docs/development/accessibility-and-localization/internationalization#appendix-using-the-dart-intl-tools).

Please add support for .arb resource files. ARB is based on JSON and should therefore be relatively simple to implement.

(Note that the specification confusingly adds "arb.register("arb_ref_app", {" to its ARB example. However, actual ARB resource files are pure JSON, as noted later in the spec: "It is very convenient and light-weight to reference resource from JavaScript code. JSON format is derived from JavaScript, and ARB is represented in JSON.")

**Comment by orestesgaolin** [comment]
I would love to see support of ARB files. Flutter is getting more and more popular and there are only two commercial tools that support ARB (Localizely and Crowdin).

**Comment by wilkomanger** [comment]
Would love to see this!

**Comment by nijel** [comment]
PR for this is here: https://github.com/translate/translate/pull/4040
