### ISSUE TITLE
Release 3.4.1?

### ISSUE THREAD

**Issue by nijel** [translate/translate#3933]
I think master branch contains [enough fixes](https://github.com/translate/translate/compare/2.4.0...master) to make new release useful.

From open pull requests, I'd like to see https://github.com/translate/translate/pull/3931 in as well.

@unho any plans on the release?

**Comment by unho** [comment]
I will try to do as soon as I can, maybe this weekend.

**Comment by nijel** [comment]
Thanks!

**Comment by ilocit** [comment]
Thanks to all also from my side! Awesome.

**Comment by unho** [comment]
I have released 2.5.0 instead.
