### ISSUE TITLE
Markdown as a native source format

### ISSUE THREAD

**Issue by eighthave** [translate/translate#3956]
Markdown is a widely popular markup format for documentation and websites.  If translation tools can directly support it, this opens up a lot of possibilties for a really smooth user experience for both translators and developers/webmasters.  Some platforms like [Transifex](https://docs.transifex.com/formats/markdown) have naive support for Markdown where it breaks down by paragraph more or less.  This is a very limited approach.

For f-droid.org, we have been using [po4a](https://github.com/mquinson/po4a) which is a perl program that parses Markdown into _gettext_ PO files.  That has proven that parsing Markdown for translation can work.  But its approach is limited because it is basically a collection of regexps, and ignores large parts of the Markdown spec.  Here are some specific examples of things that are handled:
* https://github.com/mquinson/po4a/issues/195
* https://github.com/mquinson/po4a/issues/194

You can see that in action here: https://hosted.weblate.org/projects/f-droid/website-docs/

@uniqx and I have discussed some ideas with @nijel about how to handle Markdown well in the translation workflow.  It seems clear that it will be worthwhile to use a complete Markdown parser so that the translation workflow can usefully break the documents into strings to be translated, and back.  Then this will also enable syntax checkers directly in the user interface, and things like checking whether the links are working in the translation.

It seems to me the ideal would be having _docs/MyDoc.md_ be the source file, and the _docs/<LANG>/MyDoc.md_ be the translation file.  For projects that want to translate the document title, then the filename could be a key, e.g. _docs/my-doc.md_ and the title would be in the document:

_docs/my-docs.md_
```markdown

# My Document

```
_docs/de/my-docs.md_
```markdown

# Mein Dokument

```

There is also a widely used extension to Markdown known as [YAML Front Matter](https://jekyllrb.com/docs/front-matter/).  This should also be directly supported, and looks easy to do.  I've outlined how that can be supported here https://github.com/mquinson/po4a/issues/196

**Comment by nijel** [comment]
There is existing [text storage](https://github.com/translate/translate/blob/master/translate/storage/txt.py), but it's probably better to start from scratch for Markdown as it is quite simple.

**Comment by eighthave** [comment]
Seems to me that it will pay off in the long run to have a proper
parsing setup that fully understands Markdown.  That will handle the
vast amount of edge cases that will likely happen here, when you
consider things like inline HTML, ## vs --------- titles, tables, and more.

Seems to me that full parsing will allow for some of the nice gettext
merging tricks in a way that collections of pattern matching will not.
If there is an abstract syntax tree representation, then the strings can
be extracted and reinserted based on their position in that tree.  So
that would give some kind of "key" in addition to source and transaltion.

**Comment by RMStoica-zivver** [comment]
@eighthave as far as I understand there are a number of parsers already written, maybe one of them could be used as such?

**Comment by eighthave** [comment]
yeah, we'd want to use an existing markdown parser, if possible.

**Comment by mquinson** [comment]
I'm jumping into this discussion as the current author/maintainer of po4a. From my experience, it's almost impossible to reuse an existing parser because none of these things expose the AST of the document that you could work on to translate it. In po4a, we have what we call [transtractors](https://po4a.org/man/man3/Locale::Po4a::TransTractor.3pm.php) that are both document translators and string extractors at the same time. They simply parse the input file, and push content to the output file. The structure is preserved while the content is translated on the fly. But I will stop paraphrasing our doc here. Please just have a look at it for more info. Or feel free to ask ;)

Oh, and yes. A python version of po4a would be helpful to increase the pool of potential contributors. But beware, po4a is well over 10k lines (of perl). It can be used to translate something like 95% of any man page written in groff, we have a full support of AsciiDoc, HTML, POD (perl doc), and some other formats. This is large, even if none of this is fundamentally complex. I agree with the description portraying po4a as a huge bag of regular expressions, but I cannot think of a better way of dealing with this issue.

And finally, even if that's perfectly out of scope here, I am willing to provide a full support of Markdown in po4a, provided that the relevant bugs are reported ;) But still. I'd welcome a python version of this thing.

**Comment by eighthave** [comment]
thansk for your feedback!  I agree that getting access to the AST is
essential.  Some quick reading of some Python Markdown libraries seem to
show that they first parse to an AST instance, then that AST can be
separately rendered.

* https://github.com/miyuchina/mistletoe
* https://pypi.org/project/commonmark

But using CommonMark could be annoying, since it seems to be more
pedantic than GitHub Markdown:

https://help.apiary.io/faq/commonmark/

Though according to GitHub, GitHub-Flavored Markdown is purely an
extension of CommonMark, it doesn't deviate from the spec.  So that's
good news.  There is also some good discussion about the AST:

https://github.blog/2017-03-14-a-formal-spec-for-github-markdown/

**Comment by mquinson** [comment]
I spent the last 2 weeks working on po4a to revive it after almost a decade of slow maintenance, and I'd really love to contribute to an effort attempting to do the same kind of project in Python: a generic framework to parse various format, extracting the content strings and injecting translations in place in the document structure, on top of which one could write specific parsers for each format. translate is a good candidate in the sense that there is many format2po parsers, but I fail to find in the source code the generic framework shared among parsers. Could you please point me to the right location?
Thx

**Comment by nijel** [comment]
There isn't much shared logic right now each storage is responsible for parsing the file to produce list of units which have some form of ID (which is currently string, what fails in case more complex structure is being parsed, see https://github.com/translate/translate/issues/3857 and https://github.com/translate/translate/issues/3819) and later it can serialize it back to the format. Some storages share logic (for example XML based ones), but that's not much. The convertors AFAIK still contain quite a lot of ad-hoc code to deal with the formats conversion (see also https://github.com/translate/translate/issues/3573).

**Comment by wetneb** [comment]
Although my bounty is on https://github.com/WeblateOrg/weblate/issues/3106, solving this issue would of course deserve a share of the bounty (I think Bountysource supports that).

**Comment by eighthave** [comment]
I think the work @mquinson has done on _po4a_ will serve as a great testbed and model for the Python work.  I've tried to map out some of the issues in this blog post:
https://guardianproject.info/2020/04/23/figuring-out-crowdsourced-translation-of-websites/

**Comment by anderskaplan** [comment]
Hi all, I agree with @eighthave that edge cases become much easier to handle if the underlying parser has an understanding of the format, i.e., is not only doing regexp matching. I have worked on the html parsing and converters for the Translate Toolkit, replacing a regexp based strategy with one based on the dom tree, for exactly this reason. (By the way, from what @mquinson describes, it seems like po4a and the Translate Toolkit extract translatable content and insert translated content in a very similar way. At least for html.)

Markdown may look simple but I’d argue it’s actually fairly complicated. It requires two-pass parsing to figure out what is what in a robust way, and it allows embedding of arbitrary html. On top of that, there are many flavors of markdown with different extensions, although this is getting better with the introduction of the Commonmark standard.

I did a quick test with one of the standard-compliant Python parsers, commonmark.py. The intention was to see if I could get a quick markdown-to-ast-to-markdown roundtrip working. But unfortunately, the ast does not have all the information required for a clean roundtrip. After all, it was built for a different purpose so it’s not so surprising. I checked two more parsers and it seems to be the same there. Again no surprise, as they are all modeled on the same javascript reference implementation. So I’m afraid a new or at least a customized parser will be necessary.

I might be able to find some time to work on this (and I'd be happy to collaborate). But the key question to be able to move forward would be: which content in the markdown should be extracted for translation? In many cases it’s obvious:  paragraphs of text, headings, block quotes, list items, text in table cells, for example. Thematic breaks should clearly be ignored.

code blocks -- I’d argue it’s best to leave them alone, i.e., not extract them for translation. But there could be cases where you want to do that. It could be optional.

html blocks -- This can get very complicated depending on the ambition level. I think it would be reasonable to only extract text nodes. This should be a fairly small limitation as long as embedded formatting, links, and images use markdown formatting (and so are included with the text). What do you think?

yaml front matter -- Is there anything in it that should be extracted for translation, or can it just be ignored?

**Comment by ilmari-lauhakangas** [comment]
Anders: Martin and I have been onboarding a developer. Nothing has been written yet, so I didn't talk about it. If you email me at ilmari.lauhakangas@libreoffice.org we can figure out a way to collaborate.

**Comment by anderskaplan** [comment]
Update: The best approach seems to be to use a proper Markdown parser.

There are quite a few to choose from. But, none of the Markdown parsers I could find was capable of doing a clean markdown-to-ast-to-markdown roundtrip, as needed in this case. Therefore I've started to add that capability to one of them, called mistletoe. A [draft pull request](https://github.com/miyuchina/mistletoe/pull/162) is submitted to demonstrate the concept.

**Comment by eighthave** [comment]
Did you look at commonmark?  That's what lots of big platforms are using, like 
GitHub and GitLab, so that level of compatibility and support would be nice to 
tap into.

**Comment by anderskaplan** [comment]
Yes, I did look at several parsers with some criteria in mind: pure python, compact and extensible codebase, CommonMark standard compliant, and a permissive license. mistletoe seemed to be the best match. It's not 100% compliant to the latest CommonMark standard yet, but it's getting there.

**Comment by ilmari-lauhakangas** [comment]
> Just discovered https://github.com/TkTech/humanmark which presumably can do round-trip. The maintenance status is questionable though (alpha with no release for a year).

But did you test that it is "capable of doing a clean markdown-to-ast-to-markdown roundtrip" as anderskaplan said none of the parsers could do at the time? Anders's PR seems close to be accepted into mistletoe.

**Comment by anderskaplan** [comment]
I have the translation code mostly written for mistletoe, so as soon as that PR makes into a release, I'll be able to post a PR here as well.

**Comment by nijel** [comment]
That sounds great!

**Comment by TkTech** [comment]
> Just discovered https://github.com/TkTech/humanmark which presumably can do round-trip. The maintenance status is questionable though (alpha with no release for a year).

It's maintained :) It works for all my current use cases so I simply haven't added anything to it. It should be able to round-trip, although it may "optimize" whitespace and links. Rendered documents will be identical. I use it for doing things like adding automatic benchmark results into repository READMEs (https://github.com/TkTech/json_benchmark/blob/main/generate_benchmark_summaries.py).

It's purpose-built for tasks where humans want to navigate, create, and edit an AST, so it may be a good fit for your use case. The backend engine is https://github.com/executablebooks/markdown-it-py, which you may want to look into instead of mistletoe even if you decide not to use HumanMark. It's fully CommonMark-compliant, and has plugins for many, many of the common extensions like Latex.

If you end up giving it a try and find an issue, just let me know :)

**Comment by eighthave** [comment]
Sounds promising. Can the optimizing of whitespace and links be disabled?  One 
pain point in this whole process of maintaining translations in git is merge 
conflicts.  Whitespace changes would be a source of merge conflicts between 
upstream projects and translations.

**Comment by TkTech** [comment]
@anderskaplan Mind if I copy the tests you added to mistletoe? Seems the easiest way to ensure it's doing what is wanted here.

Are there any realistic test documents?

**Comment by anderskaplan** [comment]
> @anderskaplan Mind if I copy the tests you added to mistletoe? Seems the easiest way to ensure it's doing what is wanted here.
> 
> Are there any realistic test documents?

Sure, just go ahead and copy them! If this can lead to some sort of standardization, then all the better.

**Comment by anderskaplan** [comment]
> Sounds promising. Can the optimizing of whitespace and links be disabled? One pain point in this whole process of maintaining translations in git is merge conflicts. Whitespace changes would be a source of merge conflicts between upstream projects and translations.

One thing I just realized when re-reading this thread is the suggestion to use one markdown file as the reference language and one as the translated content. That's not really in line with how the translate tools work -- you'd typically have one markdown file as the reference, then parse that to generate a gettext PO(T) file, then make the translation as a second PO file, and finally generate the translated markdown file from the reference markdown + translation PO. This is described more in detail in #4725 .

That said, the gettext PO file should be generated in the same way every time. I'm aware that PO merging and editing tools may sometimes reflow the text and possibly also reorder entries, which could clearly create git merging problems. However, that's not unique to markdown.

**Comment by yarons** [comment]
Wow! This is awesome! Can't wait to see this feature in Weblate!
Btw, it might need some structural UI changes to work in WYSIWYG mode 😄
Thank you so much for this!
