### ISSUE TITLE
SyntaxWarning: "is" with a literal. Did you mean "=="? in /usr/lib/python3/dist-packages/translate/convert/prop2po.py

### ISSUE THREAD

**Issue by shirishag75** [translate/translate#3957]
Dear all, 

I was updating my packages today and got the following - 

```
Setting up python3-translate (2.5.0-2) ...
/usr/lib/python3/dist-packages/translate/convert/prop2po.py:73: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if pounit is "discard":
/usr/lib/python3/dist-packages/translate/convert/prop2po.py:119: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if origpo is "discard":
/usr/lib/python3/dist-packages/translate/convert/prop2po.py:137: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if translatedpo is "discard":
```

The same/similar issue had ocurred in python3-twisted too which they fixed via https://github.com/twisted/twisted/commit/de05fee07a39d3415e4a3e9738d141b43b54f95c

Now I don't know if it's the same issue or if the fix is as straight as the one shared, but maybe you can look at it . 

You can see the relevant lines https://salsa.debian.org/l10n-team/translate-toolkit/-/blob/master/translate/convert/prop2po.py 

The fix does seem straightforward, maybe if you did then it will be easy for downstream to implement it.

**Comment by julen** [comment]
Hi @shirishag75, thanks for bringing that up. The affected code was actually refactored recently in ba38b44, so this is now a non-issue, and hence I'm closing the ticket.
