### ISSUE TITLE
setup.py fails with py2exe

### ISSUE THREAD

**Issue by a1s** [translate/translate#3958]
I've got this error from setup.py:

```
Traceback (most recent call last):
  File "setup.py", line 526, in <module>
    standardsetup("translate-toolkit", translateversion)
  File "setup.py", line 486, in standardsetup
    translatebashscripts)
  File "setup.py", line 490, in dosetup
    from setuptools import setup
  File "C:\Python27\lib\site-packages\setuptools\__init__.py", line 20, in <module>
    from setuptools.dist import Distribution, Feature
  File "C:\Python27\lib\site-packages\setuptools\dist.py", line 336, in <module>
    _Distribution = get_unpatched(distutils.core.Distribution)
  File "C:\Python27\lib\site-packages\setuptools\monkey.py", line 44, in get_unpatched
    return lookup(item)
  File "C:\Python27\lib\site-packages\setuptools\monkey.py", line 61, in get_unpatched_class
    raise AssertionError(msg)
AssertionError: distutils has already been patched by <class py2exe.Distribution at 0x047BBF48>
```

**Comment by a1s** [comment]
This helps: https://stackoverflow.com/a/45133496

**Comment by nijel** [comment]
I've tried to do that simple change you've suggested, but apparently the py2exe integration is broken way more, so I give up. See https://github.com/translate/translate/pull/3959

**Comment by a1s** [comment]
As far as I understand, what is there now was made for Python2.  Python3 is different.

If there are no plans to get py2exe working with Python3, the whole block could be put under
`if sys.version_info()[0] < 3:`

I have checked out the [nijel:setup-py2exe](https://github.com/nijel/translate/tree/setup-py2exe) branch, and both `bdist_wininst` and `py2exe` commands work without errors in Python2, provided that I revert the changes made to `BuildCommand` and `Distribution` - that's lines 190 and 191.

**Comment by nijel** [comment]
I have exactly zero knowledge of py2exe and I tried to make it work with all supported versions. For Python 2, the compatible py2exe version is even not available in pypi.org. Feel free to pickup where I stopped and make it work at least for Python 2, but I'm not really interested in working on Python 2 only solution.

**Comment by a1s** [comment]
py2exe compatible with Python2 indeed is on PyPI: https://pypi.org/project/py2exe/0.6.9/

**Comment by nijel** [comment]
The release is there, but it has no files attached, so `pip install py2exe==0.6.9` cannot work.

**Comment by a1s** [comment]
Thank you for your assistance!  (And thank you very much for the **Translate Toolkit**!)

I'm very uncomfortable with git, but I'll try to find how to submit your e2ffdefd4ba40e0007dc0db3dea239608d00621e to the master branch.

**Comment by nijel** [comment]
Does https://github.com/translate/translate/commit/e2ffdefd4ba40e0007dc0db3dea239608d00621e really fix something? I can land it there, I just wanted to have it tested and that failed (see above).

**Comment by a1s** [comment]
Yes, e2ffdefd4ba40e0007dc0db3dea239608d00621e does fix the error.  Thank you!

As for py2exe download, this works:

```
pip2 install https://sourceforge.net/projects/py2exe/files/py2exe/0.6.9/py2exe-0.6.9.zip/download
```
