### ISSUE TITLE
FR: Allow JSON output whitespace to be configurable/overridden

### ISSUE THREAD

**Issue by sigginet** [translate/translate#3972]
In https://github.com/translate/translate/blob/cbc36ad/translate/storage/jsonl10n.py#L155 the whitespace indentation is hardcoded.
This is causing some conflicts for us when translating in Weblate since our JSON files have 2 spaces for indentation (why isn't TAB a friggin standard?).

I can fix that by:
1. Adding a pre-commit hook that fixes whitespaces in all JSON files to 2 spaces in all components (it won't be maintainable)
2. Modifying Weblate to rebase with -Xignore-space-change (yuck)
3. Asking for a new feature here (best option)

It would be great if we could override the base dump parameters somehow to adjust to each environment.
It would be even better if Weblate / translate would autodetect and store the indentation, tab, spaces and how many there are.

I'll start with a pre-commit hook since that's the cleanest way to fix things for now, but I won't be able to maintain it since we add more and more components each month.

**Comment by sigginet** [comment]
For anyone else who might be interested in this in the future, here's the pre-commit script:
You need to add it in `.git/hooks/pre-commit` and make it executable
```bash
#!/bin/bash
# The formatter to use
formatter=`which jq`

# Check availability of the formatter
if [ -z "$formatter" ]
then
  1>&2 echo "$formatter not found. Pre-commit formatting will not be done."
  exit 0
fi

# Format staged files
for file in `git diff --cached --name-only --diff-filter=ACMR | grep "\.json$"`
do
  echo "Formatting $file"
  # Format it
  "$formatter" '.' --indent 2 "$file" > "$file.tmp"
  rm "$file"
  mv "$file.tmp" "$file"
  # Add it back to index
  git add "$file"
done

# If no files left in index after formatting - fail
ret=0
if [ ! "`git diff --cached --name-only`" ]; then
  1>&2 echo "No files left after formatting"
  exit 1
fi
```

**Comment by sigginet** [comment]
@nijel you might be interested in this

**Comment by nijel** [comment]
The indentation can be already configured in both translate-toolkit and Weblate (using https://docs.weblate.org/en/latest/admin/addons.html#customize-json-output).
