### ISSUE TITLE
FR: Allow custom key separators for JSON keys

### ISSUE THREAD

**Issue by sigginet** [translate/translate#3976]
We're facing issues with periods being recognized as separators in our JSON files, but they aren't in our case.

We're using i18next with ICU, so we just write the whole sentence as the key, so we know what to expect in the code.

Given this input file:
```JSON
{
  "Whoops! We are terribly sorry. We are unable to get information on this attraction.": "Oups ! Nous sommes vraiment désolés. Nous n'avons pas pu récupérer les informations sur ce lieu d'intérêt"
}
```

When we run it through translate (Weblate), it returns this output file:
```JSON
{
  "Whoops! We are terribly sorry": {
    " We are unable to get information on this attraction": {
      "": "Oups ! Nous sommes vraiment désolés. Nous n'avons pas pu récupérer les informations sur ce lieu d'intérêt"
    }
  }
}
```

That's just awful and requires rework before we merge the translations in the code.

Can you offer a custom key separator for JSON keys (or even the ability to turn them off)?
Then we would be able to have a simple 2D JSON structure in the output.

Example code to fix:
https://github.com/translate/translate/blob/cbc36ad/translate/storage/jsonl10n.py#L332

**Comment by sigginet** [comment]
@nijel - you might be interested in this as well

**Comment by nijel** [comment]
This is basically different incarnation of https://github.com/translate/translate/issues/3857. See https://github.com/translate/translate/issues/3819 for detailed explanation.

In case you are not using nesting at all, choose "JSON file" instead of "JSON nested structure file" in Weblate.

**Comment by sigginet** [comment]
OK, some of our translators have already done work with these components.
@nijel can I just change the component now, or do I have to delete the components and re-import them?

**Comment by nijel** [comment]
It should be possible to change that, but make sure that everything is commited prior doing so in case something goes wrong.

**Comment by sigginet** [comment]
I'll do my best :) Thanks @nijel
