### ISSUE TITLE
Conditional imports

### ISSUE THREAD

**Issue by nijel** [translate/translate#4004]
Right now translate-toolkit doesn't have any requirements (the only one was six and that was dropped for the 3.0 release). There are two levels of deps - recommended and optional.

The code sometimes tries to deal with missing deps by catching `ImportError`, but in many cases it is not (for example lxml imports are not guarded in many cases).

I think this would use some cleanups and revisiting:

* Maybe we should make some "recommended" ones required (lxml comes to my mind).
* Merge "recommended" and "optional" to one list.
* Properly expose these in `setup.py` as `extras_require` so that it's possible to depend on that (for example `translate-toolkit[PHP]` to get PHP support)
  * https://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies

**Comment by unho** [comment]
I fully agree. Anyway I am thinking that it would be great to have some option to get all the dependencies instead of having to install them one by one.

**Comment by nijel** [comment]
I don't think that pip itself can do it, but the list can be generated in setup.py based on the requirements files and it can include something like "full" option having all extras.

**Comment by unho** [comment]
That's what I was suggesting.

**Comment by unho** [comment]
@nijel I don't think this issue is still addressed.

**Comment by nijel** [comment]
What do you think is missing? The optional deps can be specified since https://github.com/translate/translate/pull/4026, there is also option to do `translate-toolkit[recommended]` or `translate-toolkit[all]`.

**Comment by unho** [comment]
Installing using `translate-toolkit[PHP]` (which I can live without) or the merge of recommended and optional requirements are things mentioned in the first comment on this issue.

**Comment by nijel** [comment]
`translate-toolkit[PHP]` should work since #4026

**Comment by unho** [comment]
Sure. Sorry!

**Comment by nijel** [comment]
As for recommended/optional, I think it kind of makes sense, that's why I didn't change this in the end. I can merge these if you think it's better.

**Comment by unho** [comment]
I think it will be less confusing to have them merged.

**Comment by phlax** [comment]
hi - not sure how helpful this is - but seems worth mentioning...

> The code sometimes tries to deal with missing deps by catching ImportError

When i was profiling pootle/ttk i noticed that these imports were causing a lot of diskio and degrading performance. Not sure if this is still the case, or what the impact was exactly

**Comment by nijel** [comment]
@phlax I guess you talk about https://github.com/translate/translate/pull/3492, I unfortunately didn't get to review that, but I want to take a look.

@unho Okay, I've merged them in https://github.com/translate/translate/pull/4063

**Comment by phlax** [comment]
@nijel - yep - not sure that my hack was the best approach tho - it was more for comparisons
