### ISSUE TITLE
Find more reliable replacement for chardet

### ISSUE THREAD

**Issue by nijel** [translate/translate#4039]
I'd like to get some feedback before spending more time on this :-)

Chardet is not maintained and is broken for some UTF-8 files with emoji, see https://github.com/chardet/chardet/issues/148.

[Charamel](https://github.com/chomechome/charamel) is new library which seems to provide better accuracy. The downside is that constructing the detector is slow (it loads quite many data from the gzip compressed files). For long-running services this can be mitigated by sharing single detector instance, but for single action scripts the delay will be noticeable (around 1 second).

**Comment by unho** [comment]
Looks like they started Charamel 30 days ago. I'd say look if there are other alternatives.

**Comment by nijel** [comment]
Yes, that seems quite recent. I also don't like the startup times, but I didn't quickly find anything else.

**Comment by nijel** [comment]
Few months later: I've given up on charamel in language-finder as it consumes huge amount of memory and for our purposes we can replace it with few lines of code to detect Unicode encodings we need to detect: https://github.com/WeblateOrg/translation-finder/blob/master/translation_finder/chardet.py

Anyway, it would be good to find a suitable replacement for chardet to avoids utf-8 detection problems. Maybe https://github.com/PyYoshi/cChardet could be a way to go...

**Comment by nijel** [comment]
As chardet is now alive (see https://github.com/translate/translate/pull/4201), I think we can stay with it for now and hope that the issues with it will be addressed.
