### ISSUE TITLE
3.0.0 release

### ISSUE THREAD

**Issue by nijel** [translate/translate#4048]
I'd like to release 3.0.0 soon to get cleanups and fixes to users.

Any objections to doing that once remaining issues in the milestone https://github.com/translate/translate/milestone/25 are addressed?

**Comment by unho** [comment]
No objection.

**Comment by nijel** [comment]
@unho Any opinion on lxml dependency? Basically whether #4035 or #4002 should be merged...

**Comment by unho** [comment]
@nijel Didn't notice it was either one or another... Reviewing.

**Comment by unho** [comment]
@nijel I would go with making lxml required since it is required by several formats that might be considered core formats.

**Comment by nijel** [comment]
I wanted to release now, but it seems that Read the Docs is having some issues and I can't build the docs because http://docs.translatehouse.org is not working. Let's see when they will fix the service...

**Comment by nijel** [comment]
It is now out.
