### ISSUE TITLE
rc2po: rc file grammar doesn't handle concatenating adjacent strings

### ISSUE THREAD

**Issue by jon-turney** [translate/translate#4105]
e.g.

```
STRINGTABLE
BEGIN
    IDS_ADJACENT_STRINGS    "Line1\n"
                            "Line2"
END
```

This can't be parsed by rc2po.  The adjacent strings should be concatenated (as per C).

See https://docs.microsoft.com/en-us/windows/win32/menurc/stringtable-resource, which specifies the syntax as 'stringID string'  where 'string' is defined as 'One or more strings, enclosed in quotation marks'.

**Comment by nijel** [comment]
Should be fixed by https://github.com/translate/translate/pull/4106

**Comment by jon-turney** [comment]
Confirming this fix. Thanks!
