### ISSUE TITLE
Broken readthedocs.org integration

### ISSUE THREAD

**Issue by nijel** [translate/translate#4228]
The readthedocs.org integration lacks some permissions, and I'm unable to fix that. It might need something on the organization level, what I can't control.

* It fails to set build status, what would be really handy on pull request builds (it publishes pull request docs to a temporary URL)
* The webhook sync from the rtd.org fails (I hoped that this might address the issue above)

![image](https://user-images.githubusercontent.com/212189/103479355-7581b000-4dcd-11eb-9a9c-52a10c419c7a.png)

Looking at Weblate, we have Read the Docs Community (readthedocs.org) approved in Third-party access. That should be on 
https://github.com/organizations/translate/settings/oauth_application_policy for translate org. Can somebody from @translate/house check this?

**Comment by rffontenelle** [comment]
@nijel I have access to organizations/transate. I don't see any mention of rtd.org in "Third-party access". Also there is no hook in Webhook section, which should have according to ([Incoming Webhooks and Automation](https://docs.readthedocs.io/en/stable/webhooks.html#github)) section in rtd page. Let me know if you want me to add it.

**Comment by nijel** [comment]
The hook is there on translate/translate (where I can add or edit it manually) and that works fine for triggering the build for both pushes and pull requests.

What doesn't work is updating the commit status using checks API and I can't trigger automatic hook sync on rtd.org (fails for me with "Webhook activation failed. Make sure you have the necessary permissions.").

I've now found way to request adding rtd.org OAuth app what should fix this. The approval should be on the page I've mentioned previously...

**Comment by rffontenelle** [comment]
Request approved, access granted. Please see if it works now.

**Comment by nijel** [comment]
Thanks! The sync now works and the pull request status is also being updated: https://github.com/translate/translate/pull/4227
