### ISSUE TITLE
XWiki Page Properties format does not handle correctly source edition

### ISSUE THREAD

**Issue by surli** [translate/translate#4265]
As explained in https://dev.xwiki.org/xwiki/bin/view/Community/XWiki%20Translations%20Formats/#HFileFormat: 
>  source translation files need to contain a XWiki.TranslationDocumentClass xobject as documented in Localization Extension

Right now editing the source file translation has the effect to remove this special class. You can see the result when using this format on Weblate here: https://github.com/xwiki-contrib/application-activitypub/pull/22/files#diff-0134e6af64b31dc0fc0e04d39cece9438a0cc36b411b5f474aee2f90ff5e162cL113

**Comment by surli** [comment]
@nijel I'm working on a fix, it's not very difficult but I need to detect if a translation file is a source file. Do you know if there's such API or an easy way to check this in TranslationStore class? Is it safe to perform a comparison between sourcelanguage and targetlanguage here?

**Comment by nijel** [comment]
I'm not convinced if these are properly set, but it's definitely worth trying.

**Comment by surli** [comment]
> I'm not convinced if these are properly set, but it's definitely worth trying.
PS: In case these are not set, Weblate might be fixed to do that properly.

for info I hotpatched our weblate server with the fix I provided and it's enough to fix the issue in weblate, so apparently everything's properly set here.
