### ISSUE TITLE
Cannot parse XLF files bigger than about 32MB

### ISSUE THREAD

**Issue by mclei-asw** [translate/translate#4302]
Cannot parse XLF files bigger than about 32MB.

Used in Weblate versions from 3.10 to 4.5.1

**I already tried**

Searched for the problem and found, that it is a limitation of lxml, which could be bypassed by specifying huge_tree=True when creating the XML parser. But there could be some security implications.

**To Reproduce the issue**

Steps to reproduce the behavior: Use XLF file larger than 32MB.

**Error messages caught by Weblate**

WARNING Translation parse error: XMLSyntaxError: internal error: Huge input lookup, line 379625, column 1 (, line 379625)
WARNING Failed to parse file on commit: FileParseError: internal error: Huge input lookup, line 379625, column 1 (, line 379625)
ERROR project/xxxxx/cs: skipping commit due to error: internal error: Huge input lookup, line 379625, column 1 (, line 379625)

Originally it was reported to Weblate (https://github.com/WeblateOrg/weblate/issues/5720#issuecomment-804102182), but in fact, it is problem in translate toolkit.

**Comment by BrightXiaoHan** [comment]
Have you solved this?

**Comment by mclei-asw** [comment]
Yes, by manually adding huge_tree=True argument to XMLParser method calls.

**Comment by nijel** [comment]
Has anybody investigated what security implications this has? It seems to disable a lot of limits inside libxml2...

**Comment by tigmo** [comment]
Is there any plan on adding the huge_tree as an option?

**Comment by dxdx123** [comment]
I also encountered this problem, do you have any good suggestions?
![image](https://github.com/translate/translate/assets/14290268/e59da5c8-b1c3-439e-9306-a392cc6741f6)

**Comment by nijel** [comment]
The best suggestion we have right now is to split the files. I don't think anybody looked into the question I've raised years ago in https://github.com/translate/translate/issues/4302#issuecomment-891269117.

**Comment by nijel** [comment]
Furthermore, can you try upgrading to `lxml` 5.0.0? It builds on libxml2 2.12.3 which seems to do a lot better in parsing massive files. I've added test with a 120MB file in https://github.com/translate/translate/pull/5159, and it works just fine for me locally. I consider this big enough file to support, so if CI passes on all platforms, I'm going to close this issue.

If you still have a problem with parsing some file, and you are using `lxml` 5.0.0 (or newer), please open a separate issue and include the file to reproduce the issue.
