### ISSUE TITLE
CDATA support in Android

### ISSUE THREAD

**Issue by nijel** [translate/translate#4320]
Right now the Android strings format does not deal with CDATA. This breaks quotes as it applies unquoting to it's content.

See https://github.com/WeblateOrg/weblate/issues/1211#issuecomment-821940498 for more details.

See https://lxml.de/api.html#cdata for LXML documentation on the topic.

**Comment by rwrx** [comment]
Hello @nijel unfortunately we do have the same problem with Android XML strings which does contain HTML markup. For example we do have this XML string:

```
<string name="dialog_storage_permission_info" formatted="false"><Data><![CDATA[
    <html><head>
      <style type=\"text/css\">
        body { margin: 0px; }
      </style></head><body>
      <div style=\"background-color: transparent; color: %1$s; padding: %2$dpx;\">
        <p>This app requires <strong>permission to access all files</strong> on the storage.</p>
        <p>This permission <strong>allows</strong> this app to <strong>open</strong> and <strong>save</strong> files <strong>anywhere</strong> on the <strong>storage</strong>.</p>
        <p>This app <strong>only access files</strong> you are <strong>opening</strong> or <strong>saving</strong>.</p>
        <p>It does <strong>NOT access</strong> any other <strong>files</strong> on the <strong>storage</strong>.</p>
      </div>
    </body></html>
    ]]></Data>
</string>
```

And in Weblate it is shown this way:

![screenshot](https://github.com/translate/translate/assets/2378743/dfe0fe34-c044-4652-a9f6-de859f0317a5)

Which is very hard for translator to translate. Do you have some news for this issue? We would very appreciate if it will be possible to show these kinds of strings as they are raw XML or HTML. 

Thank you  a lot for creating Weblate, it is a great tool for translations.

**Comment by rwrx** [comment]
@nijel If I could ask, are there some bounties for implementing or fixing this specific issue? We will give bounty for this issue as it is very important for us.

**Comment by nijel** [comment]
@rwrx There is no generic bounty tool on this repo (if you have some recommendation on this, please let me know). You can reach out Weblate team at care@weblate.org if you are interested in funding a feature.

**Comment by rwrx** [comment]
@nijel Thank you a lot. I have written an e-mail.

**Comment by lucasmz-dev** [comment]
Hey, I'm wondering if after these changes if it's normal for such strings to be shown like this, or should it be more simplified and smart? I'm not familiar with these CDATA strings

![Image](https://github.com/user-attachments/assets/e9697911-115a-462e-b834-4a78941b93f6)
