### ISSUE TITLE
Proposing a PR to fix a few small typos

### ISSUE THREAD

**Issue by timgates42** [translate/translate#4382]
# Issue Type

[x] Bug (Typo)

# Steps to Replicate and Expected Behaviour

- Examine translate/convert/test_po2dtd.py and observe `preseve`, however expect to see `preserve`.
- Examine translate/filters/test_checks.py and observe `placeholds`, however expect to see `placeholder`.
- Examine translate/convert/convert.py and observe `invidividual`, however expect to see `individual`.
- Examine translate/storage/test_dtd.py and observe `graacefully`, however expect to see `gracefully`.
- Examine translate/search/test_match.py and observe `differerntly`, however expect to see `differently`.

# Notes

Semi-automated issue generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

To avoid wasting CI processing resources a branch with the fix has been
prepared but a pull request has not yet been created. A pull request fixing
the issue can be prepared from the link below, feel free to create it or
request @timgates42 create the PR. Alternatively if the fix is undesired please
close the issue with a small comment about the reasoning.

https://github.com/timgates42/translate/pull/new/bugfix_typos

Thanks.

**Comment by nijel** [comment]
> To avoid wasting CI processing resources a branch with the fix has been prepared but a pull request has not yet been created.

This makes no sense - the CI for new contributors already require maintainer approval for few months (see https://github.blog/2021-04-22-github-actions-update-helping-maintainers-combat-bad-actors/), and you are adding yet another manual step here. It's better to create the pull request directly.

**Comment by timgates42** [comment]
Thanks @nijel I didn't know that about GitHub Actions changing their policy - thanks for pointing this out. Also I've added the PR #4383 - thanks!

**Comment by timgates42** [comment]
fyi @nijel have adjusted meticulous to create PRs instead - https://github.com/timgates42/meticulous/pull/136

**Comment by nijel** [comment]
Thanks!
