### ISSUE TITLE
Domain translatehouse.org not working

### ISSUE THREAD

**Issue by nijel** [translate/translate#4410]
Both https://toolkit.translatehouse.org/ and http://docs.translatehouse.org/ are not working, not sure who is in charge there, but it would be great to fix that :-).

**Comment by rffontenelle** [comment]
Looks like it expired yesterday according to [Gandi.net's WHOIS domain lookup](https://whois.gandi.net/en/results?search=translatehouse.org), but [can be renewed by anyone](https://shop.gandi.net/en/domain/renew?search=translatehouse.org).

> Domain Name: translatehouse.org
> Registry Domain ID: D166355035-LROR
> Registrar WHOIS Server: whois.gandi.net
> Registrar URL: http://www.gandi.net
> Updated Date: 2021-08-15T22:17:07Z
> Creation Date: 2012-08-15T22:07:04Z
> Registrar Registration Expiration Date: 2021-08-15T22:07:04Z

**Comment by unho** [comment]
I am afraid I can do nothing regarding this.

**Comment by arky** [comment]
@dwaynebailey Can you take a lot at this. Thanks!

**Comment by rffontenelle** [comment]
It looks like translatehouse.org is back up again.
