### ISSUE TITLE
Add support for flutter/dart "arb" file format

### ISSUE THREAD

**Issue by yarons** [translate/translate#4436]
It looks like google's new language/framework uses an "arb" file format in place of po files.

I am not too familiar with it, but they look like plain json files, and would like to be able to use a dedicated application to edit them. I'd be happy with a barebones implementation for now, although the file format doesn't seem too complex to support.

The specification is available [over there](https://github.com/google/app-resource-bundle/wiki/ApplicationResourceBundleSpecification)

Here is a tutorial with the expected workflow, a possible application, and a few syntax examples.
As an example, the file I attempted to translate is [this one](https://gitlab.com/ChristianPauly/fluffychat-flutter/-/blob/9a52e938628df3c35e2cf7a2af6e33cdb5a0f6ed/lib/i18n/intl_messages.arb), I hope it makes for a good example of real-world usage. The [german translation](https://gitlab.com/ChristianPauly/fluffychat-flutter/-/blob/9a52e938628df3c35e2cf7a2af6e33cdb5a0f6ed/lib/i18n/intl_de.arb) sits in the same folder, as well as instruction in [that repository's readme](https://gitlab.com/ChristianPauly/fluffychat-flutter/-/blob/9a52e938628df3c35e2cf7a2af6e33cdb5a0f6ed/README.md#how-to-add-translations-for-your-language).

A new mime type should probably be created as well, but that can be done independently.

[The bug report on GNOME](https://gitlab.gnome.org/GNOME/gtranslator/-/issues/102)
[The bug report on KDE](https://bugs.kde.org/show_bug.cgi?id=417867)

**Comment by nijel** [comment]
It is already supported, see https://github.com/translate/translate/issues/3910 and https://github.com/translate/translate/pull/4040
