### ISSUE TITLE
Wrapping of PO file should take into account the East Asian Width (wide/fullwidth)

### ISSUE THREAD

**Issue by alvinhochun** [translate/translate#4452]
Previously reported on https://github.com/WeblateOrg/weblate/issues/6350

Characters with the [East Asian Width](https://unicode.org/reports/tr11/) property being "Fullwidth" or "Wide" shall be counted as two "characters" wide when wrapping messages in gettext files.

Looking at the code for a bit, since `PoWrapper` inherits `textwrap.TextWrapper`, it appears that achieving this will require an alternative implementation of `textwrap.TextWrapper`. https://bugs.python.org/issue24665 and https://github.com/python/cpython/pull/89 contain some discussions and patches to implement this in `TextWrapper`, but the changes were rejected by upstream. The author also published it as an external library: https://gitlab.com/fgallaire/cjkwrap | https://pypi.org/project/CJKwrap/

**Comment by nijel** [comment]
Proposed fix: https://github.com/translate/translate/pull/4511
