### ISSUE TITLE
Enable square brackets in keys of GWT properties

### ISSUE THREAD

**Issue by orangesunny** [translate/translate#4573]
**Issue:**
Currently, TT does not parse GWT prop. files with [] in the key. It is because of its usage in plurals: 

http://www.gwtproject.org/doc/latest/DevGuideI18nPluralForms.html
_"Hopefully this will improve over time, and we can support more standard approaches to getting translated messages with plural forms back into GWT."_

**Desired solutions:**
- Adjust TT to take [] as plural only when it's really the plural.
- Enable usage of [] in keys

**Comment by nijel** [comment]
The issue might actually be in plurals handling:

```
userItems.limit = Only {0} items can be added.
userItems.limit[one] = Only one item can be added.
userItems.limit[\=0] = No items can be added.
```
