### ISSUE TITLE
Add support for the PAPPL format

### ISSUE THREAD

**Issue by yarons** [translate/translate#4627]
https://github.com/michaelrsweet/pappl/tree/master/pappl/strings

Well, I couldn't find any documentation for this and I'm not sure why he didn't use any supported format but there it is.

The general idea is:
`"Original String" = "Translated String";`

And there's also a header file for the translations which is basically exactly the same but it has this at the beginning:
`static const char *XX_strings = ` (where XX is the ISO code for the language such as de for German and he for Hebrew).
And all the quotes are escaped.

I'm not sure it's worth implementing but it's worth mentioning that it exists.

**Comment by nijel** [comment]
That looks like http://docs.translatehouse.org/projects/translate-toolkit/en/latest/formats/strings.html, so it should already work.

**Comment by yarons** [comment]
I'm not sure about the parameter convention.

**Comment by yarons** [comment]
Apparently it's correct, I've mentioned you in the PAPPL relevant issue.

**Comment by yarons** [comment]
Wonderful, thanks.
