### ISSUE TITLE
rc file parser doesn't treat all whitespace similarly

### ISSUE THREAD

**Issue by jon-turney** [translate/translate#4642]
e.g. res.rc

```
IDD_DIALOG DIALOG 0, 0, 340, 180
CAPTION "Caption"
BEGIN
    LTEXT           "Right",IDC_STATIC_HEADER,7,0,258,8,NOT WS_GROUP
    LTEXT           "Wrong",IDC_STATIC_HEADER
                    ,7,0,258,8,NOT WS_GROUP
END
```

running `rc2po res.rc res.po`, produces res.po containing:

```
#: DIALOG.IDD_DIALOG.CAPTION
msgid "Caption"
msgstr ""

#: DIALOG.IDD_DIALOG.LTEXT.IDC_STATIC_HEADER
msgid "Right"
msgstr ""

#: DIALOG.IDD_DIALOG.LTEXT.[%27IDC_STATIC_HEADER%27]
msgid "Wrong"
msgstr ""
```

**Comment by jon-turney** [comment]
It seems that in the second case the `IDC_STATIC_HEADER` text is matching `Group(combined_constants)` rather than `constant` in the pyparsing grammar, so we end up with the a single element list for the identifer. I don't really understand why that is.

**Comment by nijel** [comment]
https://github.com/translate/translate/pull/4646 should fix this.

**Comment by jon-turney** [comment]
Thanks!
