### ISSUE TITLE
Warning about use of legacy python setup.py

### ISSUE THREAD

**Issue by flodolo** [translate/translate#4739]
Noticed this warning in a few GitHub workflows using translate-toolkit

```
Collecting translate-toolkit==3.7.*
  Downloading translate_toolkit-3.7.3-py3-none-any.whl (1.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 11.6 MB/s eta 0:00:00
  DEPRECATION: lxml is being installed using the legacy 'setup.py install' method, because it 
  does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce 
  this behaviour change. A possible replacement is to enable the '--use-pep517' option. 
  Discussion can be found at https://github.com/pypa/pip/issues/8559
```

**Comment by rffontenelle** [comment]
Hi, the deprecation warning is against lxml project. Translation toolkit us already set with a pyproject.toml file, as you can see in the root directory of the project.

**Comment by flodolo** [comment]
Sorry for the noise, I assumed it was something in translate-toolkit (and should have checked the root of the repo indeed).

**Comment by rffontenelle** [comment]
No problem at all. Thanks for taking time to report a potential issue 😉

**Comment by rffontenelle** [comment]
Just for reference, linking your new report at lxml's bug report: https://bugs.launchpad.net/lxml/+bug/1993882
