### ISSUE TITLE
phply appears to be unmaintained since 2018

### ISSUE THREAD

**Issue by a17r** [translate/translate#4784]
Unfortunately, the PHP parser chosen in https://github.com/translate/translate/issues/3625 has not received any commits [1] since its last release [2] in August 2018. And that's a problem, because it still depends on the equally unmaintained `nose` package that is broken with `>=python-3.9`, so we are quickly running into an unsustainable situation with one of the dependencies of translate-toolkit.

At least in Gentoo we have begun with cleaning up any nose revdeps and that will affect the function of translate-toolkit. [3]

See also:
[1] https://github.com/viraptor/phply/tree/master
[2] https://pypi.org/project/phply/#history
[3] https://bugs.gentoo.org/888253

**Comment by nijel** [comment]
`phply` itself seems to have no issues with Python >= 3.9. It's just it's test suite relying on `nose`. Have you tried reaching @viraptor about that?

I don't think anything will change in the translate-toolkit. `phply` works well for our purpose and there seems to be no alternatives.

**Comment by a17r** [comment]
The problem with tests not working is how will you verify that it won't amass regressions at runtime? It is unlikely that we will keep a package available on someone's word that it is working correctly with untested Python versions.

**Comment by nijel** [comment]
Translate toolkit tests are covering everything it needs. Of course it does not cover full phply...

**Comment by viraptor** [comment]
I'm happy to fix it to support later pythons (likely by migrating to pytest), but I'm not personally using it anymore.
If anyone wants to keep maintaining it and/or take over, you're very welcome to get involved.

**Comment by a17r** [comment]
That would be great. There is nose2pytest to help with converting but I don't know how much of your nose usage it covers.

**Comment by viraptor** [comment]
https://github.com/viraptor/phply/releases/tag/1.2.6 released with pytest and checks from py3.6 to py3.10 through github actions.

**Comment by a17r** [comment]
Thanks a lot!

**Comment by viraptor** [comment]
Let me know if there are any other problems. While I don't have reasons/time to push the project forwards, I'd like to keep it in a usable state so others can take over in the future.

**Comment by nijel** [comment]
@viraptor Having the release on PyPI as well would be useful :-). It still has 1.2.5, see https://pypi.org/project/phply/.

**Comment by viraptor** [comment]
Every time :facepalm: 
Done now.

**Comment by nijel** [comment]
@viraptor I had that issue often as well util I automated that using https://github.com/pypa/gh-action-pypi-publish
