### ISSUE TITLE
Plural tags and counts for i18next

### ISSUE THREAD

**Issue by nijel** [translate/translate#4812]
It turns out that i18next decided to build their own plural rules instead of relying on CLDR like nearly everybody else. Because of that plural tags differ for some language in translate-toolkit and the original code.

See https://github.com/WeblateOrg/weblate/issues/8625

Somebody needs to go through https://github.com/i18next/i18next/blob/a334583a7752bf83a62da10fae035af53641784b/src/PluralResolver.js#L5-L39, and figure out differences compared to CLDR. Once this is done, the exceptions need to be handled in the i18next storage.

**Comment by nijel** [comment]
Okay, I think it's a bug in i18next, there were already similar in the past, see https://github.com/i18next/i18next/issues/1607

**Comment by SamantazFox** [comment]
> Okay, I think it's a bug in i18next, there were already similar in the past, see [i18next/i18next#1607](https://github.com/i18next/i18next/issues/1607)

Ok, thanks! I'll open an issue there, then!

**Comment by SamantazFox** [comment]
> It turns out that i18next decided to build their own plural rules instead of relying on CLDR like nearly everybody else. Because of that plural tags differ for some language in translate-toolkit and the original code.

I looked more into this. [They moved to the v4 format exactly for that reason](https://github.com/i18next/i18next/pull/1653).

So now, the v3 plural rules are set into the stone (and forever broken) and the v4 rules depends on the `Intl` Javascript API, which is maintained by upstream (NodeJS/Chromium/Firefo/etc...) and change according to the CLDR.

**Comment by nijel** [comment]
As Weblate supports v4 now as well, I've added hint about plurals to our docs: https://github.com/WeblateOrg/weblate/commit/bf7db3c40c45c3dc16ba0b841c55f1ecb6dcdea7
