### ISSUE TITLE
rc2po missing dependencies on Ubuntu 22.04.2

### ISSUE THREAD

**Issue by Tyrben** [translate/translate#4850]
Note: I return this issue here since I think many people will encounter it. Maybe you can do something. But I think it's a Ubuntu/Debian packager problem. Maybe are you in relation with them?

## How to reproduce

1. install the package translate-toolkit
2. run the command `rc2po --version`

## Result

You obtain a python crash Traceback:

> Traceback (most recent call last):
>   File "/usr/bin/rc2po", line 33, in <module>
>     sys.exit(load_entry_point('translate-toolkit==3.6.0', 'console_scripts', 'rc2po')())
>   File "/usr/bin/rc2po", line 25, in importlib_load_entry_point
>     return next(matches).load()
>   File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
>     module = import_module(match.group('module'))
>   File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
>   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
>   File "/usr/lib/python3/dist-packages/translate/convert/rc2po.py", line 27, in <module>
>     from translate.storage import po, rc
>   File "/usr/lib/python3/dist-packages/translate/storage/rc.py", line 30, in <module>
>     from pyparsing import (
> ImportError: cannot import name 'c_style_comment' from 'pyparsing' (/usr/lib/python3/dist-packages/pyparsing.py)

## Expected

A version number appears

**Comment by nijel** [comment]
Some formats have additional dependencies, please see https://github.com/translate/translate#requirements

**Comment by Tyrben** [comment]
I'm OK with that.
And if I was using the installer instead of the deb package, I should have used `pip install translate-toolkit[all]` .
But, a package is what it is and after its installation, all should be functional. All dependencies included. So I bet more for a misconception of the debian/ubuntu package.
I reported it here not so that you fix it, but so that you acknowledge the deb package problem.

**Comment by nijel** [comment]
Yes, optional dependencies should be listed as `Suggests` or `Recommends` in the package.
