### ISSUE TITLE
rc2po adds 2 extra lines when the msg contains one '\n'

### ISSUE THREAD

**Issue by Tyrben** [translate/translate#4854]
When the input data (RC format) contains "C-style" special character '\n', the resulting PO / POT file contains a text on 3 lines instead of 1.

Input (extract):

```C
STRINGTABLE
BEGIN
    ID_SENDTOMAPPING        "Send to mapping\nSend to mapping"
    ID_SENDTOMAPPING_MULTI  "Send multi to mapping\nSend multi to mapping"
END
```

Output (extract):

```
#: STRINGTABLE.ID_SENDTOMAPPING
msgid ""
"Send to mapping\n"
"Send to mapping"
msgstr ""
```

Expected output

```
#: STRINGTABLE.ID_SENDTOMAPPING
msgid "Send to mapping\nSend to mapping"
msgstr ""
```

When a string to translate contains "C-style" special characters, the converter should not interpret, but transmit "as-is".

**Comment by nijel** [comment]
This is correct, PO files are typically formatted that way for strings containing new lines.
