### ISSUE TITLE
rc2po fills the wrong keys

### ISSUE THREAD

**Issue by Tyrben** [translate/translate#4874]
If there is a way to extract all languages in one batch, tel me. But this bug report is after extracting one .PO file for each language. Producing several files:
trans.en.po, trans.de.po, trans.fr.po

From a translator perspective, English should be the reference (called msgid in PO).
https://en.opensuse.org/SDB:Localization_work_with_po_files

So, the behaviour is not it.
the generated file for instance, in German, is:

> #: DIALOGEX.IDD_DIALOG_PEN.CAPTION
> msgid "Eigenschaften des Striches"
> msgstr ""

and in English:

> #: DIALOGEX.IDD_DIALOG_PEN.CAPTION
> msgid "Pen Settings"
> msgstr ""

What is expected should be: 

> #: DIALOGEX.IDD_DIALOG_PEN.CAPTION
> msgid "Pen Settings"
> msgstr "Eigenschaften des Striches"

It's a bug report AND a question: how to manage rc2po to make the job?

**Comment by nijel** [comment]
You should use `--template=TEMPLATE` with English to get both languages into one PO file.
