### ISSUE TITLE
Plural issues on Android due to update to CLDR 41

### ISSUE THREAD

**Issue by johan12345** [translate/translate#4899]
With PR #4679, plural rules were updated to follow CLDR 41, adding additional plural types for some languages. However, the latest releases of Android only supports CLDR 38 so far, according to the [docs](https://developer.android.com/guide/topics/resources/internationalization#versioning-nougat). This means that for languages like `es`, `it`, `pt` and `pt_PT`, Weblate will require a `many` plural type - but Android does not support these plural types yet and thus produces a lint error.

Does it make sense to downgrade the data in [`plural_tags`](https://github.com/translate/translate/blob/master/translate/lang/data.py#L384) to CLDR 38? Or should those be specifically overriden in the implementation for [Android](https://github.com/translate/translate/blob/master/translate/storage/aresource.py)?

**Comment by nijel** [comment]
Presently, this list is shared for more file formats, so probably a separate one is needed for Android to stick with CLDR 38. The previous version was CLDR 37, so some additions in the PR are needed for Android as well.

As for Weblate, it will need additional definitions in https://github.com/WeblateOrg/language-data/ to match this (it currently uses the latest CLDR as well).

**Comment by johan12345** [comment]
reported on Google's issue tracker: https://issuetracker.google.com/issues/280634462

**Comment by nijel** [comment]
...which is now Won't Fix (Obsolete), what really doesn't explain anything.

Anyway, Android seems to be upgrading CLDR frequently, the question is how to deal with that:

* Keep separate rules for Android and update them when Android with updated support is released. This is more accurate, but also requires more maintenance.
* Always follow the latest CLDR and ignore the differences. Android will follow up at some point anyway.
* Update CLDR data once it has been released in Android. This will postpone it for everybody else.

This was merely a non-issue before changes in CLDR 38 – the only changes were additions of new languages, so it didn't break existing ones. In recent CLDR releases, rules for existing languages are changing and that makes it harder to deal with.

**Comment by nijel** [comment]
@emmapeel2 That is definitely not related to plural definitions, please open a separate issue here: https://github.com/WeblateOrg/weblate/issues/new?assignees=&labels=&projects=&template=bug_report.yml

**Comment by emmapeel2** [comment]
> @emmapeel2 That is definitely not related to plural definitions, please open a separate issue here: https://github.com/WeblateOrg/weblate/issues/new?assignees=&labels=&projects=&template=bug_report.yml

Ok, this is the new ticket: https://github.com/WeblateOrg/weblate/issues/10887

**Comment by nijel** [comment]
I don't think there is a good way to address this. As there is no reliable way to recognize which plural rules the strings file is using, we can only make assumptions. And assuming it is using a current standard is IMHO better than assuming it uses something older. Android is usually quite fast in adopting CLDR changes, and so we are, so I think the best is to keep things as they are right now. There might be some period in time when the tools will disagree.
