### ISSUE TITLE
translate-toolkit-3.9.2-1.fc39.x86_64/usr/bin/mozfunny2prop --manpage hangs

### ISSUE THREAD

**Issue by juhp** [translate/translate#4957]
I tried building the latest release to prepare an update for Fedora, but the build hangs for me at:

```
:
+ for prog in /var/home/petersen/fedora/translate-toolkit/BUILDROOT/translate-toolkit-3.9.2-1.fc39.x86_64/usr/bin/*
++ basename /var/home/petersen/fedora/translate-toolkit/BUILDROOT/translate-toolkit-3.9.2-1.fc39.x86_64/usr/bin/moz2po
+ progname=moz2po
+ case ${progname} in
+ PYTHONPATH=.
+ /var/home/petersen/fedora/translate-toolkit/BUILDROOT/translate-toolkit-3.9.2-1.fc39.x86_64/usr/bin/moz2po --manpage
+ grep -q .SH /var/home/petersen/fedora/translate-toolkit/BUILDROOT/translate-toolkit-3.9.2-1.fc39.x86_64/usr/share/man/man1/moz2po.1
+ for prog in /var/home/petersen/fedora/translate-toolkit/BUILDROOT/translate-toolkit-3.9.2-1.fc39.x86_64/usr/bin/*
++ basename /var/home/petersen/fedora/translate-toolkit/BUILDROOT/translate-toolkit-3.9.2-1.fc39.x86_64/usr/bin/mozfunny2prop
+ progname=mozfunny2prop
+ case ${progname} in
+ PYTHONPATH=.
+ /var/home/petersen/fedora/translate-toolkit/BUILDROOT/translate-toolkit-3.9.2-1.fc39.x86_64/usr/bin/mozfunny2prop --manpage
```

**Comment by juhp** [comment]
Actually this is not new, at least in the sense I can reproduce also with 3.8.4.
I was building on Rawhide, which could also affect it.

**Comment by nijel** [comment]
This program does not accept any parameters, it just parses stdin:

https://github.com/translate/translate/blob/29df72d4655ad5b8b3fc7f13b473e77a977f09d5/translate/convert/mozfunny2prop.py#L158-L163

It behaves this way for 16 years, so this is really not a new thing ;-).

**Comment by juhp** [comment]
Okay... but it builds fine in the Fedora build system, but hangs for me locally (dunno if it is something to do with my environment?)  Noone else faces/faced this build problem?

**Comment by nijel** [comment]
Probably depends on what stdin is. In the build system, it will be most likely /dev/null, while on your system it is waiting for the input from the terminal. Anyway, testing `mozfunny2prop --manpage` is not really useful, so should be removed from the package build.
