### ISSUE TITLE
Support for Android resource converter

### ISSUE THREAD

**Issue by jordimas** [translate/translate#4980]
Hello. 
I'm currently using https://github.com/miracle2k/android2po to convert from Android resources (bilingual) to PO files. However, the project is no longer maintained. 

My understanding is that aresource.py provides the storage support for implementing a Android Resources to PO but this converter is not currently implemented. Is this correct?

**Comment by nijel** [comment]
Yes, implementing android2po on top of current storages should be pretty easy.

**Comment by jordimas** [comment]
Thanks, I will give a try. Is android2po something that you will be willing to consider as contribution to the project? 
(I do not know if you still accept new conversors)

**Comment by nijel** [comment]
Yes, contributions are welcome.

**Comment by nijel** [comment]
Fixed by https://github.com/translate/translate/pull/4983
