### ISSUE TITLE
Android: Some strings marked as `translatable="false"` still treated as translatable

### ISSUE THREAD

**Issue by Wohlstand** [translate/translate#5041]
Hello!

I do have the `arrays.xml` file that has the data in this form:
```xml
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <string-array name="rendererValues">
        <item></item>
        <item>sdl</item>
        <item>opengles</item>
        <item>opengles11</item>
    </string-array>
    <string name="rendererDefault">Default</string>
    <string name="rendererSdl" translatable="false">SDL2</string>
    <string name="rendererGles" translatable="false">OpenGL ES 2.0+</string>
    <string name="rendererGles11" translatable="false">OpenGL ES 1.1</string>
</resources>
```

And I marked them as non-translatable. However, they still appear at the translation project in WebLate as translatable strings.

The compelte file itself: https://github.com/Wohlstand/TheXTech/blob/main/android-project/thextech/src/main/res/values/arrays.xml

**Comment by nijel** [comment]
The string is read-only in Weblate, what matches non-translatable state in the file: https://hosted.weblate.org/translate/thextech/android-launcher-arrays/en/?checksum=b09cac1355411285

**Comment by Wohlstand** [comment]
Huh... I never expected there are "read-only" they are, I just confused: I expected they won't appear at all, but they appears, but I wasn't sure they are "read-only". Now I see, thanks for clarification!
By the way, when the source line is open, it doesn't show "read-only', and at the same time, it doesn't allows me to modify the string. So, another confusion factor.
