### ISSUE TITLE
Add support for Mobile Kotlin resources

### ISSUE THREAD

**Issue by nijel** [translate/translate#5144]
These seem to be like Android, just using `<plural>` instead of `<plurals>`, see https://github.com/icerockdev/moko-resources#example-3---plural-string.

I couldn't find official documentation for this format besides the project README, what really gives just examples and doesn't provide format specification.

**Comment by mikedawson** [comment]
Hi,

The idea of Moko resources is that you should be able to use your existing Android xml files with Kotlin Multiplatform (Android, Web, Desktop/JVM, iOS, etc). As per the README the developer is expected to have one strings.xml (unlike other Android projects where there can be multiple strings.xml) and plurals need to be in a separate file (which as above uses "plural" not "plurals" - no idea why). This means there must be two separate base files, which on Weblate can be handled by having two components in one project.

To be honest, it seems like the Moko resources project is not getting the love it needs. I think people might move to [Lyricist](https://github.com/adrielcafe/lyricist) - which can import strings.xml .

To be honest, I think if the Android strings support is updated to recognize both plural and plurals, that should do the trick and I can't see it having any adverse side effects.

**Comment by nijel** [comment]
Reading both tags would be simple, but when adding new strings you can start with a file with none of these tags, and then it needs a sensible behavior. A separate format is a better way as it will make it clear what it does without relying on some heuristics.

Anyway, adding a format on top of Android which just changes a single tag is easy, I will do that later today.

If you are interested in adding [Lyricist](https://github.com/adrielcafe/lyricist) support, please open a separate issue with a description of the format and links to a documentation. I know documenting formats is frequently not done, but how then library authors expect support from other tooling?.

**Comment by mikedawson** [comment]
I think it would be OK if you just use the official Android xml (e.g. plurals) when adding a string. If someone is using the unofficial version, then they need to do so manually.

Lyricist supports using strings.xml . It also supports putting strings directly into Kotlin code (does not seem like a good idea to me - translation and coding are different skill sets). I don't think there is any need for explicitly adding support to translate toolkit, we can use strings.xml and let Lyricist process the strings.xml file.
