### ISSUE TITLE
Weird handling of C1 control characters in .properties files

### ISSUE THREAD

**Issue by eemeli** [translate/translate#5199]
When encoding, C1 control characters (U+0000 - U+001F) are not `\` escaped except for `\f`, `\n`, `\r`, and `\t`.

When decoding, escaped C1 control characters (except as above) are not decoded, but left as literal `\u` strings.

This leads to the following unexpected behaviour:

```python
from translate.misc import quote

quote.javapropertiesencode(quote.propertiesdecode('\u0001')) # → '\x01' (expected '\\u0001')

quote.javapropertiesencode(quote.propertiesdecode('\\u01')) # → '\\\\u0001' (expected '\\u0001')
```

The same behaviour also happens with `quote.java_utf8_properties_encode()`.

**Comment by eemeli** [comment]
> The second is intentional, the control chars are shown escaped:

Note that my example is showing the results of a decode + encode round-trip. Currently, an escaped control code in a .properties file ends up getting re-written in the file with doubled escaping, and that's pretty broken.

**Comment by nijel** [comment]
https://github.com/translate/translate/pull/5203 is my attempt to address this.
