### ISSUE TITLE
Translate org app requests

### ISSUE THREAD

**Issue by phlax** [translate/translate#5210]
Hi @nijel - there are 3 apps requesting permissions to the translate org:

- codecov
- deepsource.io
- coderabbitai

lmk if you want/need me to approve them

**Comment by nijel** [comment]
I think codecov and deepsource.io are in use. coderabbitai is not that useful as I hoped for, so I'd remove that one. Is there any chance I can get permissions to manage this?

**Comment by nijel** [comment]
Thanks! Yes, I'm not on live chat things...
