### ISSUE TITLE
Removing items during iteration can result in bugs

### ISSUE THREAD

**Issue by AryazE** [translate/translate#5215]
Removing the children of a node on [this line](https://github.com/translate/translate/blob/d7922d50628dfc2964e9ae69437bf0c95851e2ce/translate/misc/xml_helpers.py#L300) can result in missing some of the children.
A way that can fix this might be
```python
while len(node) > 0:
   node.pop()
```

**Comment by nijel** [comment]
Thask for your suggestion, pull requests are welcome!
