### ISSUE TITLE
tarball name changed from 3.12.2 to 3.13.0

### ISSUE THREAD

**Issue by sudipshil9862** [translate/translate#5312]
in 3.12.2 version the tarball name was: translate-toolkit-3.12.2.tar.gz
from 3.13.0 version onwards the tarball renamed as: translate_toolkit-3.12.2.tar.gz
translate-toolkit  -> translate_toolkit

In that case, we need to change the source link.

Is this renaming of the tarball intentional?
https://github.com/translate/translate/releases

**Comment by sudipshil9862** [comment]
The website download link is also broken:
http://toolkit.translatehouse.org/

This is not valid anymore:
https://github.com/translate/translate/releases/download/3.13.2/translate-toolkit-3.13.2.tar.gz

**Comment by nijel** [comment]
This is intentional and is caused by using recent setuptools, see https://setuptools.pypa.io/en/stable/history.html#v69-3-0
