### ISSUE TITLE
FutureWarning: This search incorrectly ignores the root element, and will be fixed in a future version.  If you rely on the current behaviour, change it to './/body'

### ISSUE THREAD

**Issue by rffontenelle** [translate/translate#5323]
When converting using po2tmx, the following is raised:

```
/usr/lib/python3.12/site-packages/translate/storage/lisa.py:312: FutureWarning: This search incorrectly ignores the root element, and will be fixed in a future version.  If you rely on the current behaviour, change it to './/body'
  self.body = self.document.find("//%s" % self.namespaced(self.bodyNode))

```

This warning comes from https://github.com/lxml/lxml/commit/3a8caecc0f94d8e00ab116a4b32e57675140eb4d as of lxml 5.1.1

Context of the code executed:

https://github.com/translate/translate/blob/47c3819aef6998bde5a1e8c2d142eadad79e3967/translate/storage/lisa.py#L306-L312

Steps to reproduce:
- Have lxml 5.1.1 or newer installed
- Run `po2tmx -l your_language_code -i some_input.po -o some_output.tmx`

**Comment by nijel** [comment]
The described behavior is intentional for translate-toolkit and I didn't find a way to silent the warning. Suggestions are welcome.

**Comment by rffontenelle** [comment]
If that's the case, then let's follow the last part of the warning: "If you rely on the current behaviour, change it to './/body'"
