### ISSUE TITLE
docs.translatehouse.org <pre> tags are illegible

### ISSUE THREAD

**Issue by mr-bronson** [translate/translate#5336]
Sections attempting to display code, input, output use `<pre>` elements.  These are given a background color on line 734 of bootstrap.css:
`background-color: #f5f5f5;`
which overlays the parent element's background color from its `class="highlight"`; pygments.css line 7:
` background: #111111;`
So when the content inside the `<pre>` element sets its own text colors, predominantly white (`#ffffff`), which of course is too similar to `#f5f5f5` to be visible.

Here's a screenshot of one from [this page](https://docs.translatehouse.org/projects/translate-toolkit/en/latest/commands/txt2po.html):
![translatehouse-invisible-pre-text](https://github.com/user-attachments/assets/279afb5c-9676-46cb-9101-90ae8bc8332d)

This affects all but the last `<pre>` element on this page.  In that case, the content does not specify any text color, so it inherits the color specified by bootstrap.css which overrides the color set by class `highlight`.

So, for most of these, adding a `.highlight > pre` selector might help, but that would break the last case, making black on black.

There are other issues with this website, which makes me wonder whether it's being actively maintained:
1. The "Site" and "Page" buttons in the top menu do nothing.
2. The footer has a copyright notice from last year (not that I care; it's just an indication of neglect).
3. The footer gives a link to a broken site: Created using [Sphinx](http://sphinx.pocoo.org/) 8.0.2.  (It gives a 400 HTTP error.)

**Comment by rffontenelle** [comment]
It seems all the issues are all related to the theme used by Translate House's software: https://github.com/translate/sphinx-themes: "Site" is from 'globaltoc.html', "Page" is from 'localtoc.html' and the footer's broken link is from 'layout.html'

Only the copyright year is from this project's [docs/conf.py](https://github.com/translate/translate/blob/dab8006c2110c4a065483f37853eed3a218efe00/docs/conf.py#L23).

**Comment by nijel** [comment]
I guess the theme is not up-to-date with the current Sphinx as it was last updated 11 years ago. Maybe it's time to switch to a third-party theme instead? We're using [Furo](https://pradyunsg.me/furo/quickstart/) at Weblate, and it works well. I'm open to other suggestions as well.

**Comment by nijel** [comment]
https://github.com/translate/translate/pull/5338 does switch to Furo (and some other needed changes), feedback is welcome.
