### ISSUE TITLE
sub2po fail to create POT file from srt file

### ISSUE THREAD

**Issue by petterreinholdtsen** [translate/translate#5372]
This is also reported as <URL: https://bugs.debian.org/1084811 >.

I am unable to use sub2po to generate a POT file from a srt file.  Am I doing something wrong, or is this supposed to work?  I tried to clone this git repository and run the program from here, as well as using the Debian package.  Here is a test run:

```
% ls -lh  ../Ada_Zangeman_English.en.srt ../Ada_Zangeman_English.en.pot 
ls: cannot access '../Ada_Zangeman_English.en.pot': No such file or directory
-rw-r--r-- 1 user group 48K okt.   9 13:06 ../Ada_Zangeman_English.en.srt
% python3 ./translate/convert/sub2po.py -P  ../Ada_Zangeman_English.en.srt ../Ada_Zangeman_English.en.pot 
processing 1 files...
sub2po.py: WARNING: Error processing: input ../Ada_Zangeman_English.en.srt, output ../Ada_Zangeman_English.en.pot, template None: marshal data too short
[###########################################] 100%
% ls -lh  ../Ada_Zangeman_English.en.srt ../Ada_Zangeman_English.en.pot 
-rw-r--r-- 1 user group   0 okt.   9 14:03 ../Ada_Zangeman_English.en.pot
-rw-r--r-- 1 user group 48K okt.   9 13:06 ../Ada_Zangeman_English.en.srt
%
```

Is this supposed to work or I am doing something wrong?

**Comment by rffontenelle** [comment]
Can you please share: your translate-toolkit version, your Python version, and this 'Ada_Zangeman_English.en.srt' file ?

**Comment by petterreinholdtsen** [comment]
[Rafael Fontenelle]
> Can you please share: your translate-toolkit version, your Python
> version, and this 'Ada_Zangeman_English.en.srt' file ?

Sure.  This happen with both translate-toolkit version 3.8.4-1 and the
latest git master branch just fetched using 'git clone
https://github.com/translate/translate'.   The example I showed here was
using the git master branch.  The python version is 3.11.2.
A very short edition of the 'Ada_Zangeman_English.en.srt' file is shown
in the Debian bug report, the complete file is available from
<URL: https://codeberg.org/pere/text-ada-zangemann/src/branch/video-subtitle/video >.
It do not seem to matter if there are two or many strings in the .srt
file.

-- 
Happy hacking
Petter Reinholdtsen

**Comment by rffontenelle** [comment]
I'm unable to reproduce the error in my Arch (python 3.12.6 + translate-toolkit 3.13.3) nor in a Debian Bookworm container with same versions. In both cases, POT was generated without issue.

Have you tried to increase the error level, using `--errorlevel` flag, to see if some useful insight comes up?

**Comment by petterreinholdtsen** [comment]
[Rafael Fontenelle]
> I'm unable to reproduce the error in my Arch (python 3.12.6 +
> translate-toolkit 3.13.3) nor in a Debian Bookworm container with same
> versions. In both cases, POT was generated without issue.

Good to hear.  Then it should not be a fundamental problem with the code.

> Have you tried to increase the error level, using `--errorlevel` flag,
> to see if some useful insight comes up?

Ah, did not know that was the way to get more debug info.  Tried just
now:

% python3 ./translate/convert/sub2po.py --errorlevel traceback -P  ../Ada_Zangeman_English.en.srt ../Ada_Zangeman_English.en.pot 
processing 1 files...
sub2po.py: WARNING: Error processing: input ../Ada_Zangeman_English.en.srt, output ../Ada_Zangeman_English.en.pot, template None: Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/translate/misc/optrecurse.py", line 607, in recursiveprocess
    success = self.processfile(
              ^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3/dist-packages/translate/convert/convert.py", line 233, in processfile
    return super().processfile(
           ^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3/dist-packages/translate/misc/optrecurse.py", line 687, in processfile
    if fileprocessor(inputfile, outputfile, templatefile, **passthroughoptions):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/scratch/pere/src/text-ada-zangemann/video/translate/./translate/convert/sub2po.py", line 104, in convertsub
    from translate.storage import subtitles

  File "/usr/lib/python3/dist-packages/translate/storage/subtitles.py", line 36, in <module>
    from aeidon import Subtitle, documents, newlines

  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load

  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked

  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked

  File "<frozen importlib._bootstrap_external>", line 936, in exec_module

  File "<frozen importlib._bootstrap_external>", line 1069, in get_code

  File "<frozen importlib._bootstrap_external>", line 729, in _compile_bytecode

EOFError: marshal data too short

[###########################################] 100%
%

This did not make me any wiser.  Do you understand what is going wrong
here?
-- 
Happy hacking
Petter Reinholdtsen

**Comment by nijel** [comment]
Something went wrong with some byte-compiled Python files. Try reinstalling aeidon (which seem to be causing the issue):

```
pip uninstall aeidon
pip install aeidon
```

**Comment by rffontenelle** [comment]
Please (preferably before using the above suggestion) run `python -c 'import aeidon; print(aeidon.__version__)'` to check if the returned version is `1.11`

Debian provides 'python3-aeidon' package as dependency of 'translate-toolkit', so you should at least have these. Reinstalling these instead of using pip might be a good idea, unless you're willing to use pip to install newer translate-toolkit version and its dependencies.

**Comment by petterreinholdtsen** [comment]
[Rafael Fontenelle]
> Please (preferably before using the above suggestion) run `python -c
> 'import aeidon; print(aeidon.__version__)'` to check if the returned
> version is `1.11`
>
> Debian provides 'python3-aeidon' package as dependency of
> 'translate-toolkit', so you should at least have these. Reinstalling
> these instead of using pip might be a good idea, unless you're willing
> to use pip to install newer translate-toolkit version and its
> dependencies.

Sadly, I had already tried to remove all used pyc files before I saw
your suggestions to debug this, based on a web page that also suggested
the pyc files were a problem.  I had a strace output, and ran this
command:

 sudo rm  $(grep pyc test.strace |cut -d\" -f 2|sort -u)

After getting rid of all pyc files, the script started working. :)

-- 
Happy hacking
Petter Reinholdtsen

**Comment by rffontenelle** [comment]
Glad it is working again!
