### ISSUE TITLE
Support property list (.plist) format

### ISSUE THREAD

**Issue by friedelwolff** [translate/translate#633]
_Version: 1.2.0_

The property list (.plist) format is used on Mac OSX. There is a library to read and write the format:

http://docs.python.org/library/plistlib.html

Note that the library was only available in the Mac-specific library before Python 2.6.

**Comment by anentropic** [comment]
it looks like a plist converter would also be the basis of support for Apple `.stringsdict` format (which is a plist file)

**Comment by nijel** [comment]
stringsdict implemented in https://github.com/translate/translate/pull/4398
