### ISSUE TITLE
Create a linguist.py language file to handle .ts plurals

### ISSUE THREAD

**Issue by dwaynebailey** [translate/translate#786]
_Version: trunk_

Visit http://www.koders.com/cpp/fidE7B7E83C54B9036EB7FA0F27BC56BCCFC4B9DF34.aspx#L200  to see the complete list of plurals for .ts.

Seems to cover almost all and more of the languages we might need.  Its not directly clear how these would convert to the ISO codes we see in Qt Linguist files.

They also have a neat list of plural forms that could be quite interesting to use in the editing widget.

**Comment by ossilator** [comment]
qt linguist's plural rules are directly derived from https://unicode-org.github.io/cldr-staging/charts/latest/supplemental/language_plural_rules.html (at whatever location was current at that time). the gettext style expressions were probably verified against / adjusted to the gettext source code, but i don't remember any more.

so if anything needs to be done, it would be syncing up with cldr.

**Comment by nijel** [comment]
The CLDR data is already present because it is used by other formats. It does differ from default Gettext in some cases (but that's covered by https://github.com/translate/translate/issues/3578). Anyway if .ts plurals is based on CLDR, it makes sense to switch to it.

**Comment by nijel** [comment]
https://github.com/WeblateOrg/weblate/issues/7427 made me look into Turkish. CLDR lists [two forms - one / other](https://unicode-org.github.io/cldr-staging/charts/latest/supplemental/language_plural_rules.html#tr), while Qt code has Turkish between [japaneseStyleLanguages](https://github.com/qt/qttools/blob/ce05219da0750a3be429b396ea0d13980aa14d70/src/linguist/shared/numerus.cpp#L146) which only have single plural form. So clearly there are differences from the CLDR definitions...

**Comment by nijel** [comment]
Qt numerus rules might be based on some CLDR version, but it is not being updated, what makes it diverge from the translate-toolkit implementation. For example CLDR recently introduced modulo 1000000 condition for `fr`, `pt_BR` and other langauges.

There is a Qt issue to bring this in sync with CLDR, but with not apparent progress: https://bugreports.qt.io/browse/QTBUG-61473

**Comment by nijel** [comment]
What is most likely needed is to go through https://github.com/qt/qttools/blob/85e769fc36c1c9da995f5761bf9cca4b37e7eaa1/src/linguist/shared/numerus.cpp and get a list of plural forms from that. The file hasn't been touched for years, so that is apparently the source of truth for Qt.

**Comment by ossilator** [comment]
yes, that file is the source of truth for qt.

as i'm hinting at in the qt issue you linked, qt can't just update existing rules due to this causing backwards incompatibility with old .ts files. it would be probably a good idea to spin off a task to rectify that in the file format (that's fundamentally no big deal, as it's xml and versioned - only upgrading existing translations losslessly would be a bit challenging ...).
